#pragma checksum "D:\Learningportal\Learning-System\Mba_Notes\note.Master" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "6EB42CE871E94BE914DEDD4D134EA4F98C9FDBA9"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    
    #line 330 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 337 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 328 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 326 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 332 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 246 "D:\Learningportal\Learning-System\Mba_Notes\note.Master"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 343 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 246 "D:\Learningportal\Learning-System\Mba_Notes\note.Master"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 342 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    #line 333 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 329 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 331 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 338 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 334 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 325 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 246 "D:\Learningportal\Learning-System\Mba_Notes\note.Master"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 246 "D:\Learningportal\Learning-System\Mba_Notes\note.Master"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 327 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 336 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 246 "D:\Learningportal\Learning-System\Mba_Notes\note.Master"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class mba_notes_note_master : global::Learning_System.Mba_Notes.note {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.mba_notes_note_master.@__PageInspector_LoadHelper("SetTraceData");
        
        private System.Web.UI.ITemplate @__Template_ContentPlaceHolder1;
        
        private static bool @__initialized;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public mba_notes_note_master() {
            ((global::Learning_System.Mba_Notes.note)(this)).AppRelativeVirtualPath = "~/Mba_Notes/note.Master";
            if ((global::ASP.mba_notes_note_master.@__initialized == false)) {
                global::ASP.mba_notes_note_master.@__initialized = true;
            }
            this.ContentPlaceHolders.Add("contentplaceholder1");
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(this.Context.ApplicationInstance));
            }
        }
        
        [TemplateContainer(typeof(Learning_System.Mba_Notes.note))]
        [TemplateInstanceAttribute(System.Web.UI.TemplateInstance.Single)]
        public virtual System.Web.UI.ITemplate Template_ContentPlaceHolder1 {
            get {
                return this.@__Template_ContentPlaceHolder1;
            }
            set {
                this.@__Template_ContentPlaceHolder1 = value;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n\r\n\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    \r\n    <meta charset=\"utf-8\">\r\n    <m" +
                    "eta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n    <link re" +
                    "l=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstr" +
                    "ap.min.css\">\r\n    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4." +
                    "1/jquery.min.js\"></script>\r\n    <script src=\"https://cdnjs.cloudflare.com/ajax/l" +
                    "ibs/popper.js/1.14.7/umd/popper.min.js\"></script>\r\n    <script src=\"https://maxc" +
                    "dn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"></script>\r\n    <link re" +
                    "l=\"stylesheet\" href=\"https://pro.fontawesome.com/releases/v5.10.0/css/all.css\" /" +
                    ">\r\n    <link href=\"mcsdash.css\" rel=\"stylesheet\" />\r\n   <style>\r\n       /* Sideb" +
                    "ar Styles */\r\n#sidebar {\r\n    position: fixed;\r\n    top: 5rem;\r\n    left: 0;\r\n  " +
                    "  width: 0;\r\n    height: calc(100vh - 5rem);\r\n    background-color: #343a40;\r\n  " +
                    "  color: #fff;\r\n    overflow-x: hidden;\r\n    overflow-y: auto;\r\n    z-index: 999" +
                    ";\r\n    transition: width 0.3s ease;\r\n}\r\n\r\n#content {\r\n    margin-top: 5rem; /* A" +
                    "djusted to account for navbar height */\r\n    margin-left: 0;\r\n    width: 100%;\r\n" +
                    "    transition: margin-left 0.3s ease;\r\n}\r\n\r\n#sidebar a {\r\n    color: #fff;\r\n   " +
                    " text-decoration: none;\r\n    display: block;\r\n    padding: 0.5rem 1rem;\r\n}\r\n\r\n#s" +
                    "idebar a:hover {\r\n    background-color: #495057;\r\n}\r\n\r\n#sidebar ul {\r\n    paddin" +
                    "g: 0;\r\n    list-style: none;\r\n    margin: 0;\r\n}\r\n\r\n#sidebar ul li {\r\n    padding" +
                    ": 0;\r\n}\r\n\r\n#sidebar .submenu {\r\n    display: none;\r\n    padding-left: 1rem;\r\n}\r\n" +
                    "\r\n/* Open Sidebar Styles */\r\n.sidebar-open #sidebar {\r\n    width: 30%;\r\n}\r\n\r\n.si" +
                    "debar-open #content {\r\n    margin-left: 30%;\r\n}\r\n\r\n.submenu-toggle {\r\n    displa" +
                    "y: flex;\r\n    justify-content: space-between;\r\n    align-items: center;\r\n    wid" +
                    "th: 100%;\r\n}\r\n\r\n/* Toggle Icon Styles */\r\n.fas.fa-caret-down {\r\n    transition: " +
                    "transform 0.3s ease;\r\n    font-size: 1rem;\r\n}\r\n\r\n.rotate {\r\n    transform: rotat" +
                    "e(180deg);\r\n}\r\n\r\n/* Responsive Menu Bar */\r\n#menu-bar {\r\n    padding-top: 6rem; " +
                    "/* Adjusted for the fixed navbar */\r\n    position: fixed;\r\n    left: 10rem;\r\n   " +
                    " z-index: 1000;\r\n}\r\n\r\n/* Media Queries */\r\n@media (max-width: 768px) {\r\n        " +
                    "#menu-bar {\r\n        left: 0.3rem;\r\n        top: -4.5rem;\r\n        padding: 0;\r\n" +
                    "    }\r\n\r\n    #menu-bar button {\r\n        font-size: 1.5rem;\r\n        padding: 10" +
                    "px;\r\n    }\r\n\r\n    .sidebar-open #sidebar {\r\n        width: 60%;\r\n    }\r\n\r\n    .s" +
                    "idebar-open #content {\r\n        margin-left: 60%;\r\n        width: 40%;\r\n    }\r\n " +
                    "   #content {\r\n    padding-top: 10%;\r\n    width: 100%;\r\n    margin-left: 0px;\r\n " +
                    "   padding-left: 2rem;\r\n}\r\n}\r\n\r\n@media (max-width: 576px) {\r\n    #menu-bar butto" +
                    "n {\r\n        font-size: 1.2rem;\r\n        margin-top:10rem;\r\n    }\r\n\r\n    .sideba" +
                    "r-open #sidebar {\r\n        width: 75%;\r\n    }\r\n\r\n    .sidebar-open #content {\r\n " +
                    "       margin-left: 75%;\r\n        width: 25%;\r\n    }\r\n}\r\n\r\n   </style>\r\n    <tit" +
                    "le>MBA notes</title>\r\n</head>\r\n<body>\r\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        120,
                        2924,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.WebTools.BrowserLink.Runtime.WebForms.TraceHelpers, Microsoft.WebTools." +
                    "BrowserLink.Tracing, Version=18.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f1" +
                    "1d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.mba_notes_note_master.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.mba_notes_note_master.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control3() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
        <!-- Header -->
                       <nav class=""navbar navbar-expand-lg d-flex shad align-items-center justify-content-between flex-wrap navbar-light bg-light shadow  bg-body rounded"" style=""position: fixed; top: 0; left: 0; width: 100%; height: 5rem; background-color: #f8f9fa; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); z-index: 1000; padding: 0 1rem;"">
            <!-- Logo Section -->
            <div class=""d-flex align-items-center"" style=""flex: 1; justify-content: center;"">
                <a href=""../../Default.aspx"">
");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3076,
                        547,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control4() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                    <img src=\"logo/logo.png\" alt=\"Logo\"   width=\"150\">\r\n\r\n     " +
                    "           </a>\r\n            </div>\r\n            <!-- Title Section -->\r\n       " +
                    "     <div class=\"d-flex align-items-center justify-content-center\" style=\"flex: " +
                    "1;\">\r\n                <h3 style=\"font-size: 2rem; font-weight: bold; color: #002" +
                    "366; margin: 0;\">MBA NOTES</h3>\r\n            </div>\r\n            <!-- Spacer to " +
                    "balance the right side -->\r\n            <div class=\"d-none d-md-flex align-items" +
                    "-center\" style=\"flex: 1; justify-content: flex-end;\">\r\n                <!-- You " +
                    "can add additional items here if needed -->\r\n            </div>\r\n        </nav>\r" +
                    "\n\r\n        <div class=\"d-flex\">\r\n            <div id=\"sidebar\">\r\n               " +
                    "                          <ul>\r\n    <li>\r\n        <a href=\"#\" onclick=\"toggleSub" +
                    "menu(event, \'first\')\">\r\n            <span class=\"submenu-toggle\">First Sem <i cl" +
                    "ass=\"fas fa-caret-down first\"></i></span>\r\n        </a>\r\n        <div id=\"first-" +
                    "submenu\" class=\"submenu\">\r\n            <ul>\r\n                <li><a href=\"busine" +
                    "ss_accounting_and_finance.aspx\">BA & F</a></li>\r\n                <li><a href=\"bu" +
                    "siness_economics.aspx\">B Economics</a></li>\r\n                <li><a href=\"human_" +
                    "resource_management.aspx\">HR Mgmt</a></li>\r\n                <li><a href=\"manager" +
                    "ial_communication.aspx\">Managerial Comm</a></li>\r\n                <li><a href=\"b" +
                    "usiness_environment_analysis.aspx\">B Env Analysis</a></li>\r\n            </ul>\r\n " +
                    "       </div>\r\n    </li>\r\n    <li>\r\n        <a href=\"#\" onclick=\"toggleSubmenu(e" +
                    "vent, \'second\')\">\r\n            <span class=\"submenu-toggle\">Second Sem <i class=" +
                    "\"fas fa-caret-down second\"></i></span>\r\n        </a>\r\n        <div id=\"second-su" +
                    "bmenu\" class=\"submenu\">\r\n            <ul>\r\n                <li><a href=\"business" +
                    "_research_methodology.aspx\">BE Methodology</a></li>\r\n                <li><a href" +
                    "=\"operation_management.aspx\">Operational Mgmt</a></li>\r\n                <li><a h" +
                    "ref=\"marketing_management.aspx\">Marketing Mgmt</a></li>\r\n                <li><a " +
                    "href=\"organizational_behaviour.aspx\">Organizational Beha</a></li>\r\n             " +
                    "   <li><a href=\"consumer_behaviour.aspx\">Consumer Beha</a></li>\r\n            </u" +
                    "l>\r\n        </div>\r\n    </li>\r\n    <li>\r\n        <a href=\"#\" onclick=\"toggleSubm" +
                    "enu(event, \'third\')\">\r\n            <span class=\"submenu-toggle\">Third Sem <i cla" +
                    "ss=\"fas fa-caret-down third\"></i></span>\r\n        </a>\r\n        <div id=\"third-s" +
                    "ubmenu\" class=\"submenu\">\r\n            <ul>\r\n                <li><a href=\"strateg" +
                    "ic_management.aspx\">Strategic Mgmt</a></li>\r\n                <li><a href=\"retail" +
                    "_management.aspx\">Retail Mgmt</a></li>\r\n                <li><a href=\"financial_m" +
                    "anagement.aspx\">Financial Mgmt</a></li>\r\n                <li><a href=\"entreprene" +
                    "urship_management.aspx\">Entrepreneur Mgmt</a></li>\r\n                <li><a href=" +
                    "\"sales_and_promotions_management.aspx\">S & P Mgmt</a></li>\r\n                <li>" +
                    "<a href=\"international_business.aspx\">Intl Business</a></li>\r\n                <l" +
                    "i><a href=\"internship_project_industry_based.aspx\">IPIB</a></li>\r\n            </" +
                    "ul>\r\n        </div>\r\n    </li>\r\n    <li>\r\n        <a href=\"#\" onclick=\"toggleSub" +
                    "menu(event, \'fourth\')\">\r\n            <span class=\"submenu-toggle\">Fourth Sem <i " +
                    "class=\"fas fa-caret-down fourth\"></i></span>\r\n        </a>\r\n        <div id=\"fou" +
                    "rth-submenu\" class=\"submenu\">\r\n            <ul>\r\n                <li><a href=\"ba" +
                    "nking_and_insurance.aspx\">Banking & Insurance</a></li>\r\n                <li><a h" +
                    "ref=\"customer_relationship_management.aspx\">CRM</a></li>\r\n                <li><a" +
                    " href=\"conflict_management_and_negotiation_skills.aspx\">CM & NS</a></li>\r\n      " +
                    "          <li><a href=\"management_of_data.aspx\">Mgmt OF Data</a></li>\r\n         " +
                    "       <li><a href=\"business_ethics.aspx\">B Ethics</a></li>\r\n                <li" +
                    "><a href=\"graduate_research_project.aspx\">GRP</a></li>\r\n            </ul>\r\n     " +
                    "   </div>\r\n    </li>\r\n</ul>\r\n            </div>\r\n\r\n            <!-- Menu Bar -->" +
                    "\r\n            <div id=\"menu-bar\" class=\"top:2rem; \">\r\n                <button ty" +
                    "pe=\"button\" onclick=\"toggleSidebar()\" class=\"btn \" style=\"background:none;\">\r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3762,
                        4079,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control5() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
                    <i class=""fa fa-arrow-right"" aria-hidden=""true"" style=""color:black;"" id=""icon""></i>

                </button>
            </div>

            <!-- Content Area -->
              <div id=""content"" style=""padding-top:4%; width: 90%;margin-left:5%;"" >
      ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        7935,
                        285,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control6() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n      ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        8284,
                        8,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ContentPlaceHolder @__BuildControlContentPlaceHolder1() {
            global::System.Web.UI.WebControls.ContentPlaceHolder @__ctrl;
            
            #line 246 "D:\Learningportal\Learning-System\Mba_Notes\note.Master"
            @__ctrl = new global::System.Web.UI.WebControls.ContentPlaceHolder();
            
            #line default
            #line hidden
            this.ContentPlaceHolder1 = @__ctrl;
            
            #line 246 "D:\Learningportal\Learning-System\Mba_Notes\note.Master"
            @__ctrl.ID = "ContentPlaceHolder1";
            
            #line default
            #line hidden
            if ((this.ContentTemplates != null)) {
                this.@__Template_ContentPlaceHolder1 = ((System.Web.UI.ITemplate)(this.ContentTemplates["ContentPlaceHolder1"]));
            }
            if ((this.@__Template_ContentPlaceHolder1 != null)) {
                this.InstantiateInContentPlaceHolder(@__ctrl, this.@__Template_ContentPlaceHolder1);
            }
            else {
                global::System.Web.UI.LiteralControl @__ctrl1;
                
                #line 246 "D:\Learningportal\Learning-System\Mba_Notes\note.Master"
                @__ctrl1 = this.@__BuildControl__control6();
                
                #line default
                #line hidden
                System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
                
                #line 246 "D:\Learningportal\Learning-System\Mba_Notes\note.Master"
                @__parser.AddParsedSubObject(@__ctrl1);
                
                #line default
                #line hidden
            }
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        8220,
                        97,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control7() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n  </div>\r\n        </div>\r\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        8317,
                        32,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControlform2() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            
            #line 149 "D:\Learningportal\Learning-System\Mba_Notes\note.Master"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
            
            #line default
            #line hidden
            this.form2 = @__ctrl;
            
            #line 149 "D:\Learningportal\Learning-System\Mba_Notes\note.Master"
            @__ctrl.ID = "form2";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 149 "D:\Learningportal\Learning-System\Mba_Notes\note.Master"
            @__ctrl1 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 149 "D:\Learningportal\Learning-System\Mba_Notes\note.Master"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl2;
            
            #line 149 "D:\Learningportal\Learning-System\Mba_Notes\note.Master"
            @__ctrl2 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            
            #line 149 "D:\Learningportal\Learning-System\Mba_Notes\note.Master"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 149 "D:\Learningportal\Learning-System\Mba_Notes\note.Master"
            @__ctrl3 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 149 "D:\Learningportal\Learning-System\Mba_Notes\note.Master"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ContentPlaceHolder @__ctrl4;
            
            #line 149 "D:\Learningportal\Learning-System\Mba_Notes\note.Master"
            @__ctrl4 = this.@__BuildControlContentPlaceHolder1();
            
            #line default
            #line hidden
            
            #line 149 "D:\Learningportal\Learning-System\Mba_Notes\note.Master"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 149 "D:\Learningportal\Learning-System\Mba_Notes\note.Master"
            @__ctrl5 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            
            #line 149 "D:\Learningportal\Learning-System\Mba_Notes\note.Master"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3044,
                        5312,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control8() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n\r\n    <script>\r\n        function toggleSidebar() {\r\n            var sidebar =" +
                    " document.getElementById(\'sidebar\');\r\n            var content = document.getElem" +
                    "entById(\'content\');\r\n            var menuBar = document.getElementById(\'menu-bar" +
                    "\');\r\n            var sidebarOpen = document.body.classList.toggle(\'sidebar-open\'" +
                    ");\r\n            var icon = document.getElementById(\'icon\');\r\n\r\n            if (s" +
                    "idebarOpen) {\r\n                sidebar.style.width = \'20%\'; // Adjust to desired" +
                    " width\r\n\r\n                content.style.marginLeft = \'20%\'; // Adjust to match s" +
                    "idebar width\r\n                content.style.width = \'80%\'; // Adjust content wid" +
                    "th accordingly\r\n                menuBar.style.left = \'20%\'; // Align menu bar wi" +
                    "th sidebar\r\n                menuBar.style.paddingTop = \'-0.7rem\'; // Adjust padd" +
                    "ing\r\n                icon.style.transform = \'rotate(180deg)\'; // Rotate icon whe" +
                    "n sidebar is open\r\n            } else {\r\n                sidebar.style.width = \'" +
                    "0\'; // Collapse sidebar\r\n                content.style.marginLeft = \'0\'; // Adju" +
                    "st content margin\r\n                content.style.width = \'100%\'; // Full width f" +
                    "or content\r\n                menuBar.style.left = \'3%\'; // Align menu bar when si" +
                    "debar is closed\r\n                icon.style.transform = \'rotate(0deg)\'; // Reset" +
                    " icon rotation\r\n            }\r\n        }\r\n\r\n\r\n        function toggleSubmenu(eve" +
                    "nt, submenuId) {\r\n            event.preventDefault();\r\n\r\n            // Get subm" +
                    "enu and icon elements\r\n            var submenu = document.getElementById(submenu" +
                    "Id + \'-submenu\');\r\n            var icon = document.querySelector(\'.\' + submenuId" +
                    ");\r\n\r\n            // Ensure sidebar is open\r\n            document.body.classList" +
                    ".add(\'sidebar-open\');\r\n\r\n            // Toggle the submenu visibility\r\n         " +
                    "   if (submenu.style.display === \'block\') {\r\n                submenu.style.displ" +
                    "ay = \'none\'; // Hide submenu\r\n                icon.classList.remove(\'rotate\'); /" +
                    "/ Reset icon rotation\r\n            } else {\r\n                submenu.style.displ" +
                    "ay = \'block\'; // Show submenu\r\n                icon.classList.add(\'rotate\'); // " +
                    "Rotate icon\r\n            }\r\n        }\r\n\r\n        window.onload = function () {\r\n" +
                    "            var sidebar = document.getElementById(\'sidebar\');\r\n            var c" +
                    "ontent = document.getElementById(\'content\');\r\n            var menuBar = document" +
                    ".getElementById(\'menu-bar\');\r\n            var icon = document.getElementById(\'ic" +
                    "on\');\r\n\r\n            // Open sidebar by default\r\n            document.body.class" +
                    "List.add(\'sidebar-open\');\r\n            sidebar.style.width = \'20%\'; // Adjust to" +
                    " desired width\r\n            content.style.marginLeft = \'20%\'; // Adjust to match" +
                    " sidebar width\r\n            content.style.width = \'80%\'; // Adjust content width" +
                    " accordingly\r\n            menuBar.style.left = \'20%\'; // Align menu bar with sid" +
                    "ebar\r\n            menuBar.style.paddingTop = \'-0.7rem\'; // Adjust padding\r\n     " +
                    "       icon.style.transform = \'rotate(180deg)\'; // Rotate icon when sidebar is o" +
                    "pen\r\n        }\r\n\r\n\r\n    </script>\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        8356,
                        3034,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(mba_notes_note_master @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 1 "D:\Learningportal\Learning-System\Mba_Notes\note.Master"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "D:\Learningportal\Learning-System\Mba_Notes\note.Master"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl2;
            
            #line 1 "D:\Learningportal\Learning-System\Mba_Notes\note.Master"
            @__ctrl2 = this.@__BuildControlform2();
            
            #line default
            #line hidden
            
            #line 1 "D:\Learningportal\Learning-System\Mba_Notes\note.Master"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 1 "D:\Learningportal\Learning-System\Mba_Notes\note.Master"
            @__ctrl3 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 1 "D:\Learningportal\Learning-System\Mba_Notes\note.Master"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.@__BuildControlTree(this);
        }
    }
}
