#pragma checksum "D:\Learningportal\Learning-System\Bhm_Notes\note.Master" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "5CBED7A06D5D674CA98D2A355D9B6AE4CA3FDD8F"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    
    #line 330 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 337 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 328 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 326 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 332 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 321 "D:\Learningportal\Learning-System\Bhm_Notes\note.Master"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 343 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 321 "D:\Learningportal\Learning-System\Bhm_Notes\note.Master"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 342 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    #line 333 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 329 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 331 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 338 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 334 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 325 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 321 "D:\Learningportal\Learning-System\Bhm_Notes\note.Master"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 321 "D:\Learningportal\Learning-System\Bhm_Notes\note.Master"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 327 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 336 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 321 "D:\Learningportal\Learning-System\Bhm_Notes\note.Master"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class bhm_notes_note_master : global::Learning_System.Bhm_Notes.note {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.bhm_notes_note_master.@__PageInspector_LoadHelper("SetTraceData");
        
        private System.Web.UI.ITemplate @__Template_ContentPlaceHolder1;
        
        private static bool @__initialized;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bhm_notes_note_master() {
            ((global::Learning_System.Bhm_Notes.note)(this)).AppRelativeVirtualPath = "~/Bhm_Notes/note.Master";
            if ((global::ASP.bhm_notes_note_master.@__initialized == false)) {
                global::ASP.bhm_notes_note_master.@__initialized = true;
            }
            this.ContentPlaceHolders.Add("contentplaceholder1");
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(this.Context.ApplicationInstance));
            }
        }
        
        [TemplateContainer(typeof(Learning_System.Bhm_Notes.note))]
        [TemplateInstanceAttribute(System.Web.UI.TemplateInstance.Single)]
        public virtual System.Web.UI.ITemplate Template_ContentPlaceHolder1 {
            get {
                return this.@__Template_ContentPlaceHolder1;
            }
            set {
                this.@__Template_ContentPlaceHolder1 = value;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n\r\n\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta charset=\"utf-8\">\r\n    <meta na" +
                    "me=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n    <link rel=\"sty" +
                    "lesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min" +
                    ".css\">\r\n    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jque" +
                    "ry.min.js\"></script>\r\n    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/po" +
                    "pper.js/1.14.7/umd/popper.min.js\"></script>\r\n    <script src=\"https://maxcdn.boo" +
                    "tstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"></script>\r\n    <link rel=\"sty" +
                    "lesheet\" href=\"https://pro.fontawesome.com/releases/v5.10.0/css/all.css\" />\r\n   " +
                    " <link href=\"mcsdash.css\" rel=\"stylesheet\" />\r\n    <style>\r\n        /* Sidebar S" +
                    "tyles */\r\n        #sidebar {\r\n            position: fixed;\r\n            top: 5re" +
                    "m;\r\n            left: 0;\r\n            width: 0;\r\n            height: calc(100vh " +
                    "- 5rem);\r\n            background-color: #343a40;\r\n            color: #fff;\r\n    " +
                    "        overflow-x: hidden;\r\n            overflow-y: auto;\r\n            z-index:" +
                    " 999;\r\n            transition: width 0.3s ease;\r\n        }\r\n\r\n        #content {" +
                    "\r\n            margin-top: 5rem; /* Adjusted to account for navbar height */\r\n   " +
                    "         margin-left: 0;\r\n            width: 100%;\r\n            transition: marg" +
                    "in-left 0.3s ease;\r\n        }\r\n\r\n        #sidebar a {\r\n            color: #fff;\r" +
                    "\n            text-decoration: none;\r\n            display: block;\r\n            pa" +
                    "dding: 0.5rem 1rem;\r\n        }\r\n\r\n            #sidebar a:hover {\r\n              " +
                    "  background-color: #495057;\r\n            }\r\n\r\n        #sidebar ul {\r\n          " +
                    "  padding: 0;\r\n            list-style: none;\r\n            margin: 0;\r\n        }\r" +
                    "\n\r\n            #sidebar ul li {\r\n                padding: 0;\r\n            }\r\n\r\n " +
                    "       #sidebar .submenu {\r\n            display: none;\r\n            padding-left" +
                    ": 1rem;\r\n        }\r\n\r\n        /* Open Sidebar Styles */\r\n        .sidebar-open #" +
                    "sidebar {\r\n            width: 30%;\r\n        }\r\n\r\n        .sidebar-open #content " +
                    "{\r\n            margin-left: 30%;\r\n        }\r\n\r\n        .submenu-toggle {\r\n      " +
                    "      display: flex;\r\n            justify-content: space-between;\r\n            a" +
                    "lign-items: center;\r\n            width: 100%;\r\n        }\r\n\r\n        /* Toggle Ic" +
                    "on Styles */\r\n        .fas.fa-caret-down {\r\n            transition: transform 0." +
                    "3s ease;\r\n            font-size: 1rem;\r\n        }\r\n\r\n        .rotate {\r\n        " +
                    "    transform: rotate(180deg);\r\n        }\r\n\r\n        /* Responsive Menu Bar */\r\n" +
                    "        #menu-bar {\r\n            padding-top: 6rem; /* Adjusted for the fixed na" +
                    "vbar */\r\n            position: fixed;\r\n            left: 10rem;\r\n            z-i" +
                    "ndex: 1000;\r\n        }\r\n\r\n        /* Media Queries */\r\n        @media (max-width" +
                    ": 768px) {\r\n            #menu-bar {\r\n                left: 0.3rem;\r\n            " +
                    "    top: -4.5rem;\r\n                padding: 0;\r\n            }\r\n\r\n               " +
                    " #menu-bar button {\r\n                    font-size: 1.5rem;\r\n                   " +
                    " padding: 10px;\r\n                }\r\n\r\n            .sidebar-open #sidebar {\r\n    " +
                    "            width: 60%;\r\n            }\r\n\r\n            .sidebar-open #content {\r\n" +
                    "                margin-left: 60%;\r\n                width: 40%;\r\n            }\r\n\r" +
                    "\n            #content {\r\n                padding-top: 10%;\r\n                widt" +
                    "h: 100%;\r\n                margin-left: 0px;\r\n                padding-left: 2rem;" +
                    "\r\n            }\r\n        }\r\n\r\n        @media (max-width: 576px) {\r\n            #" +
                    "menu-bar button {\r\n                font-size: 1.2rem;\r\n                margin-to" +
                    "p: 10rem;\r\n            }\r\n\r\n            .sidebar-open #sidebar {\r\n              " +
                    "  width: 75%;\r\n            }\r\n\r\n            .sidebar-open #content {\r\n          " +
                    "      margin-left: 75%;\r\n                width: 25%;\r\n            }\r\n        }\r\n" +
                    "    </style>\r\n    <title>BHM notes</title>\r\n</head>\r\n<body>\r\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        120,
                        3826,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.WebTools.BrowserLink.Runtime.WebForms.TraceHelpers, Microsoft.WebTools." +
                    "BrowserLink.Tracing, Version=18.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f1" +
                    "1d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.bhm_notes_note_master.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.bhm_notes_note_master.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control3() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
        <!-- Header -->
                        <nav class=""navbar navbar-expand-lg d-flex shad align-items-center justify-content-between flex-wrap navbar-light bg-light shadow  bg-body rounded"" style=""position: fixed; top: 0; left: 0; width: 100%; height: 5rem; background-color: #f8f9fa; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); z-index: 1000; padding: 0 1rem;"">
            <!-- Logo Section -->
            <div class=""d-flex align-items-center"" style=""flex: 1; justify-content: center;"">
                <a href=""../../Default.aspx"">
");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3978,
                        548,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control4() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                    <img src=\"logo/logo.png\" alt=\"Logo\"   width=\"150\">\r\n\r\n     " +
                    "           </a>\r\n            </div>\r\n            <!-- Title Section -->\r\n       " +
                    "     <div class=\"d-flex align-items-center justify-content-center\" style=\"flex: " +
                    "1;\">\r\n                <h3 style=\"font-size: 2rem; font-weight: bold; color: #002" +
                    "366; margin: 0;\">BHM NOTES</h3>\r\n            </div>\r\n            <!-- Spacer to " +
                    "balance the right side -->\r\n            <div class=\"d-none d-md-flex align-items" +
                    "-center\" style=\"flex: 1; justify-content: flex-end;\">\r\n                <!-- You " +
                    "can add additional items here if needed -->\r\n            </div>\r\n        </nav>\r" +
                    "\n\r\n        <div class=\"d-flex\">\r\n            <div id=\"sidebar\">\r\n               " +
                    " <ul>\r\n\r\n\r\n                    <li>\r\n                        <a href=\"#\" onclick" +
                    "=\"toggleSubmenu(event, \'first\')\">\r\n                            <span class=\"subm" +
                    "enu-toggle\">First Sem <i class=\"fas fa-caret-down first\"></i></span>\r\n          " +
                    "              </a>\r\n                        <div id=\"first-submenu\" class=\"subme" +
                    "nu\">\r\n                            <ul>\r\n                                <li><a h" +
                    "ref=\"introduction_to_hospitality_and_tourism_management.aspx\">IHTM </a></li>\r\n  " +
                    "                              <li><a href=\"housekeeping_operation.aspx\">HO</a></" +
                    "li>\r\n                                <li><a href=\"front_office_operation.aspx\">F" +
                    "OO</a></li>\r\n                                <li><a href=\"food_and_beverage_serv" +
                    "ice_skill.aspx\">FBSS </a></li>\r\n                                <li><a href=\"fun" +
                    "damental_of_computer_in_hotel_concept_and_application.aspx\">FCH</a></li>\r\n      " +
                    "                          <li><a href=\"english_for_academics.aspx\">EA</a></li>\r\n" +
                    "\r\n                            </ul>\r\n                        </div>\r\n           " +
                    "         </li>\r\n\r\n                    <li>\r\n                        <a href=\"#\" " +
                    "onclick=\"toggleSubmenu(event, \'second\')\">\r\n                            <span cla" +
                    "ss=\"submenu-toggle\">Second Sem <i class=\"fas fa-caret-down second\"></i></span>\r\n" +
                    "                        </a>\r\n                        <div id=\"second-submenu\" c" +
                    "lass=\"submenu\">\r\n                            <ul>\r\n                             " +
                    "   <li><a href=\"front_office_management.aspx\">FOM</a></li>\r\n                    " +
                    "            <li><a href=\"housekeeping_management.aspx\">HM</a></li>\r\n            " +
                    "                    <li><a href=\"food_production_operation.aspx\">FPO</a></li>\r\n " +
                    "                               <li><a href=\"food_and_beverage_service_operation." +
                    "aspx\">FBSO</a></li>\r\n                                <li><a href=\"hospitality_en" +
                    "glish.aspx\">Hospitality English</a></li>\r\n                                <li><a" +
                    " href=\"fundamentals_of_management.aspx\">FM</a></li>\r\n\r\n                         " +
                    "   </ul>\r\n                        </div>\r\n                    </li>\r\n           " +
                    "         <li>\r\n                        <a href=\"#\" onclick=\"toggleSubmenu(event," +
                    " \'third\')\">\r\n                            <span class=\"submenu-toggle\">Third Sem " +
                    "<i class=\"fas fa-caret-down third\"></i></span>\r\n                        </a>\r\n  " +
                    "                      <div id=\"third-submenu\" class=\"submenu\">\r\n                " +
                    "            <ul>\r\n                                <li><a href=\"food_science_and_" +
                    "nutrition.aspx\">FSM</a></li>\r\n                                <li><a href=\"accou" +
                    "nting_for_hospitality.aspx\">AH</a></li>\r\n                                <li><a " +
                    "href=\"foodd_production_management.aspx\">FPM</a></li>\r\n                          " +
                    "      <li><a href=\"beverage_study.aspx\">Beverage Study</a></li>\r\n               " +
                    "                 <li><a href=\"hospitality_human_resource_management.aspx\">HHRM</" +
                    "a></li>\r\n                                <li><a href=\"hotel_french.aspx\">Hotel F" +
                    "rench</a></li>\r\n\r\n\r\n                            </ul>\r\n                        <" +
                    "/div>\r\n                    </li>\r\n                    <li>\r\n                    " +
                    "    <a href=\"#\" onclick=\"toggleSubmenu(event, \'fourth\')\">\r\n                     " +
                    "       <span class=\"submenu-toggle\">Fourth Sem <i class=\"fas fa-caret-down fourt" +
                    "h\"></i></span>\r\n                        </a>\r\n                        <div id=\"f" +
                    "ourth-submenu\" class=\"submenu\">\r\n                            <ul>\r\n             " +
                    "                   <li><a href=\"food_and_catering_management.aspx\">FCM</a></li>\r" +
                    "\n                                <li><a href=\"introduction_to_economics.aspx\">IE" +
                    "</a></li>\r\n                                <li><a href=\"organizational_behavior." +
                    "aspx\">OB</a></li>\r\n                                <li><a href=\"entrepreneurship" +
                    ".aspx\">Entrepreneurship</a></li>\r\n                                <li><a href=\"r" +
                    "estaurant_business_operation.aspx\">RBO</a></li>\r\n                               " +
                    " <li><a href=\"hospitality_service_marketing.aspx\">HSM</a></li>\r\n\r\n              " +
                    "              </ul>\r\n                        </div>\r\n                    </li>\r\n" +
                    "\r\n                    <li>\r\n                        <a href=\"#\" onclick=\"toggleS" +
                    "ubmenu(event, \'fifth\')\">\r\n                            <span class=\"submenu-toggl" +
                    "e\">Fifth Sem <i class=\"fas fa-caret-down fifth\"></i></span>\r\n                   " +
                    "     </a>\r\n                        <div id=\"fifth-submenu\" class=\"submenu\">\r\n   " +
                    "                         <ul>\r\n                                <li><a href=\"stat" +
                    "istics.aspx\">Statistics</a></li>\r\n                                <li><a href=\"r" +
                    "evenue_management.aspx\">Revenue Management</a></li>\r\n                           " +
                    "     <li><a href=\"purchasing_and_cost_control.aspx\">PCC</a></li>\r\n              " +
                    "                  <li><a href=\"public_relation.aspx\">Public Relation</a></li>\r\n " +
                    "                               <li><a href=\"hospitality_training_and_development" +
                    ".aspx\">HTD</a></li>\r\n                                <li><a href=\"hospitality_la" +
                    "w.aspx\">Hospitality Law</a></li>\r\n\r\n                            </ul>\r\n         " +
                    "               </div>\r\n                    </li>\r\n\r\n                    <li>\r\n  " +
                    "                      <a href=\"#\" onclick=\"toggleSubmenu(event, \'sixth\')\">\r\n    " +
                    "                        <span class=\"submenu-toggle\">Sixth Sem <i class=\"fas fa-" +
                    "caret-down sixth\"></i></span>\r\n                        </a>\r\n                   " +
                    "     <div id=\"sixth-submenu\" class=\"submenu\">\r\n                            <ul>\r" +
                    "\n                                <li><a href=\"hotel_maintenanace.aspx\">Hotel Mai" +
                    "ntenance</a></li>\r\n                                <li><a href=\"event_management" +
                    ".aspx\">Event_Management</a></li>\r\n                                <li><a href=\"t" +
                    "ourist_behavioral_science.aspx\">TBS</a></li>\r\n                                <l" +
                    "i><a href=\"research_methodology.aspx\">Research Methodology</a></li>\r\n\r\n         " +
                    "                   </ul>\r\n                        </div>\r\n                    </" +
                    "li>\r\n\r\n\r\n\r\n\r\n                    <li>\r\n                        <a href=\"#\" oncli" +
                    "ck=\"toggleSubmenu(event, \'seventh\')\">\r\n                            <span class=\"" +
                    "submenu-toggle\">Seventh Sem <i class=\"fas fa-caret-down seventh\"></i></span>\r\n  " +
                    "                      </a>\r\n                        <div id=\"seventh-submenu\" cl" +
                    "ass=\"submenu\">\r\n                            <ul>\r\n                              " +
                    "  <li><a href=\"industrial_training.aspx\">Industrial Training I</a></li>\r\n\r\n     " +
                    "                       </ul>\r\n                        </div>\r\n                  " +
                    "  </li>\r\n\r\n\r\n                    <li>\r\n                        <a href=\"#\" oncli" +
                    "ck=\"toggleSubmenu(event, \'eight\')\">\r\n                            <span class=\"su" +
                    "bmenu-toggle\">Eighth Sem <i class=\"fas fa-caret-down eight\"></i></span>\r\n       " +
                    "                 </a>\r\n                        <div id=\"eight-submenu\" class=\"su" +
                    "bmenu\">\r\n                            <ul>\r\n                                <li><" +
                    "a href=\"industrial_training2.aspx\">Industrial Training II </a></li>\r\n           " +
                    "                     <li><a href=\"internship_report.aspx\">Internship Report</a><" +
                    "/li>\r\n\r\n\r\n                            </ul>\r\n                        </div>\r\n   " +
                    "                 </li>\r\n\r\n\r\n\r\n\r\n\r\n                </ul>\r\n            </div>\r\n\r\n " +
                    "           <!-- Menu Bar -->\r\n            <div id=\"menu-bar\" class=\"top:2rem; \">" +
                    "\r\n                <button type=\"button\" onclick=\"toggleSidebar()\" class=\"btn \" s" +
                    "tyle=\"background: none;\">\r\n                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4665,
                        8128,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control5() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
                    <i class=""fa fa-arrow-right"" aria-hidden=""true"" style=""color: black;"" id=""icon""></i>

                </button>
            </div>

            <!-- Content Area -->
            <div id=""content"" style=""padding-top: 4%; width: 90%; margin-left: 5%;"">
                ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        12887,
                        296,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control6() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        13247,
                        18,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ContentPlaceHolder @__BuildControlContentPlaceHolder1() {
            global::System.Web.UI.WebControls.ContentPlaceHolder @__ctrl;
            
            #line 321 "D:\Learningportal\Learning-System\Bhm_Notes\note.Master"
            @__ctrl = new global::System.Web.UI.WebControls.ContentPlaceHolder();
            
            #line default
            #line hidden
            this.ContentPlaceHolder1 = @__ctrl;
            
            #line 321 "D:\Learningportal\Learning-System\Bhm_Notes\note.Master"
            @__ctrl.ID = "ContentPlaceHolder1";
            
            #line default
            #line hidden
            if ((this.ContentTemplates != null)) {
                this.@__Template_ContentPlaceHolder1 = ((System.Web.UI.ITemplate)(this.ContentTemplates["ContentPlaceHolder1"]));
            }
            if ((this.@__Template_ContentPlaceHolder1 != null)) {
                this.InstantiateInContentPlaceHolder(@__ctrl, this.@__Template_ContentPlaceHolder1);
            }
            else {
                global::System.Web.UI.LiteralControl @__ctrl1;
                
                #line 321 "D:\Learningportal\Learning-System\Bhm_Notes\note.Master"
                @__ctrl1 = this.@__BuildControl__control6();
                
                #line default
                #line hidden
                System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
                
                #line 321 "D:\Learningportal\Learning-System\Bhm_Notes\note.Master"
                @__parser.AddParsedSubObject(@__ctrl1);
                
                #line default
                #line hidden
            }
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        13183,
                        107,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control7() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n            </div>\r\n        </div>\r\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        13290,
                        42,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControlform2() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            
            #line 148 "D:\Learningportal\Learning-System\Bhm_Notes\note.Master"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
            
            #line default
            #line hidden
            this.form2 = @__ctrl;
            
            #line 148 "D:\Learningportal\Learning-System\Bhm_Notes\note.Master"
            @__ctrl.ID = "form2";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 148 "D:\Learningportal\Learning-System\Bhm_Notes\note.Master"
            @__ctrl1 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 148 "D:\Learningportal\Learning-System\Bhm_Notes\note.Master"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl2;
            
            #line 148 "D:\Learningportal\Learning-System\Bhm_Notes\note.Master"
            @__ctrl2 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            
            #line 148 "D:\Learningportal\Learning-System\Bhm_Notes\note.Master"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 148 "D:\Learningportal\Learning-System\Bhm_Notes\note.Master"
            @__ctrl3 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 148 "D:\Learningportal\Learning-System\Bhm_Notes\note.Master"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ContentPlaceHolder @__ctrl4;
            
            #line 148 "D:\Learningportal\Learning-System\Bhm_Notes\note.Master"
            @__ctrl4 = this.@__BuildControlContentPlaceHolder1();
            
            #line default
            #line hidden
            
            #line 148 "D:\Learningportal\Learning-System\Bhm_Notes\note.Master"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 148 "D:\Learningportal\Learning-System\Bhm_Notes\note.Master"
            @__ctrl5 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            
            #line 148 "D:\Learningportal\Learning-System\Bhm_Notes\note.Master"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3946,
                        9393,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control8() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n\r\n    <script>\r\n        function toggleSidebar() {\r\n            var sidebar =" +
                    " document.getElementById(\'sidebar\');\r\n            var content = document.getElem" +
                    "entById(\'content\');\r\n            var menuBar = document.getElementById(\'menu-bar" +
                    "\');\r\n            var sidebarOpen = document.body.classList.toggle(\'sidebar-open\'" +
                    ");\r\n            var icon = document.getElementById(\'icon\');\r\n\r\n            if (s" +
                    "idebarOpen) {\r\n                sidebar.style.width = \'20%\'; // Adjust to desired" +
                    " width\r\n\r\n                content.style.marginLeft = \'20%\'; // Adjust to match s" +
                    "idebar width\r\n                content.style.width = \'80%\'; // Adjust content wid" +
                    "th accordingly\r\n                menuBar.style.left = \'20%\'; // Align menu bar wi" +
                    "th sidebar\r\n                menuBar.style.paddingTop = \'-0.7rem\'; // Adjust padd" +
                    "ing\r\n                icon.style.transform = \'rotate(180deg)\'; // Rotate icon whe" +
                    "n sidebar is open\r\n            } else {\r\n                sidebar.style.width = \'" +
                    "0\'; // Collapse sidebar\r\n                content.style.marginLeft = \'0\'; // Adju" +
                    "st content margin\r\n                content.style.width = \'100%\'; // Full width f" +
                    "or content\r\n                menuBar.style.left = \'3%\'; // Align menu bar when si" +
                    "debar is closed\r\n                icon.style.transform = \'rotate(0deg)\'; // Reset" +
                    " icon rotation\r\n            }\r\n        }\r\n\r\n\r\n        function toggleSubmenu(eve" +
                    "nt, submenuId) {\r\n            event.preventDefault();\r\n\r\n            // Get subm" +
                    "enu and icon elements\r\n            var submenu = document.getElementById(submenu" +
                    "Id + \'-submenu\');\r\n            var icon = document.querySelector(\'.\' + submenuId" +
                    ");\r\n\r\n            // Ensure sidebar is open\r\n            document.body.classList" +
                    ".add(\'sidebar-open\');\r\n\r\n            // Toggle the submenu visibility\r\n         " +
                    "   if (submenu.style.display === \'block\') {\r\n                submenu.style.displ" +
                    "ay = \'none\'; // Hide submenu\r\n                icon.classList.remove(\'rotate\'); /" +
                    "/ Reset icon rotation\r\n            } else {\r\n                submenu.style.displ" +
                    "ay = \'block\'; // Show submenu\r\n                icon.classList.add(\'rotate\'); // " +
                    "Rotate icon\r\n            }\r\n        }\r\n\r\n\r\n        window.onload = function () {" +
                    "\r\n            var sidebar = document.getElementById(\'sidebar\');\r\n            var" +
                    " content = document.getElementById(\'content\');\r\n            var menuBar = docume" +
                    "nt.getElementById(\'menu-bar\');\r\n            var icon = document.getElementById(\'" +
                    "icon\');\r\n\r\n            // Open sidebar by default\r\n            document.body.cla" +
                    "ssList.add(\'sidebar-open\');\r\n            sidebar.style.width = \'20%\'; // Adjust " +
                    "to desired width\r\n            content.style.marginLeft = \'20%\'; // Adjust to mat" +
                    "ch sidebar width\r\n            content.style.width = \'80%\'; // Adjust content wid" +
                    "th accordingly\r\n            menuBar.style.left = \'20%\'; // Align menu bar with s" +
                    "idebar\r\n            menuBar.style.paddingTop = \'-0.7rem\'; // Adjust padding\r\n   " +
                    "         icon.style.transform = \'rotate(180deg)\'; // Rotate icon when sidebar is" +
                    " open\r\n        }\r\n\r\n    </script>\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n\r\n\r\n\r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        13339,
                        3026,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(bhm_notes_note_master @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 1 "D:\Learningportal\Learning-System\Bhm_Notes\note.Master"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "D:\Learningportal\Learning-System\Bhm_Notes\note.Master"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl2;
            
            #line 1 "D:\Learningportal\Learning-System\Bhm_Notes\note.Master"
            @__ctrl2 = this.@__BuildControlform2();
            
            #line default
            #line hidden
            
            #line 1 "D:\Learningportal\Learning-System\Bhm_Notes\note.Master"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 1 "D:\Learningportal\Learning-System\Bhm_Notes\note.Master"
            @__ctrl3 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 1 "D:\Learningportal\Learning-System\Bhm_Notes\note.Master"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.@__BuildControlTree(this);
        }
    }
}
