#pragma checksum "D:\Learningportal\Learning-System\AIBlog.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "FE0F16D5F3547247C68929E338A818D0842F9A61"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    
    #line 3 "D:\Learningportal\Learning-System\AIBlog.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 325 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 331 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 338 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 3 "D:\Learningportal\Learning-System\AIBlog.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 326 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 330 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 1 "D:\Learningportal\Learning-System\AIBlog.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 336 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 329 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 333 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 3 "D:\Learningportal\Learning-System\AIBlog.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 334 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 3 "D:\Learningportal\Learning-System\AIBlog.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 328 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 337 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 3 "D:\Learningportal\Learning-System\AIBlog.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 332 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 327 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 343 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 342 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class aiblog_aspx : global::Learning_System.WebForm3, System.Web.SessionState.IRequiresSessionState, System.Web.IHttpHandler {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.aiblog_aspx.@__PageInspector_LoadHelper("SetTraceData");
        
        private static bool @__initialized;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public aiblog_aspx() {
            string[] dependencies;
            ((global::Learning_System.WebForm3)(this)).AppRelativeVirtualPath = "~/AIBlog.aspx";
            if ((global::ASP.aiblog_aspx.@__initialized == false)) {
                dependencies = new string[2];
                dependencies[0] = "~/AIBlog.aspx";
                dependencies[1] = "~/learning.Master";
                global::ASP.aiblog_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.aiblog_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(this.Context.ApplicationInstance));
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n    <div class=\"container my-5\">\r\n        <div class=\"text-center rounded-4 py-" +
                    "4\">\r\n            <img src=\"slide/facedetection.png\" class=\"img-fluid w-100\" styl" +
                    "e=\"height: 350px; border-radius: 10px; object-fit: contain\" />\r\n        </div>\r\n" +
                    "        <h1 class=\"text-dark\">Building a Real-Time Face Recognition and Attendan" +
                    "ce System Using OpenCV, Face Recognition, and Google Text-to-Speech</h1>\r\n      " +
                    "  <p>In today\'s world, face recognition technology has rapidly evolved, making i" +
                    "ts way into various applications from security systems to mobile devices. One in" +
                    "teresting use case is in automated attendance systems, where the time-consuming " +
                    "process of manually taking attendance can be eliminated with the power of facial" +
                    " recognition. In this blog post, we will walk through the steps of building a re" +
                    "al-time face recognition and attendance system using OpenCV, the face_recognitio" +
                    "n library, and Google Text-to-Speech (gTTS).</p>\r\n\r\n        <h2 class=\"text-dark" +
                    "\">Project Overview</h2>\r\n        <p>The goal of this project is to create a syst" +
                    "em that can recognize faces in real-time using a webcam, identify the person, an" +
                    "d then mark their attendance by writing their name and the time they were recogn" +
                    "ized to a CSV file. Additionally, the system will use text-to-speech technology " +
                    "to announce the name of the recognized person.</p>\r\n\r\n        <h2 class=\"text-da" +
                    "rk\">Prerequisites</h2>\r\n        <p>Before we dive into the code, let\'s make sure" +
                    " you have the necessary tools and libraries installed:</p>\r\n        <ul>\r\n      " +
                    "      <li>Python</li>\r\n            <li>OpenCV</li>\r\n            <li>face_recogni" +
                    "tion</li>\r\n            <li>gTTS</li>\r\n        </ul>\r\n        <p>You can install " +
                    "these libraries using pip:</p>\r\n        <div class=\"code-container\">\r\n          " +
                    "  <div class=\"d-flex justify-content-end mb-2\">\r\n                <button class=\"" +
                    "copy-btn text-light bg-primary\" onclick=\"copyToClipboard(\'installCommand\')\">Copy" +
                    " Code</button>\r\n            </div>\r\n            <pre><code id=\"installCommand\">p" +
                    "ip install opencv-python face-recognition gtts</code></pre>\r\n        </div>\r\n\r\n " +
                    "       <h2 class=\"text-dark\">Step 1: Preparing the Training Images</h2>\r\n       " +
                    " <p>The first step is to gather a set of training images. These images should co" +
                    "ntain the faces of the individuals you want to recognize. Store these images in " +
                    "a folder named <strong>training images</strong>. Each image file should be named" +
                    " after the person it contains, as this name will be used to identify the person " +
                    "during recognition.</p>\r\n\r\n        <div class=\"code-container\">\r\n            <di" +
                    "v class=\"d-flex justify-content-end mb-2\">\r\n                <button class=\"copy-" +
                    "btn text-light bg-primary\" onclick=\"copyToClipboard(\'trainingImagesCode\')\">Copy " +
                    "Code</button>\r\n            </div>\r\n            <pre><code id=\"trainingImagesCode" +
                    "\">import cv2\r\nimport numpy as np\r\nimport face_recognition\r\nimport os\r\nfrom datet" +
                    "ime import datetime\r\nfrom gtts import gTTS\r\nimport time</code></pre>\r\n        </" +
                    "div>\r\n\r\n        <h2 class=\"text-dark\">Step 2: Loading and Encoding the Images</h" +
                    "2>\r\n        <p>The next step is to load the training images and convert them int" +
                    "o a format that the face_recognition library can use. This involves reading each" +
                    " image, converting it from BGR (the default format used by OpenCV) to RGB, and t" +
                    "hen generating a face encoding for each image.</p>\r\n\r\n        <div class=\"code-c" +
                    "ontainer\">\r\n            <div class=\"d-flex justify-content-end mb-2\">\r\n         " +
                    "       <button class=\"copy-btn text-light bg-primary\" onclick=\"copyToClipboard(\'" +
                    "encodingCode\')\">Copy Code</button>\r\n            </div>\r\n            <pre><code i" +
                    "d=\"encodingCode\">path = \'training images\'  # Path to the images folder\r\nimages =" +
                    " []\r\nclassNames = []\r\nmyList = os.listdir(path)\r\n\r\nfor cl in myList:\r\n    curImg" +
                    " = cv2.imread(f\'{path}/{cl}\')\r\n    images.append(curImg)\r\n    classNames.append(" +
                    "os.path.splitext(cl)[0])\r\n\r\ndef findEncodings(images):\r\n    encodeList = []\r\n   " +
                    " for img in images:\r\n        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)\r\n       " +
                    " encode = face_recognition.face_encodings(img)[0]\r\n        encodeList.append(enc" +
                    "ode)\r\n    return encodeList\r\n\r\nencodeListKnown = findEncodings(images)</code></p" +
                    "re>\r\n        </div>\r\n\r\n        <h2 class=\"text-dark\">Step 3: Marking Attendance<" +
                    "/h2>\r\n        <p>Once a face is recognized, we need to record the attendance by " +
                    "writing the person’s name and the current time to a CSV file. This is done by ch" +
                    "ecking if the person has already been marked for the day, and if not, appending " +
                    "their information to the file. We also use the gTTS library to announce the name" +
                    " of the person as they are recognized.</p>\r\n\r\n        <div class=\"code-container" +
                    "\">\r\n            <div class=\"d-flex justify-content-end mb-2\">\r\n                <" +
                    "button class=\"copy-btn text-light bg-primary\" onclick=\"copyToClipboard(\'attendan" +
                    "ceCode\')\">Copy Code</button>\r\n            </div>\r\n            <pre><code id=\"att" +
                    "endanceCode\">def markAttendance(name):\r\n    with open(\'Attendance.csv\',\'r+\') as " +
                    "f:\r\n        myDataList = f.readlines()\r\n        nameList = []\r\n        for line " +
                    "in myDataList:\r\n            entry = line.split(\',\')\r\n            nameList.append" +
                    "(entry[0])\r\n            \r\n        if name not in nameList:\r\n            now = da" +
                    "tetime.now()\r\n            dtString1 = now.strftime(\'%H:%M:%S\')\r\n            dtSt" +
                    "ring2 = now.strftime(\'%A\')\r\n            dtString3 = now.strftime(\'%d:%m:%Y\')\r\n  " +
                    "          f.writelines(f\'\\n{name},{dtString1},{dtString2},{dtString3}\')\r\n\r\n     " +
                    "       # Speak the recognized name\r\n            language = \'en\'\r\n            out" +
                    "put = gTTS(text=f\'hello {name}\', lang=language, slow=False)\r\n            output." +
                    "save(\"output.mp3\")\r\n            os.system(\"start output.mp3\")\r\n            time." +
                    "sleep(3)\r\n            os.remove(\'output.mp3\')</code></pre>\r\n        </div>\r\n\r\n  " +
                    "      <h2 class=\"text-dark\">Step 4: Capturing and Processing Video</h2>\r\n       " +
                    " <p>The main loop of the program captures frames from the webcam, processes them" +
                    " to detect faces, and then compares these detected faces with the known encoding" +
                    "s. If a match is found, the person\'s name is displayed on the video feed, and th" +
                    "eir attendance is marked.</p>\r\n\r\n        <div class=\"code-container\">\r\n         " +
                    "   <div class=\"d-flex justify-content-end mb-2\">\r\n                <button class=" +
                    "\"copy-btn text-light bg-primary\" onclick=\"copyToClipboard(\'videoCode\')\">Copy Cod" +
                    "e</button>\r\n            </div>\r\n            <pre><code id=\"videoCode\">cap = cv2." +
                    "VideoCapture(0)\r\n\r\nwhile True:\r\n    success, img = cap.read()\r\n    imgS = cv2.re" +
                    "size(img, (0, 0), None, 0.25, 0.25)\r\n    imgS = cv2.cvtColor(imgS, cv2.COLOR_BGR" +
                    "2RGB)\r\n    \r\n    facesCurFrame = face_recognition.face_locations(imgS)\r\n    enco" +
                    "desCurFrame = face_recognition.face_encodings(imgS, facesCurFrame)\r\n    \r\n    fo" +
                    "r encodeFace, faceLoc in zip(encodesCurFrame, facesCurFrame):\r\n        matches =" +
                    " face_recognition.compare_faces(encodeListKnown, encodeFace)\r\n        faceDis = " +
                    "face_recognition.face_distance(encodeListKnown, encodeFace)\r\n        matchIndex " +
                    "= np.argmin(faceDis)\r\n        \r\n        if matches[matchIndex]:\r\n            nam" +
                    "e = classNames[matchIndex]\r\n            y1, x2, y2, x1 = faceLoc\r\n            y1" +
                    ", x2, y2, x1 = y1*4, x2*4, y2*4, x1*4\r\n            cv2.rectangle(img, (x1, y1), " +
                    "(x2, y2), (0, 255, 0), 2)\r\n            cv2.rectangle(img, (x1, y2-35), (x2, y2)," +
                    " (0, 255, 0), cv2.FILLED)\r\n            cv2.putText(img, name, (x1+6, y2-6), cv2." +
                    "FONT_HERSHEY_COMPLEX, 1, (255, 255, 255), 2)\r\n            markAttendance(name)\r\n" +
                    "    \r\n    cv2.imshow(\'my video\', img)\r\n    if cv2.waitKey(13) & 0xFF == ord(\'q\')" +
                    ":\r\n        cv2.destroyAllWindows()\r\n        break</code></pre>\r\n        </div>\r\n" +
                    "\r\n        <h2 class=\"text-dark\">Step 5: Running the Program</h2>\r\n        <p>Fin" +
                    "ally, you can run the program and test it with different faces. Make sure to hav" +
                    "e your webcam set up and properly configured. When you run the script, it will s" +
                    "tart capturing video and recognizing faces in real-time. Ensure you have the tra" +
                    "ining images folder with the correct images before running the program.</p>\r\n\r\n " +
                    "       <div class=\"code-container\">\r\n            <div class=\"d-flex justify-cont" +
                    "ent-end mb-2\">\r\n                <button class=\"copy-btn text-light bg-primary\" o" +
                    "nclick=\"copyToClipboard(\'runCode\')\">Copy Code</button>\r\n            </div>\r\n    " +
                    "        <pre><code id=\"runCode\">python face_recognition_attendance.py</code></pr" +
                    "e>\r\n        </div>\r\n\r\n        <h2 class=\"text-dark\">Conclusion</h2>\r\n        <p>" +
                    "This real-time face recognition and attendance system is a great way to explore " +
                    "computer vision and machine learning technologies. By integrating OpenCV, face_r" +
                    "ecognition, and gTTS, you can build a practical application that demonstrates th" +
                    "e power of these technologies. Experiment with the code and adapt it to your own" +
                    " needs!</p>\r\n\r\n\r\n        <p class=\"my-5\">\r\n            <a href=\"https://github.c" +
                    "om/subashsigdel/Automatic-attendence_project.git\" target=\"_blank\" class=\"btn btn" +
                    "-primary\">\r\n                <i class=\"fab fa-github\"></i>View on GitHub\r\n       " +
                    "     </a>\r\n        </p>\r\n        <div class=\"d-flex justify-content-end\">\r\n     " +
                    "       <a href=\"Default.aspx\" class=\"btn btn-primary text-light\">Back to home</a" +
                    ">\r\n        </div>\r\n    </div>\r\n    <style>\r\n        /* General styling for the c" +
                    "ode containers */\r\n        .code-container {\r\n            border: 1px solid #ddd" +
                    ";\r\n            border-radius: 0.25rem;\r\n            background-color: #f8f9fa;\r\n" +
                    "            padding: 1rem;\r\n            margin-bottom: 1.5rem;\r\n            posi" +
                    "tion: relative;\r\n        }\r\n\r\n        /* Button to copy code */\r\n        .copy-b" +
                    "tn {\r\n            border: none;\r\n            border-radius: 0.25rem;\r\n          " +
                    "  padding: 0.5rem 1rem;\r\n            cursor: pointer;\r\n            font-size: 0." +
                    "875rem;\r\n            position: absolute;\r\n            right: 1rem;\r\n            " +
                    "top: 1rem;\r\n        }\r\n\r\n        /* Adjust the appearance of the code block */\r\n" +
                    "        pre {\r\n            margin: 0;\r\n            overflow-x: auto;\r\n        }\r" +
                    "\n\r\n        /* Style for code elements */\r\n        code {\r\n            display: b" +
                    "lock;\r\n        }\r\n    </style>\r\n");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        293,
                        10033,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.WebTools.BrowserLink.Runtime.WebForms.TraceHelpers, Microsoft.WebTools." +
                    "BrowserLink.Tracing, Version=18.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f1" +
                    "1d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.aiblog_aspx.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.aiblog_aspx.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent1(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 3 "D:\Learningportal\Learning-System\AIBlog.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 3 "D:\Learningportal\Learning-System\AIBlog.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(aiblog_aspx @__ctrl) {
            
            #line 1 "D:\Learningportal\Learning-System\AIBlog.aspx"
            @__ctrl.Title = "Real-Time Face Recognition and Attendance System";
            
            #line default
            #line hidden
            
            #line 1 "D:\Learningportal\Learning-System\AIBlog.aspx"
            @__ctrl.MasterPageFile = "~/learning.Master";
            
            #line default
            #line hidden
            
            #line 1 "D:\Learningportal\Learning-System\AIBlog.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 3 "D:\Learningportal\Learning-System\AIBlog.aspx"
            this.AddContentTemplate("ContentPlaceHolder1", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent1)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "D:\Learningportal\Learning-System\AIBlog.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.aiblog_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -1005266328;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
