//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.7.2")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_cxrledid {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_cxrledid() {
        }
        
        static object Create_ASP_bit_notes_cryptography_aspx() {
            return new ASP.bit_notes_cryptography_aspx();
        }
        
        static object Create_ASP_bit_notes_software_project_management_aspx() {
            return new ASP.bit_notes_software_project_management_aspx();
        }
        
        static object Create_ASP_bit_notes_java_programming_4_aspx() {
            return new ASP.bit_notes_java_programming_4_aspx();
        }
        
        static object Create_ASP_bit_notes_managementinformationsystem_aspx() {
            return new ASP.bit_notes_managementinformationsystem_aspx();
        }
        
        static object Create_ASP_bit_notes_industrial_training_aspx() {
            return new ASP.bit_notes_industrial_training_aspx();
        }
        
        static object Create_ASP_bit_notes_operating_system_aspx() {
            return new ASP.bit_notes_operating_system_aspx();
        }
        
        static object Create_ASP_bit_notes_java_programming_aspx() {
            return new ASP.bit_notes_java_programming_aspx();
        }
        
        static object Create_ASP_bit_notes_compiler_and_design_constructions_aspx() {
            return new ASP.bit_notes_compiler_and_design_constructions_aspx();
        }
        
        static object Create_ASP_bit_notes_advance_computer_network_aspx() {
            return new ASP.bit_notes_advance_computer_network_aspx();
        }
        
        static object Create_ASP_bit_notes_e_commerce_aspx() {
            return new ASP.bit_notes_e_commerce_aspx();
        }
        
        static object Create_ASP_bit_notes_ai_aspx() {
            return new ASP.bit_notes_ai_aspx();
        }
        
        static object Create_ASP_bit_notes_industrymanagement_aspx() {
            return new ASP.bit_notes_industrymanagement_aspx();
        }
        
        static object Create_ASP_bit_notes_cloud_computing_aspx() {
            return new ASP.bit_notes_cloud_computing_aspx();
        }
        
        static object Create_ASP_bit_notes_wml_and_wap_programming_aspx() {
            return new ASP.bit_notes_wml_and_wap_programming_aspx();
        }
        
        static object Create_ASP_bit_notes_systemsoftware_admin_aspx() {
            return new ASP.bit_notes_systemsoftware_admin_aspx();
        }
        
        static object Create_ASP_bit_notes_database_management_system_aspx() {
            return new ASP.bit_notes_database_management_system_aspx();
        }
    }
}
