#pragma checksum "D:\Learningportal\Learning-System\Bba_Notes\note.Master" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "064111C8870F6FEC282503E3D6BAF665BB7B6699"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    
    #line 330 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 337 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 328 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 326 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 332 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 403 "D:\Learningportal\Learning-System\Bba_Notes\note.Master"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 343 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 403 "D:\Learningportal\Learning-System\Bba_Notes\note.Master"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 342 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    #line 333 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 329 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 331 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 338 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 334 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 325 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 403 "D:\Learningportal\Learning-System\Bba_Notes\note.Master"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 403 "D:\Learningportal\Learning-System\Bba_Notes\note.Master"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 327 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 336 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 403 "D:\Learningportal\Learning-System\Bba_Notes\note.Master"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class bba_notes_note_master : global::Learning_System.Bba_Notes.note {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.bba_notes_note_master.@__PageInspector_LoadHelper("SetTraceData");
        
        private System.Web.UI.ITemplate @__Template_ContentPlaceHolder1;
        
        private static bool @__initialized;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bba_notes_note_master() {
            ((global::Learning_System.Bba_Notes.note)(this)).AppRelativeVirtualPath = "~/Bba_Notes/note.Master";
            if ((global::ASP.bba_notes_note_master.@__initialized == false)) {
                global::ASP.bba_notes_note_master.@__initialized = true;
            }
            this.ContentPlaceHolders.Add("contentplaceholder1");
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(this.Context.ApplicationInstance));
            }
        }
        
        [TemplateContainer(typeof(Learning_System.Bba_Notes.note))]
        [TemplateInstanceAttribute(System.Web.UI.TemplateInstance.Single)]
        public virtual System.Web.UI.ITemplate Template_ContentPlaceHolder1 {
            get {
                return this.@__Template_ContentPlaceHolder1;
            }
            set {
                this.@__Template_ContentPlaceHolder1 = value;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <meta name=\"view" +
                    "port\" content=\"width=device-width, initial-scale=1\">\n    <link rel=\"stylesheet\" " +
                    "href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\">\n  " +
                    "  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"" +
                    "></script>\n    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.1" +
                    "4.7/umd/popper.min.js\"></script>\n    <script src=\"https://maxcdn.bootstrapcdn.co" +
                    "m/bootstrap/4.3.1/js/bootstrap.min.js\"></script>\n    <link rel=\"stylesheet\" href" +
                    "=\"https://pro.fontawesome.com/releases/v5.10.0/css/all.css\" />\n    <link href=\"m" +
                    "csdash.css\" rel=\"stylesheet\" />\n    <style>\n        /* ── Google Font ── */\n    " +
                    "    @import url(\'https://fonts.googleapis.com/css2?family=Sora:wght@400;600;700&" +
                    "family=DM+Sans:wght@400;500&display=swap\');\n\n        /* ══ SIDEBAR ══ */\n       " +
                    " #sidebar {\n            position: fixed;\n            top: 5rem;\n            left" +
                    ": 0;\n            width: 0;\n            height: calc(100vh - 5rem);\n            b" +
                    "ackground-color: #12183a;\n            color: #fff;\n            overflow-x: hidde" +
                    "n;\n            overflow-y: auto;\n            z-index: 999;\n            transitio" +
                    "n: width 0.3s ease;\n            font-family: \'DM Sans\', sans-serif;\n            " +
                    "border-right: 1px solid rgba(255,255,255,0.07);\n        }\n\n        /* Scrollbar " +
                    "*/\n        #sidebar::-webkit-scrollbar { width: 4px; }\n        #sidebar::-webkit" +
                    "-scrollbar-track { background: transparent; }\n        #sidebar::-webkit-scrollba" +
                    "r-thumb { background: rgba(255,255,255,0.12); border-radius: 4px; }\n\n        /* " +
                    "── SEMESTERS label at top ── */\n        #sidebar::before {\n            content: " +
                    "\"SEMESTERS\";\n            display: block;\n            font-family: \'Sora\', sans-s" +
                    "erif;\n            font-size: 10px;\n            font-weight: 700;\n            let" +
                    "ter-spacing: 2px;\n            color: rgba(255,255,255,0.35);\n            padding" +
                    ": 18px 20px 10px;\n        }\n\n        #sidebar ul {\n            padding: 0;\n     " +
                    "       list-style: none;\n            margin: 0;\n        }\n\n        #sidebar ul l" +
                    "i { padding: 0; }\n\n        /* ── Semester top-level link ── */\n        #sidebar " +
                    "> ul > li > a {\n            color: rgba(255,255,255,0.75);\n            text-deco" +
                    "ration: none;\n            display: flex;\n            align-items: center;\n      " +
                    "      padding: 11px 16px;\n            font-family: \'Sora\', sans-serif;\n         " +
                    "   font-size: 13.5px;\n            font-weight: 600;\n            border-left: 3px" +
                    " solid transparent;\n            transition: background 0.2s, border-color 0.2s, " +
                    "color 0.2s;\n            gap: 10px;\n        }\n\n        #sidebar > ul > li > a:hov" +
                    "er {\n            background: rgba(255,255,255,0.06);\n            color: #fff;\n  " +
                    "      }\n\n        #sidebar > ul > li.active-sem > a {\n            border-left-col" +
                    "or: #FF2D8D;\n            background: rgba(255,45,141,0.10);\n            color: #" +
                    "fff;\n        }\n\n        /* ── Numbered badge ── */\n        .sem-badge {\n        " +
                    "    display: inline-flex;\n            align-items: center;\n            justify-c" +
                    "ontent: center;\n            width: 22px;\n            height: 22px;\n            b" +
                    "order-radius: 7px;\n            background: rgba(255,255,255,0.12);\n            f" +
                    "ont-size: 11px;\n            font-weight: 700;\n            font-family: \'Sora\', s" +
                    "ans-serif;\n            color: rgba(255,255,255,0.7);\n            flex-shrink: 0;" +
                    "\n            transition: background 0.2s, color 0.2s;\n        }\n\n        #sideba" +
                    "r > ul > li.active-sem .sem-badge {\n            background: #FF2D8D;\n           " +
                    " color: #fff;\n        }\n\n        /* ── Chevron ── */\n        .submenu-toggle {\n " +
                    "           display: flex;\n            align-items: center;\n            justify-c" +
                    "ontent: space-between;\n            width: 100%;\n            gap: 8px;\n        }\n" +
                    "\n        .sem-name { flex: 1; }\n\n        .fas.fa-caret-down {\n            transi" +
                    "tion: transform 0.3s ease;\n            font-size: 11px;\n            opacity: 0.5" +
                    ";\n            margin-left: auto;\n        }\n\n        .rotate { transform: rotate(" +
                    "180deg); }\n\n        /* ── Submenu ── */\n        #sidebar .submenu {\n            " +
                    "display: none;\n            padding: 4px 0 8px 0;\n            background: rgba(0," +
                    "0,0,0.15);\n        }\n\n        #sidebar .submenu ul { padding: 0; }\n\n        #sid" +
                    "ebar .submenu ul li a {\n            color: rgba(255,255,255,0.5);\n            te" +
                    "xt-decoration: none;\n            display: flex;\n            align-items: center;" +
                    "\n            gap: 9px;\n            padding: 7px 16px 7px 36px;\n            font-" +
                    "size: 13px;\n            font-family: \'DM Sans\', sans-serif;\n            font-wei" +
                    "ght: 400;\n            transition: color 0.2s, background 0.2s;\n            posit" +
                    "ion: relative;\n        }\n\n        #sidebar .submenu ul li a::before {\n          " +
                    "  content: \"\";\n            width: 6px;\n            height: 6px;\n            bord" +
                    "er-radius: 50%;\n            background: rgba(255,255,255,0.25);\n            flex" +
                    "-shrink: 0;\n            transition: background 0.2s;\n        }\n\n        #sidebar" +
                    " .submenu ul li a:hover {\n            color: rgba(255,255,255,0.85);\n           " +
                    " background: rgba(255,255,255,0.04);\n        }\n\n        #sidebar .submenu ul li " +
                    "a:hover::before {\n            background: rgba(255,255,255,0.6);\n        }\n\n    " +
                    "    #sidebar .submenu ul li.active-subject > a {\n            color: #FF2D8D;\n   " +
                    "         font-weight: 500;\n        }\n\n        #sidebar .submenu ul li.active-sub" +
                    "ject > a::before {\n            background: #FF2D8D;\n        }\n\n        /* ══ CON" +
                    "TENT ══ */\n        #content {\n            margin-top: 5rem;\n            margin-l" +
                    "eft: 0;\n            width: 100%;\n            transition: margin-left 0.3s ease;\n" +
                    "        }\n\n        /* ══ OPEN STATE ══ */\n        .sidebar-open #sidebar { width" +
                    ": 300px; }\n\n        .sidebar-open #content {\n            margin-left: 300px;\n   " +
                    "         width: calc(100% - 300px);\n        }\n\n        /* ══ TOGGLE BUTTON ══ */" +
                    "\n        #menu-bar {\n            padding-top: 6rem;\n            position: fixed;" +
                    "\n            left: 10rem;\n            z-index: 1000;\n        }\n\n        #menu-ba" +
                    "r button {\n            background: #e8ecf7 !important;\n            border: 1.5px" +
                    " solid #c5cde8 !important;\n            border-radius: 8px;\n            width: 36" +
                    "px;\n            height: 36px;\n            display: flex;\n            align-items" +
                    ": center;\n            justify-content: center;\n            padding: 0;\n         " +
                    "   transition: background 0.2s, box-shadow 0.2s;\n            box-shadow: 0 2px 8" +
                    "px rgba(8,21,71,0.12);\n        }\n\n        #menu-bar button:hover {\n            b" +
                    "ackground: #d0d8f0 !important;\n            box-shadow: 0 4px 12px rgba(8,21,71,0" +
                    ".18) !important;\n        }\n\n        #icon { color: #12183a !important; font-size" +
                    ": 15px; font-weight: 900; }\n\n        /* ══ MEDIA QUERIES ══ */\n        @media (m" +
                    "ax-width: 900px) {\n            .sidebar-open #sidebar {\n                width: 3" +
                    "00px;\n                box-shadow: 4px 0 24px rgba(0,0,0,0.4);\n            }\n\n   " +
                    "         .sidebar-open #content {\n                margin-left: 0 !important;\n   " +
                    "             width: 100% !important;\n            }\n\n            #sidebar-overlay" +
                    " {\n                display: none;\n                position: fixed;\n             " +
                    "   inset: 0;\n                background: rgba(0,0,0,0.45);\n                z-ind" +
                    "ex: 998;\n            }\n\n            .sidebar-open #sidebar-overlay { display: bl" +
                    "ock; }\n\n            #content {\n                width: 100% !important;\n         " +
                    "       margin-left: 0 !important;\n                padding-left: 0.75rem;\n       " +
                    "         padding-right: 0.75rem;\n            }\n\n            #menu-bar {\n        " +
                    "        left: 0.5rem;\n                padding-top: 5.6rem;\n            }\n       " +
                    " }\n\n        @media (max-width: 576px) {\n            .sidebar-open #sidebar { wid" +
                    "th: 240px; }\n            #menu-bar { left: 0.3rem; }\n        }\n    </style>\n    " +
                    "<title>BBA Notes</title>\n</head>\n<body>\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        120,
                        7805,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.WebTools.BrowserLink.Runtime.WebForms.TraceHelpers, Microsoft.WebTools." +
                    "BrowserLink.Tracing, Version=18.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f1" +
                    "1d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.bba_notes_note_master.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.bba_notes_note_master.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control3() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n        <div id=\"sidebar-overlay\" onclick=\"closeSidebarOverlay()\"></div>\n\n      " +
                    "  <nav class=\"navbar navbar-expand-lg d-flex shad align-items-center justify-con" +
                    "tent-between flex-wrap navbar-light bg-light shadow bg-body rounded\"\n           " +
                    " style=\"position: fixed; top: 0; left: 0; width: 100%; height: 5rem; background-" +
                    "color: #f8f9fa; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); z-index: 1000; padding" +
                    ": 0 1rem;\">\n            <div class=\"d-flex align-items-center\" style=\"flex: 1; j" +
                    "ustify-content: center;\">\n                <a href=\"../../Default.aspx\">\n        " +
                    "            <img src=\"logo/logo.png\" alt=\"Logo\" width=\"150\">\n                </a" +
                    ">\n            </div>\n            <div class=\"d-flex align-items-center justify-c" +
                    "ontent-center\" style=\"flex: 1;\">\n                <h3 style=\"font-size: 2rem; fon" +
                    "t-weight: bold; color: #002366; margin: 0;\">BBA NOTES</h3>\n            </div>\n  " +
                    "          <div class=\"d-none d-md-flex align-items-center\" style=\"flex: 1; justi" +
                    "fy-content: flex-end;\">\n            </div>\n        </nav>\n\n        <div class=\"d" +
                    "-flex\">\n            <div id=\"sidebar\">\n                <ul>\n                    " +
                    "<li>\n                        <a href=\"#\" onclick=\"toggleSubmenu(event, \'first\')\"" +
                    ">\n                            <span class=\"submenu-toggle\"><span class=\"sem-badg" +
                    "e\">1</span><span class=\"sem-name\">First Sem</span> <i class=\"fas fa-caret-down f" +
                    "irst\"></i></span>\n                        </a>\n                        <div id=\"" +
                    "first-submenu\" class=\"submenu\">\n                            <ul>\n               " +
                    "                 <li><a href=\"business_english_I.aspx\">BE I</a></li>\n           " +
                    "                     <li><a href=\"principles_of_management.aspx\">P Mgmt</a></li>" +
                    "\n                                <li><a href=\"microeconomics.aspx\">Microeconomic" +
                    "s</a></li>\n                                <li><a href=\"introduction_to_accounti" +
                    "ng.aspx\">Intro To Accounting</a></li>\n                                <li><a hre" +
                    "f=\"fundamental_of_computer_principles_and_programming.aspx\">FCP &amp; P</a></li>" +
                    "\n                            </ul>\n                        </div>\n              " +
                    "      </li>\n\n                    <li>\n                        <a href=\"#\" onclic" +
                    "k=\"toggleSubmenu(event, \'second\')\">\n                            <span class=\"sub" +
                    "menu-toggle\"><span class=\"sem-badge\">2</span><span class=\"sem-name\">Second Sem</" +
                    "span> <i class=\"fas fa-caret-down second\"></i></span>\n                        </" +
                    "a>\n                        <div id=\"second-submenu\" class=\"submenu\">\n           " +
                    "                 <ul>\n                                <li><a href=\"human_resourc" +
                    "es_management.aspx\">HR Mgmt</a></li>\n                                <li><a href" +
                    "=\"principles_of_marketing.aspx\">P of Marketing</a></li>\n                        " +
                    "        <li><a href=\"internet_fundamental_and_applications.aspx\">IFA</a></li>\n  " +
                    "                              <li><a href=\"macroeconomics.aspx\">Macroeconomics</" +
                    "a></li>\n                                <li><a href=\"business_english_II.aspx\">B" +
                    "E II</a></li>\n                            </ul>\n                        </div>\n " +
                    "                   </li>\n\n                    <li>\n                        <a hr" +
                    "ef=\"#\" onclick=\"toggleSubmenu(event, \'third\')\">\n                            <spa" +
                    "n class=\"submenu-toggle\"><span class=\"sem-badge\">3</span><span class=\"sem-name\">" +
                    "Third Sem</span> <i class=\"fas fa-caret-down third\"></i></span>\n                " +
                    "        </a>\n                        <div id=\"third-submenu\" class=\"submenu\">\n  " +
                    "                          <ul>\n                                <li><a href=\"busi" +
                    "ness_organization.aspx\">B Organization</a></li>\n                                " +
                    "<li><a href=\"quantitative_methods_statistics.aspx\">QM</a></li>\n                 " +
                    "               <li><a href=\"business_communication.aspx\">B Communication</a></li" +
                    ">\n                                <li><a href=\"product_and_operation_management." +
                    "aspx\">P &amp; O Mgmt</a></li>\n                                <li><a href=\"entre" +
                    "preneurship.aspx\">Entrepreneurship</a></li>\n                            </ul>\n  " +
                    "                      </div>\n                    </li>\n\n                    <li>" +
                    "\n                        <a href=\"#\" onclick=\"toggleSubmenu(event, \'fourth\')\">\n " +
                    "                           <span class=\"submenu-toggle\"><span class=\"sem-badge\">" +
                    "4</span><span class=\"sem-name\">Fourth Sem</span> <i class=\"fas fa-caret-down fou" +
                    "rth\"></i></span>\n                        </a>\n                        <div id=\"f" +
                    "ourth-submenu\" class=\"submenu\">\n                            <ul>\n               " +
                    "                 <li><a href=\"business_law.aspx\">Business Law</a></li>\n         " +
                    "                       <li><a href=\"project_management.aspx\">PM</a></li>\n       " +
                    "                         <li><a href=\"introduction_to_financial_accounting.aspx\"" +
                    ">Intro To FA</a></li>\n                                <li><a href=\"company_law.a" +
                    "spx\">Company Law</a></li>\n                                <li><a href=\"psycholog" +
                    "y.aspx\">Psychology</a></li>\n                            </ul>\n                  " +
                    "      </div>\n                    </li>\n\n                    <li>\n               " +
                    "         <a href=\"#\" onclick=\"toggleSubmenu(event, \'fifth\')\">\n                  " +
                    "          <span class=\"submenu-toggle\"><span class=\"sem-badge\">5</span><span cla" +
                    "ss=\"sem-name\">Fifth Sem</span> <i class=\"fas fa-caret-down fifth\"></i></span>\n  " +
                    "                      </a>\n                        <div id=\"fifth-submenu\" class" +
                    "=\"submenu\">\n                            <ul>\n                                <li" +
                    "><a href=\"international_business_management.aspx\">Intl BM</a></li>\n             " +
                    "                   <li><a href=\"marketing_management.aspx\">Marketing Mgmt</a></l" +
                    "i>\n                                <li><a href=\"business_ethics.aspx\">B Ethics</" +
                    "a></li>\n                                <li><a href=\"sociology.aspx\">Sociology</" +
                    "a></li>\n                                <li><a href=\"management_information_syst" +
                    "em.aspx\">MIS</a></li>\n                            </ul>\n                        " +
                    "</div>\n                    </li>\n\n                    <li>\n                     " +
                    "   <a href=\"#\" onclick=\"toggleSubmenu(event, \'sixth\')\">\n                        " +
                    "    <span class=\"submenu-toggle\"><span class=\"sem-badge\">6</span><span class=\"se" +
                    "m-name\">Sixth Sem</span> <i class=\"fas fa-caret-down sixth\"></i></span>\n        " +
                    "                </a>\n                        <div id=\"sixth-submenu\" class=\"subm" +
                    "enu\">\n                            <ul>\n                                <li><a hr" +
                    "ef=\"e_commerce.aspx\">E-Commerce</a></li>\n                                <li><a " +
                    "href=\"organizational_behavior.aspx\">Org Behavior</a></li>\n                      " +
                    "          <li><a href=\"consumer_behavior.aspx\">Con Behavior</a></li>\n           " +
                    "                     <li><a href=\"strategic_management.aspx\">Strategic Mgmt</a><" +
                    "/li>\n                                <li><a href=\"innovation_management_for_glob" +
                    "al_competitiveness.aspx\">IMGC</a></li>\n                            </ul>\n       " +
                    "                 </div>\n                    </li>\n\n                    <li>\n    " +
                    "                    <a href=\"#\" onclick=\"toggleSubmenu(event, \'seventh\')\">\n     " +
                    "                       <span class=\"submenu-toggle\"><span class=\"sem-badge\">7</s" +
                    "pan><span class=\"sem-name\">Seventh Sem</span> <i class=\"fas fa-caret-down sevent" +
                    "h\"></i></span>\n                        </a>\n                        <div id=\"sev" +
                    "enth-submenu\" class=\"submenu\">\n                            <ul>\n                " +
                    "                <li><a href=\"retail_management.aspx\">Retail Mgmt</a></li>\n      " +
                    "                          <li><a href=\"event_management.aspx\">Event Mgmt</a></li" +
                    ">\n                                <li><a href=\"business_environment.aspx\">B Envi" +
                    "ronment</a></li>\n                                <li><a href=\"business_research_" +
                    "methods.aspx\">BR Methods</a></li>\n                                <li><a href=\"b" +
                    "usiness_finance.aspx\">B Finance</a></li>\n                            </ul>\n     " +
                    "                   </div>\n                    </li>\n\n                   \n       " +
                    "         </ul>\n            </div>\n\n            <div id=\"menu-bar\">\n             " +
                    "   <button type=\"button\" onclick=\"toggleSidebar()\" class=\"btn\" style=\"background" +
                    ": none;\">\n                    <i class=\"fa fa-arrow-right\" aria-hidden=\"true\" st" +
                    "yle=\"color: black;\" id=\"icon\"></i>\n                </button>\n            </div>\n" +
                    "\n            <div id=\"content\" style=\"padding-top: 1%; width: 90%; margin-left: " +
                    "5%;\">\n                ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        7957,
                        8343,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control4() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n                ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        16364,
                        17,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ContentPlaceHolder @__BuildControlContentPlaceHolder1() {
            global::System.Web.UI.WebControls.ContentPlaceHolder @__ctrl;
            
            #line 403 "D:\Learningportal\Learning-System\Bba_Notes\note.Master"
            @__ctrl = new global::System.Web.UI.WebControls.ContentPlaceHolder();
            
            #line default
            #line hidden
            this.ContentPlaceHolder1 = @__ctrl;
            
            #line 403 "D:\Learningportal\Learning-System\Bba_Notes\note.Master"
            @__ctrl.ID = "ContentPlaceHolder1";
            
            #line default
            #line hidden
            if ((this.ContentTemplates != null)) {
                this.@__Template_ContentPlaceHolder1 = ((System.Web.UI.ITemplate)(this.ContentTemplates["ContentPlaceHolder1"]));
            }
            if ((this.@__Template_ContentPlaceHolder1 != null)) {
                this.InstantiateInContentPlaceHolder(@__ctrl, this.@__Template_ContentPlaceHolder1);
            }
            else {
                global::System.Web.UI.LiteralControl @__ctrl1;
                
                #line 403 "D:\Learningportal\Learning-System\Bba_Notes\note.Master"
                @__ctrl1 = this.@__BuildControl__control4();
                
                #line default
                #line hidden
                System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
                
                #line 403 "D:\Learningportal\Learning-System\Bba_Notes\note.Master"
                @__parser.AddParsedSubObject(@__ctrl1);
                
                #line default
                #line hidden
            }
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        16300,
                        106,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control5() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n            </div>\n        </div>\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        16406,
                        39,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControlform2() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            
            #line 267 "D:\Learningportal\Learning-System\Bba_Notes\note.Master"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
            
            #line default
            #line hidden
            this.form2 = @__ctrl;
            
            #line 267 "D:\Learningportal\Learning-System\Bba_Notes\note.Master"
            @__ctrl.ID = "form2";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 267 "D:\Learningportal\Learning-System\Bba_Notes\note.Master"
            @__ctrl1 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 267 "D:\Learningportal\Learning-System\Bba_Notes\note.Master"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ContentPlaceHolder @__ctrl2;
            
            #line 267 "D:\Learningportal\Learning-System\Bba_Notes\note.Master"
            @__ctrl2 = this.@__BuildControlContentPlaceHolder1();
            
            #line default
            #line hidden
            
            #line 267 "D:\Learningportal\Learning-System\Bba_Notes\note.Master"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 267 "D:\Learningportal\Learning-System\Bba_Notes\note.Master"
            @__ctrl3 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 267 "D:\Learningportal\Learning-System\Bba_Notes\note.Master"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        7925,
                        8527,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control6() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n\n<script>\nfunction isMobile() {\n    return window.innerWidth <= 900;\n}\n\nfunction" +
                    " toggleSidebar() {\n    var sidebar = document.getElementById(\'sidebar\');\n    var" +
                    " content = document.getElementById(\'content\');\n    var menuBar = document.getEle" +
                    "mentById(\'menu-bar\');\n    var icon = document.getElementById(\'icon\');\n\n    if (!" +
                    "sidebar || !content || !menuBar || !icon) return;\n\n    if (document.body.classLi" +
                    "st.contains(\'sidebar-open\')) {\n        document.body.classList.remove(\'sidebar-o" +
                    "pen\');\n        sidebar.style.width = \'0\';\n        content.style.marginLeft = \'0\'" +
                    ";\n        content.style.width = \'100%\';\n        menuBar.style.left = \'0.5rem\';\n " +
                    "       icon.style.transform = \'rotate(0deg)\';\n    } else {\n        document.body" +
                    ".classList.add(\'sidebar-open\');\n        sidebar.style.width = \'300px\';\n        i" +
                    "f (!isMobile()) {\n            content.style.marginLeft = \'300px\';\n            co" +
                    "ntent.style.width = \'calc(100% - 300px)\';\n            menuBar.style.left = \'300p" +
                    "x\';\n        } else {\n            content.style.marginLeft = \'0\';\n            con" +
                    "tent.style.width = \'100%\';\n            menuBar.style.left = \'0.5rem\';\n        }\n" +
                    "        icon.style.transform = \'rotate(180deg)\';\n    }\n}\n\nfunction closeSidebarO" +
                    "verlay() {\n    var sidebar = document.getElementById(\'sidebar\');\n    var content" +
                    " = document.getElementById(\'content\');\n    var icon = document.getElementById(\'i" +
                    "con\');\n\n    document.body.classList.remove(\'sidebar-open\');\n    if (sidebar) sid" +
                    "ebar.style.width = \'0\';\n    if (content) {\n        content.style.marginLeft = \'0" +
                    "\';\n        content.style.width = \'100%\';\n    }\n    if (icon) icon.style.transfor" +
                    "m = \'rotate(0deg)\';\n}\n\nfunction toggleSubmenu(event, submenuId) {\n    if (event)" +
                    " event.preventDefault();\n\n    var submenu = document.getElementById(submenuId + " +
                    "\'-submenu\');\n    var icon = document.querySelector(\'.\' + submenuId);\n\n    if (!s" +
                    "ubmenu) return;\n\n    var parentLi = submenu.parentElement;\n\n    document.body.cl" +
                    "assList.add(\'sidebar-open\');\n\n    var items = document.querySelectorAll(\'#sideba" +
                    "r > ul > li\');\n    for (var i = 0; i < items.length; i++) {\n        var li = ite" +
                    "ms[i];\n        if (li !== parentLi) {\n            li.classList.remove(\'active-se" +
                    "m\');\n            var otherSubmenu = li.querySelector(\'.submenu\');\n            va" +
                    "r otherIcon = li.querySelector(\'.fas.fa-caret-down\');\n            if (otherSubme" +
                    "nu) otherSubmenu.style.display = \'none\';\n            if (otherIcon) otherIcon.cl" +
                    "assList.remove(\'rotate\');\n        }\n    }\n\n    if (submenu.style.display === \'bl" +
                    "ock\') {\n        submenu.style.display = \'none\';\n        if (icon) icon.classList" +
                    ".remove(\'rotate\');\n        if (parentLi) parentLi.classList.remove(\'active-sem\')" +
                    ";\n    } else {\n        submenu.style.display = \'block\';\n        if (icon) icon.c" +
                    "lassList.add(\'rotate\');\n        if (parentLi) parentLi.classList.add(\'active-sem" +
                    "\');\n\n        var sidebar = document.getElementById(\'sidebar\');\n        var conte" +
                    "nt = document.getElementById(\'content\');\n        var menuBar = document.getEleme" +
                    "ntById(\'menu-bar\');\n        var mainIcon = document.getElementById(\'icon\');\n\n   " +
                    "     if (sidebar) sidebar.style.width = \'300px\';\n        if (content) {\n        " +
                    "    content.style.marginLeft = \'300px\';\n            content.style.width = \'calc(" +
                    "100% - 300px)\';\n        }\n        if (menuBar) menuBar.style.left = \'300px\';\n   " +
                    "     if (mainIcon) mainIcon.style.transform = \'rotate(180deg)\';\n    }\n}\n\nwindow." +
                    "onload = function () {\n    var sidebar = document.getElementById(\'sidebar\');\n   " +
                    " var content = document.getElementById(\'content\');\n    var menuBar = document.ge" +
                    "tElementById(\'menu-bar\');\n    var icon = document.getElementById(\'icon\');\n\n    i" +
                    "f (!isMobile()) {\n        document.body.classList.add(\'sidebar-open\');\n        i" +
                    "f (sidebar) sidebar.style.width = \'300px\';\n        if (content) {\n            co" +
                    "ntent.style.marginLeft = \'300px\';\n            content.style.width = \'calc(100% -" +
                    " 300px)\';\n        }\n        if (menuBar) menuBar.style.left = \'300px\';\n        i" +
                    "f (icon) icon.style.transform = \'rotate(180deg)\';\n    } else {\n        if (menuB" +
                    "ar) menuBar.style.left = \'0.5rem\';\n    }\n\n    var links = document.querySelector" +
                    "All(\'#sidebar .submenu ul li a\');\n    var pathParts = window.location.pathname.s" +
                    "plit(\'/\');\n    var currentPage = pathParts.length > 0 ? pathParts[pathParts.leng" +
                    "th - 1].toLowerCase() : \'\';\n\n    for (var j = 0; j < links.length; j++) {\n      " +
                    "  var link = links[j];\n        var hrefAttr = link.getAttribute(\'href\');\n       " +
                    " var href = hrefAttr ? hrefAttr.toLowerCase() : \'\';\n\n        if (href === curren" +
                    "tPage) {\n            if (link.parentElement) link.parentElement.classList.add(\'a" +
                    "ctive-subject\');\n\n            var parentSubmenu = link.parentElement;\n          " +
                    "  while (parentSubmenu && !parentSubmenu.classList.contains(\'submenu\')) {\n      " +
                    "          parentSubmenu = parentSubmenu.parentElement;\n            }\n\n          " +
                    "  if (parentSubmenu) {\n                parentSubmenu.style.display = \'block\';\n  " +
                    "              var parentLi = parentSubmenu.parentElement;\n                if (pa" +
                    "rentLi) {\n                    parentLi.classList.add(\'active-sem\');\n            " +
                    "        var caret = parentLi.querySelector(\'.fas.fa-caret-down\');\n              " +
                    "      if (caret) caret.classList.add(\'rotate\');\n                }\n            }\n" +
                    "        }\n    }\n};\n</script>\n</body>\n</html>\n\r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        16452,
                        5248,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(bba_notes_note_master @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 1 "D:\Learningportal\Learning-System\Bba_Notes\note.Master"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "D:\Learningportal\Learning-System\Bba_Notes\note.Master"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl2;
            
            #line 1 "D:\Learningportal\Learning-System\Bba_Notes\note.Master"
            @__ctrl2 = this.@__BuildControlform2();
            
            #line default
            #line hidden
            
            #line 1 "D:\Learningportal\Learning-System\Bba_Notes\note.Master"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 1 "D:\Learningportal\Learning-System\Bba_Notes\note.Master"
            @__ctrl3 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 1 "D:\Learningportal\Learning-System\Bba_Notes\note.Master"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.@__BuildControlTree(this);
        }
    }
}
