//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.7.2")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_icnj0ylq {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_icnj0ylq() {
        }
        
        static object Create_ASP_bba_notes_international_business_management_aspx() {
            return new ASP.bba_notes_international_business_management_aspx();
        }
        
        static object Create_ASP_bba_notes_microeconomics_aspx() {
            return new ASP.bba_notes_microeconomics_aspx();
        }
        
        static object Create_ASP_bba_notes_banking_and_insurance_finc__aspx() {
            return new ASP.bba_notes_banking_and_insurance_finc__aspx();
        }
        
        static object Create_ASP_bba_notes_management_information_system_aspx() {
            return new ASP.bba_notes_management_information_system_aspx();
        }
        
        static object Create_ASP_bba_notes_consumer_behavior_aspx() {
            return new ASP.bba_notes_consumer_behavior_aspx();
        }
        
        static object Create_ASP_bba_notes_business_english_i_aspx() {
            return new ASP.bba_notes_business_english_i_aspx();
        }
        
        static object Create_ASP_bba_notes_business_communication_aspx() {
            return new ASP.bba_notes_business_communication_aspx();
        }
        
        static object Create_ASP_bba_notes_principles_of_marketing_aspx() {
            return new ASP.bba_notes_principles_of_marketing_aspx();
        }
        
        static object Create_ASP_bba_notes_retail_management_aspx() {
            return new ASP.bba_notes_retail_management_aspx();
        }
        
        static object Create_ASP_bba_notes_business_law_aspx() {
            return new ASP.bba_notes_business_law_aspx();
        }
    }
}
