//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.7.2")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_mlb00kuw {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_mlb00kuw() {
        }
        
        static object Create_ASP_bba_notes_business_ethics_aspx() {
            return new ASP.bba_notes_business_ethics_aspx();
        }
        
        static object Create_ASP_bba_notes_multinational_enterprise_market__aspx() {
            return new ASP.bba_notes_multinational_enterprise_market__aspx();
        }
        
        static object Create_ASP_bba_notes_macroeconomics_aspx() {
            return new ASP.bba_notes_macroeconomics_aspx();
        }
        
        static object Create_ASP_bba_notes_internet_fundamental_and_applications_aspx() {
            return new ASP.bba_notes_internet_fundamental_and_applications_aspx();
        }
        
        static object Create_ASP_bba_notes_business_communication_aspx() {
            return new ASP.bba_notes_business_communication_aspx();
        }
        
        static object Create_ASP_bba_notes_entrepreneurship_aspx() {
            return new ASP.bba_notes_entrepreneurship_aspx();
        }
        
        static object Create_ASP_bba_notes_business_environment_aspx() {
            return new ASP.bba_notes_business_environment_aspx();
        }
        
        static object Create_ASP_bba_notes_product_and_operation_management_aspx() {
            return new ASP.bba_notes_product_and_operation_management_aspx();
        }
        
        static object Create_ASP_bba_notes_project_management_aspx() {
            return new ASP.bba_notes_project_management_aspx();
        }
        
        static object Create_ASP_bba_notes_strategic_management_aspx() {
            return new ASP.bba_notes_strategic_management_aspx();
        }
        
        static object Create_ASP_bba_notes_business_organization_aspx() {
            return new ASP.bba_notes_business_organization_aspx();
        }
    }
}
