//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.7.2")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_cer3rwsc {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_cer3rwsc() {
        }
        
        static object Create_ASP_contact_aspx() {
            return new ASP.contact_aspx();
        }
        
        static object Create_ASP_aiblog_aspx() {
            return new ASP.aiblog_aspx();
        }
        
        static object Create_ASP_aboutus_aspx() {
            return new ASP.aboutus_aspx();
        }
        
        static object Create_ASP_default_aspx() {
            return new ASP.default_aspx();
        }
        
        static object Create_ASP_blog_aspx() {
            return new ASP.blog_aspx();
        }
        
        static object Create_ASP_feedback_aspx() {
            return new ASP.feedback_aspx();
        }
        
        static object Create_ASP_login_aspx() {
            return new ASP.login_aspx();
        }
        
        static object Create_ASP_register_aspx() {
            return new ASP.register_aspx();
        }
        
        static object Create_ASP_logout_aspx() {
            return new ASP.logout_aspx();
        }
    }
}
