//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.7.2")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_x3cs2esh {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_x3cs2esh() {
        }
        
        static object Create_ASP_bit_admin_socialvalues_ethics_aspx() {
            return new ASP.bit_admin_socialvalues_ethics_aspx();
        }
        
        static object Create_ASP_bit_admin_business_english_aspx() {
            return new ASP.bit_admin_business_english_aspx();
        }
        
        static object Create_ASP_bit_admin_web_technology_python__aspx() {
            return new ASP.bit_admin_web_technology_python__aspx();
        }
        
        static object Create_ASP_bit_admin_technopreneurship_aspx() {
            return new ASP.bit_admin_technopreneurship_aspx();
        }
        
        static object Create_ASP_bit_admin_human_computer_interaction_aspx() {
            return new ASP.bit_admin_human_computer_interaction_aspx();
        }
        
        static object Create_ASP_bit_admin_multimedia_system_aspx() {
            return new ASP.bit_admin_multimedia_system_aspx();
        }
        
        static object Create_ASP_bit_admin_data_structure_and_algorithm_aspx() {
            return new ASP.bit_admin_data_structure_and_algorithm_aspx();
        }
        
        static object Create_ASP_bit_admin_real_time_system_aspx() {
            return new ASP.bit_admin_real_time_system_aspx();
        }
        
        static object Create_ASP_bit_admin_data_communication_and_networks_aspx() {
            return new ASP.bit_admin_data_communication_and_networks_aspx();
        }
        
        static object Create_ASP_bit_admin_leadership_and_human_relations_aspx() {
            return new ASP.bit_admin_leadership_and_human_relations_aspx();
        }
        
        static object Create_ASP_bit_admin_principles_of_information_technology_aspx() {
            return new ASP.bit_admin_principles_of_information_technology_aspx();
        }
    }
}
