#pragma checksum "D:\Learningportal\Learning-System\Bhm_Notes\dash.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "91A176D7A767259AAC29406466F855844C8F7DFD"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    
    #line 2 "D:\Learningportal\Learning-System\Bhm_Notes\dash.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 325 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 331 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 338 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 2 "D:\Learningportal\Learning-System\Bhm_Notes\dash.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 326 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 330 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 1 "D:\Learningportal\Learning-System\Bhm_Notes\dash.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 336 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 329 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 333 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 2 "D:\Learningportal\Learning-System\Bhm_Notes\dash.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 334 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 2 "D:\Learningportal\Learning-System\Bhm_Notes\dash.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 328 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 337 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 2 "D:\Learningportal\Learning-System\Bhm_Notes\dash.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 332 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 327 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 343 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 342 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class bhm_notes_dash_aspx : global::Learning_System.Bhm_Notes.dash, System.Web.SessionState.IRequiresSessionState, System.Web.IHttpHandler {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.bhm_notes_dash_aspx.@__PageInspector_LoadHelper("SetTraceData");
        
        private static bool @__initialized;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bhm_notes_dash_aspx() {
            string[] dependencies;
            ((global::Learning_System.Bhm_Notes.dash)(this)).AppRelativeVirtualPath = "~/Bhm_Notes/dash.aspx";
            if ((global::ASP.bhm_notes_dash_aspx.@__initialized == false)) {
                dependencies = new string[2];
                dependencies[0] = "~/Bhm_Notes/dash.aspx";
                dependencies[1] = "~/Bhm_Notes/note.Master";
                global::ASP.bhm_notes_dash_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.bhm_notes_dash_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(this.Context.ApplicationInstance));
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n<style>\n  :root {\n    --primary: #0B1F66;\n    --secondary: #081547;\n    --pink:" +
                    " #FF2D8D;\n    --pink-dark: #d4206e;\n    --pink-glow: rgba(255,45,141,0.22);\n    " +
                    "--pink-soft: rgba(255,45,141,0.1);\n    --bg: #f0f3fc;\n    --bg-card: #ffffff;\n  " +
                    "  --text-primary: #0B1F66;\n    --text-secondary: #5a6a99;\n    --text-light: #a0a" +
                    "ec8;\n    --border: rgba(11,31,102,0.1);\n    --border-pink: rgba(255,45,141,0.18)" +
                    ";\n    --shadow-sm: 0 2px 12px rgba(8,21,71,0.07);\n    --shadow-md: 0 8px 32px rg" +
                    "ba(8,21,71,0.13);\n    --shadow-lg: 0 20px 60px rgba(8,21,71,0.2);\n    --radius: " +
                    "18px;\n    --radius-sm: 10px;\n    --sidebar-w: 265px;\n    --header-h: 68px;\n    -" +
                    "-ease: 0.28s cubic-bezier(0.4,0,0.2,1);\n  }\n\n  *, *::before, *::after { box-sizi" +
                    "ng: border-box; margin: 0; padding: 0; }\n\n  body {\n    font-family: \'DM Sans\', s" +
                    "ans-serif;\n    background: var(--bg);\n    color: var(--text-primary);\n    min-he" +
                    "ight: 100vh;\n    overflow-x: hidden;\n  }\n\n  ::-webkit-scrollbar { width: 5px; }\n" +
                    "  ::-webkit-scrollbar-track { background: transparent; }\n  ::-webkit-scrollbar-t" +
                    "humb { background: rgba(11,31,102,0.15); border-radius: 4px; }\n\n  /* ══ HEADER ═" +
                    "═ */\n  header {\n    position: fixed; top: 0; left: 0; right: 0; z-index: 200;\n  " +
                    "  height: var(--header-h);\n    background: rgba(255,255,255,0.92);\n    backdrop-" +
                    "filter: blur(20px);\n    -webkit-backdrop-filter: blur(20px);\n    border-bottom: " +
                    "1px solid var(--border);\n    display: flex; align-items: center;\n    padding: 0 " +
                    "28px 0 0;\n    box-shadow: 0 2px 24px rgba(8,21,71,0.07);\n  }\n\n  .header-logo {\n " +
                    "   width: var(--sidebar-w);\n    display: flex; align-items: center; justify-cont" +
                    "ent: center;\n    padding: 0 20px;\n    border-right: 1px solid var(--border);\n   " +
                    " height: 100%;\n    flex-shrink: 0;\n    gap: 10px;\n  }\n\n  .logo-mark {\n    width:" +
                    " 36px; height: 36px;\n    background: linear-gradient(135deg, var(--primary), var" +
                    "(--pink));\n    border-radius: 10px;\n    display: flex; align-items: center; just" +
                    "ify-content: center;\n    font-family: \'Sora\', sans-serif;\n    font-weight: 800; " +
                    "font-size: 14px; color: white;\n    flex-shrink: 0;\n  }\n\n  .logo-text { display: " +
                    "flex; flex-direction: column; }\n  .logo-text strong { font-family: \'Sora\', sans-" +
                    "serif; font-size: 14px; font-weight: 800; color: var(--primary); line-height: 1." +
                    "1; }\n  .logo-text span { font-size: 10px; color: var(--text-light); letter-spaci" +
                    "ng: 0.3px; }\n\n  .header-center { flex: 1; display: flex; align-items: center; pa" +
                    "dding: 0 28px; gap: 16px; }\n\n  .page-title {\n    font-family: \'Sora\', sans-serif" +
                    ";\n    font-size: 15px; font-weight: 700;\n    color: var(--primary);\n    letter-s" +
                    "pacing: -0.2px;\n    white-space: nowrap;\n    display: flex; align-items: center;" +
                    " gap: 8px;\n  }\n  .page-title .tag {\n    font-size: 10px; font-weight: 700;\n    b" +
                    "ackground: var(--pink); color: white;\n    padding: 3px 9px; border-radius: 50px;" +
                    "\n    letter-spacing: 0.4px; font-family: \'Sora\', sans-serif;\n  }\n\n  .search-bar " +
                    "{\n    display: flex; align-items: center; gap: 10px;\n    background: var(--bg); " +
                    "border: 1.5px solid var(--border);\n    border-radius: 50px; padding: 9px 18px;\n " +
                    "   max-width: 340px; width: 100%; transition: var(--ease);\n  }\n  .search-bar:foc" +
                    "us-within { border-color: var(--pink); box-shadow: 0 0 0 4px var(--pink-glow); b" +
                    "ackground: white; }\n  .search-bar svg { color: var(--text-light); flex-shrink: 0" +
                    "; }\n  .search-bar input { border: none; background: transparent; font-family: \'D" +
                    "M Sans\', sans-serif; font-size: 13.5px; color: var(--text-primary); outline: non" +
                    "e; width: 100%; }\n  .search-bar input::placeholder { color: var(--text-light); }" +
                    "\n\n  .header-actions { display: flex; align-items: center; gap: 8px; }\n\n  .icon-b" +
                    "tn {\n    width: 38px; height: 38px; border-radius: 10px;\n    border: 1.5px solid" +
                    " var(--border); background: white;\n    display: flex; align-items: center; justi" +
                    "fy-content: center;\n    cursor: pointer; transition: var(--ease); color: var(--t" +
                    "ext-secondary); position: relative;\n  }\n  .icon-btn:hover { background: var(--bg" +
                    "); border-color: var(--pink); color: var(--pink); }\n\n  .notif-dot { position: ab" +
                    "solute; top: 8px; right: 8px; width: 7px; height: 7px; background: var(--pink); " +
                    "border-radius: 50%; border: 2px solid white; }\n\n  .avatar {\n    width: 38px; hei" +
                    "ght: 38px; border-radius: 50%;\n    background: linear-gradient(135deg, var(--pri" +
                    "mary), var(--pink));\n    display: flex; align-items: center; justify-content: ce" +
                    "nter;\n    font-family: \'Sora\', sans-serif; font-weight: 700; font-size: 13px; co" +
                    "lor: white;\n    cursor: pointer; box-shadow: 0 2px 10px var(--pink-glow); border" +
                    ": 2px solid white;\n  }\n\n  /* ══ SIDEBAR ══ */\n  .sidebar {\n    position: fixed; " +
                    "left: 0; top: var(--header-h);\n    width: var(--sidebar-w); height: calc(100vh -" +
                    " var(--header-h));\n    background: var(--secondary); overflow-y: auto; overflow-" +
                    "x: hidden;\n    padding: 18px 10px 24px; z-index: 150; transition: var(--ease);\n " +
                    "   border-right: 1px solid rgba(255,255,255,0.05);\n  }\n  .sidebar::-webkit-scrol" +
                    "lbar { width: 3px; }\n  .sidebar::-webkit-scrollbar-thumb { background: rgba(255," +
                    "255,255,0.08); border-radius: 3px; }\n\n  .sidebar-label { font-size: 10px; font-w" +
                    "eight: 700; text-transform: uppercase; letter-spacing: 1.8px; color: rgba(255,25" +
                    "5,255,0.28); padding: 4px 12px 10px; margin-top: 4px; }\n\n  .sem-item { margin-bo" +
                    "ttom: 1px; }\n\n  .sem-header {\n    display: flex; align-items: center; gap: 10px;" +
                    " padding: 9px 12px;\n    border-radius: var(--radius-sm); cursor: pointer; transi" +
                    "tion: var(--ease);\n    color: rgba(255,255,255,0.58); font-size: 13px; font-weig" +
                    "ht: 500;\n    position: relative; user-select: none;\n  }\n  .sem-header:hover { ba" +
                    "ckground: rgba(255,255,255,0.06); color: rgba(255,255,255,0.9); }\n  .sem-header." +
                    "active { background: rgba(255,45,141,0.16); color: white; }\n  .sem-header.active" +
                    "::before { content: \'\'; position: absolute; left: 0; top: 20%; bottom: 20%; widt" +
                    "h: 3px; background: var(--pink); border-radius: 0 3px 3px 0; }\n\n  .sem-icon { wi" +
                    "dth: 26px; height: 26px; background: rgba(255,255,255,0.07); border-radius: 7px;" +
                    " display: flex; align-items: center; justify-content: center; font-size: 12px; f" +
                    "lex-shrink: 0; transition: var(--ease); }\n  .sem-header.active .sem-icon { backg" +
                    "round: rgba(255,45,141,0.28); }\n\n  .sem-label { flex: 1; }\n  .sem-chevron { tran" +
                    "sition: var(--ease); opacity: 0.45; flex-shrink: 0; }\n  .sem-item.open .sem-chev" +
                    "ron { transform: rotate(180deg); opacity: 1; color: var(--pink); }\n\n  .sem-subje" +
                    "cts { display: none; padding: 3px 0 3px 16px; }\n  .sem-item.open .sem-subjects {" +
                    " display: block; }\n\n  .subject-link {\n    display: flex; align-items: center; ga" +
                    "p: 8px; padding: 7px 12px; border-radius: 8px;\n    font-size: 12.5px; color: rgb" +
                    "a(255,255,255,0.4); cursor: pointer; transition: var(--ease);\n  }\n  .subject-lin" +
                    "k:hover { color: rgba(255,255,255,0.75); background: rgba(255,255,255,0.04); }\n " +
                    " .subject-link.active { color: var(--pink); background: rgba(255,45,141,0.08); f" +
                    "ont-weight: 500; }\n  .subject-dot { width: 4px; height: 4px; border-radius: 50%;" +
                    " background: currentColor; flex-shrink: 0; }\n\n  .course-tabs { display: flex; ga" +
                    "p: 6px; padding: 0 8px 14px; margin-bottom: 4px; }\n  .ctab {\n    flex: 1; paddin" +
                    "g: 7px 0; border-radius: 8px;\n    font-family: \'Sora\', sans-serif; font-size: 11" +
                    "px; font-weight: 700;\n    text-align: center; cursor: pointer; transition: var(-" +
                    "-ease);\n    color: rgba(255,255,255,0.4); border: 1px solid rgba(255,255,255,0.0" +
                    "7);\n    background: rgba(255,255,255,0.04); letter-spacing: 0.3px;\n  }\n  .ctab.a" +
                    "ctive { background: var(--pink); color: white; border-color: transparent; box-sh" +
                    "adow: 0 3px 12px rgba(255,45,141,0.4); }\n  .ctab:not(.active):hover { background" +
                    ": rgba(255,255,255,0.08); color: rgba(255,255,255,0.7); }\n\n  /* ══ MAIN ══ */\n  " +
                    ".main { margin-left: var(--sidebar-w); padding-top: var(--header-h); min-height:" +
                    " 100vh; width: calc(100% - var(--sidebar-w)); }\n  .main-inner { padding: 30px 36" +
                    "px; width: 100%; }\n\n  /* ══ HERO BANNER ══ */\n  .hero-banner {\n    background: l" +
                    "inear-gradient(135deg, #0B1F66 0%, #081547 100%);\n    border-radius: 24px; paddi" +
                    "ng: 0; position: relative; overflow: hidden;\n    box-shadow: var(--shadow-lg); m" +
                    "argin-bottom: 28px;\n    display: grid; grid-template-columns: 1fr 340px; min-hei" +
                    "ght: 28px;\n  }\n  .hero-banner::before { content: \'\'; position: absolute; top: -1" +
                    "00px; right: 280px; width: 420px; height: 420px; background: radial-gradient(cir" +
                    "cle, rgba(245,197,66,0.10) 0%, transparent 65%); pointer-events: none; }\n  .hero" +
                    "-banner::after { content: \'\'; position: absolute; bottom: -80px; left: 20%; widt" +
                    "h: 300px; height: 300px; background: radial-gradient(circle, rgba(8,21,71,0.4) 0" +
                    "%, transparent 70%); pointer-events: none; }\n\n  .hero-shapes { position: absolut" +
                    "e; inset: 0; pointer-events: none; overflow: hidden; }\n  .shape { position: abso" +
                    "lute; border-radius: 50%; border: 1px solid rgba(255,255,255,0.07); }\n  .shape-1" +
                    " { width: 200px; height: 200px; top: -60px; right: 300px; border-color: rgba(245" +
                    ",197,66,0.12); }\n  .shape-2 { width: 120px; height: 120px; bottom: -30px; right:" +
                    " 380px; border-color: rgba(255,255,255,0.06); }\n  .shape-3 { width: 60px; height" +
                    ": 60px; top: 40px; right: 440px; background: rgba(245,197,66,0.05); border: none" +
                    "; }\n\n  .hero-content { padding: 44px 44px 40px; display: flex; flex-direction: c" +
                    "olumn; justify-content: center; position: relative; z-index: 2; }\n\n  @keyframes " +
                    "pulse { 0%,100% { opacity: 1; transform: scale(1); } 50% { opacity: 0.5; transfo" +
                    "rm: scale(0.8); } }\n\n  .hero-title { font-family: \'Sora\', sans-serif; font-size:" +
                    " 34px; font-weight: 800; color: white; line-height: 1.15; letter-spacing: -0.8px" +
                    "; margin-bottom: 10px; }\n  .hero-title .highlight { color: #F5C542; }\n  .hero-ti" +
                    "tle .separator { color: rgba(255,255,255,0.25); font-weight: 300; margin: 0 8px;" +
                    " }\n\n  .hero-mini-stats { display: flex; gap: 0; margin-bottom: 30px; }\n  .hms-it" +
                    "em { display: flex; flex-direction: column; gap: 2px; padding-right: 22px; }\n  ." +
                    "hms-item + .hms-item { padding-left: 22px; border-left: 1px solid rgba(255,255,2" +
                    "55,0.1); }\n  .hms-val { font-family: \'Sora\', sans-serif; font-size: 24px; font-w" +
                    "eight: 800; color: white; }\n  .hms-val span { color: #F5C542; font-size: 16px; }" +
                    "\n  .hms-lbl { font-size: 10px; font-weight: 600; color: rgba(255,255,255,0.38); " +
                    "text-transform: uppercase; letter-spacing: 0.9px; }\n\n\n  .btn-pink {\n    display:" +
                    " inline-flex; align-items: center; gap: 9px;\n    background: var(--pink); color:" +
                    " white;\n    font-family: \'Sora\', sans-serif; font-weight: 700; font-size: 13.5px" +
                    ";\n    padding: 12px 24px; border-radius: 12px; border: none; cursor: pointer;\n  " +
                    "  transition: var(--ease); box-shadow: 0 4px 20px rgba(255,45,141,0.45); letter-" +
                    "spacing: 0.2px;\n  }\n  .btn-pink:hover { background: var(--pink-dark); transform:" +
                    " translateY(-2px); box-shadow: 0 8px 28px rgba(255,45,141,0.55); }\n\n  .hero-visu" +
                    "al { position: relative; z-index: 2; display: flex; align-items: flex-end; justi" +
                    "fy-content: center; padding: 0 20px 0 0; overflow: hidden; }\n  .hero-illustratio" +
                    "n { width: 100%; height: 100%; display: flex; align-items: flex-end; justify-con" +
                    "tent: center; position: relative; }\n  .ilu-glow { position: absolute; bottom: 0;" +
                    " left: 50%; transform: translateX(-50%); width: 260px; height: 120px; background" +
                    ": radial-gradient(ellipse, rgba(245,197,66,0.15) 0%, transparent 70%); pointer-e" +
                    "vents: none; }\n  .student-fig { width: 240px; height: 260px; position: relative;" +
                    " flex-shrink: 0; }\n\n  .ilu-badge { position: absolute; background: white; border" +
                    "-radius: 14px; padding: 9px 14px; box-shadow: 0 8px 28px rgba(8,21,71,0.22); dis" +
                    "play: flex; align-items: center; gap: 8px; white-space: nowrap; animation: float" +
                    " 3s ease-in-out infinite; }\n  .ilu-badge:nth-child(2) { animation-delay: 1.2s; }" +
                    "\n  .ilu-badge:nth-child(3) { animation-delay: 2.1s; }\n  @keyframes float { 0%,10" +
                    "0% { transform: translateY(0); } 50% { transform: translateY(-6px); } }\n  .ib-1 " +
                    "{ top: 30px; left: -20px; }\n  .ib-2 { top: 110px; right: -24px; }\n  .ib-3 { bott" +
                    "om: 68px; left: -30px; }\n\n  .ib-icon { width: 30px; height: 30px; border-radius:" +
                    " 8px; display: flex; align-items: center; justify-content: center; font-size: 15" +
                    "px; flex-shrink: 0; }\n  .ib-icon.blue { background: rgba(11,31,102,0.1); }\n  .ib" +
                    "-icon.pink { background: rgba(255,45,141,0.1); }\n  .ib-icon.green { background: " +
                    "rgba(16,185,129,0.1); }\n  .ib-txt strong { font-family: \'Sora\', sans-serif; font" +
                    "-size: 12px; font-weight: 700; color: var(--primary); display: block; line-heigh" +
                    "t: 1.2; }\n  .ib-txt span { font-size: 10px; color: var(--text-secondary); }\n\n  /" +
                    "* ══ SECTIONS ══ */\n  .section-title { font-family: \'Sora\', sans-serif; font-siz" +
                    "e: 16px; font-weight: 700; color: var(--primary); display: flex; align-items: ce" +
                    "nter; gap: 10px; }\n  .section-icon { width: 32px; height: 32px; border-radius: 9" +
                    "px; background: var(--pink-soft); display: flex; align-items: center; justify-co" +
                    "ntent: center; font-size: 15px; }\n\n\n  /* ══ AFFILIATION BANNER ══ */\n  .affil-ba" +
                    "nner {\n    background: linear-gradient(135deg, var(--secondary) 0%, var(--primar" +
                    "y) 60%, #162077 100%);\n    border-radius: 20px; padding: 28px 36px; display: fle" +
                    "x; align-items: center; gap: 32px;\n    position: relative; overflow: hidden; box" +
                    "-shadow: var(--shadow-md); margin-bottom: 28px;\n  }\n  .affil-banner::before { co" +
                    "ntent: \'\'; position: absolute; top: -60px; right: -60px; width: 260px; height: 2" +
                    "60px; background: radial-gradient(circle, rgba(255,45,141,0.15) 0%, transparent " +
                    "65%); pointer-events: none; }\n\n  .affil-left { flex-shrink: 0; display: flex; fl" +
                    "ex-direction: column; gap: 4px; }\n  .affil-label { font-size: 10px; font-weight:" +
                    " 700; color: rgba(255,255,255,0.4); text-transform: uppercase; letter-spacing: 1" +
                    ".5px; font-family: \'Sora\', sans-serif; }\n  .affil-name { font-family: \'Sora\', sa" +
                    "ns-serif; font-size: 20px; font-weight: 800; color: white; letter-spacing: -0.3p" +
                    "x; }\n  .affil-name span { color: var(--pink); }\n  .affil-sub { font-size: 12px; " +
                    "color: rgba(255,255,255,0.45); margin-top: 2px; }\n  .affil-divider { width: 1px;" +
                    " height: 54px; background: rgba(255,255,255,0.12); flex-shrink: 0; }\n  .affil-pi" +
                    "lls { display: flex; gap: 10px; flex-wrap: wrap; flex: 1; }\n  .apill { display: " +
                    "inline-flex; align-items: center; gap: 7px; background: rgba(255,255,255,0.08); " +
                    "border: 1px solid rgba(255,255,255,0.12); border-radius: 10px; padding: 9px 14px" +
                    "; font-size: 12px; font-weight: 500; color: rgba(255,255,255,0.75); transition: " +
                    "var(--ease); }\n  .apill:hover { background: rgba(255,255,255,0.14); color: white" +
                    "; border-color: rgba(255,45,141,0.4); }\n  .apill-icon { font-size: 15px; }\n  .af" +
                    "fil-right { flex-shrink: 0; }\n\n  .btn-learn { display: inline-flex; align-items:" +
                    " center; gap: 9px; background: white; color: var(--primary); font-family: \'Sora\'" +
                    ", sans-serif; font-weight: 700; font-size: 13px; padding: 12px 22px; border-radi" +
                    "us: 12px; border: none; cursor: pointer; transition: var(--ease); box-shadow: 0 " +
                    "4px 16px rgba(0,0,0,0.12); white-space: nowrap; }\n  .btn-learn:hover { backgroun" +
                    "d: var(--pink); color: white; transform: translateY(-2px); box-shadow: 0 8px 24p" +
                    "x rgba(255,45,141,0.4); }\n\n  /* ══ ABOUT SECTION ══ */\n  .about-section { displa" +
                    "y: grid; grid-template-columns: 1fr 360px; gap: 32px; margin-bottom: 28px; align" +
                    "-items: start; }\n\n  .about-left { background: white; border-radius: 22px; border" +
                    ": 1.5px solid var(--border); padding: 36px 38px 32px; box-shadow: var(--shadow-s" +
                    "m); }\n  .about-label { font-size: 11px; font-weight: 700; text-transform: upperc" +
                    "ase; letter-spacing: 1.8px; color: var(--pink); font-family: \'Sora\', sans-serif;" +
                    " margin-bottom: 10px; }\n  .about-heading { font-family: \'Sora\', sans-serif; font" +
                    "-size: 26px; font-weight: 800; color: var(--primary); letter-spacing: -0.5px; li" +
                    "ne-height: 1.2; margin-bottom: 20px; }\n  .about-heading span { color: #16a34a; }" +
                    "\n  .about-para { font-size: 14px; color: #374151; line-height: 1.75; margin-bott" +
                    "om: 14px; }\n  .about-para strong { color: var(--primary); font-weight: 700; }\n  " +
                    ".about-para:last-of-type { margin-bottom: 24px; }\n\n\n  .about-btns { display: fle" +
                    "x; gap: 12px; flex-wrap: wrap; }\n\n  /* ══ POSTER ══ */\n  .about-right { position" +
                    ": sticky; top: calc(var(--header-h) + 20px); }\n  .poster-wrap { position: relati" +
                    "ve; }\n  .poster-glow { position: absolute; bottom: -20px; left: 50%; transform: " +
                    "translateX(-50%); width: 280px; height: 60px; background: radial-gradient(ellips" +
                    "e, rgba(255,45,141,0.25) 0%, transparent 70%); pointer-events: none; }\n  .poster" +
                    "-card { border-radius: 20px; overflow: hidden; box-shadow: 0 24px 64px rgba(8,21" +
                    ",71,0.28); position: relative; }\n\n  .poster-inner {\n    background: linear-gradi" +
                    "ent(160deg, #0047b3 0%, #0B1F66 35%, #081547 70%, #060e33 100%);\n    padding: 22" +
                    "px 20px 16px; position: relative; overflow: hidden; min-height: 520px;\n  }\n  .po" +
                    "ster-inner::before { content: \'\'; position: absolute; top: -80px; right: -60px; " +
                    "width: 280px; height: 280px; background: radial-gradient(circle, rgba(255,45,141" +
                    ",0.15) 0%, transparent 65%); pointer-events: none; }\n  .poster-inner::after { co" +
                    "ntent: \'\'; position: absolute; top: 0; left: 0; right: 0; bottom: 0; background:" +
                    " url(\"data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'60\' he" +
                    "ight=\'60\'%3E%3Cpath d=\'M30 0 L60 30 L30 60 L0 30Z\' stroke=\'rgba(255,255,255,0.03" +
                    ")\' fill=\'none\'/%3E%3C/svg%3E\") repeat; pointer-events: none; }\n\n  .poster-logos " +
                    "{ display: flex; align-items: center; justify-content: space-between; margin-bot" +
                    "tom: 18px; position: relative; z-index: 2; }\n  .poster-logo-tx { display: flex; " +
                    "align-items: center; gap: 7px; }\n  .tx-text-wrap { display: flex; flex-direction" +
                    ": column; }\n  .tx-name { font-family: \'Sora\', sans-serif; font-size: 17px; font-" +
                    "weight: 900; color: white; letter-spacing: -0.3px; line-height: 1; }\n  .tx-sub {" +
                    " font-size: 8px; color: rgba(255,255,255,0.5); line-height: 1.2; }\n\n  .poster-lo" +
                    "go-luc { display: flex; align-items: center; gap: 6px; }\n  .luc-seal { width: 28" +
                    "px; height: 28px; border-radius: 50%; background: #c8102e; display: flex; align-" +
                    "items: center; justify-content: center; font-family: \'Sora\', sans-serif; font-we" +
                    "ight: 800; font-size: 8px; color: white; border: 2px solid rgba(255,255,255,0.3)" +
                    "; flex-shrink: 0; }\n  .luc-name { font-size: 8px; font-weight: 700; color: rgba(" +
                    "255,255,255,0.75); line-height: 1.4; font-family: \'Sora\', sans-serif; letter-spa" +
                    "cing: 0.3px; }\n\n  .poster-tagline { font-family: \'Sora\', sans-serif; font-size: " +
                    "11px; font-weight: 600; color: rgba(255,255,255,0.65); letter-spacing: 1.5px; ma" +
                    "rgin-bottom: 2px; position: relative; z-index: 2; }\n  .poster-main-title { font-" +
                    "family: \'Sora\', sans-serif; font-size: 30px; font-weight: 900; color: #00c8ff; l" +
                    "ine-height: 1.05; letter-spacing: -0.5px; margin-bottom: 14px; position: relativ" +
                    "e; z-index: 2; }\n  .poster-degree-row { display: flex; align-items: center; gap:" +
                    " 12px; position: relative; z-index: 2; }\n  .poster-degree-title { font-family: \'" +
                    "Sora\', sans-serif; font-size: 36px; font-weight: 900; color: white; letter-spaci" +
                    "ng: -1px; line-height: 1; position: relative; z-index: 2; }\n  .poster-degree-sub" +
                    " { font-size: 11px; color: rgba(255,255,255,0.6); line-height: 1.4; margin-botto" +
                    "m: 16px; position: relative; z-index: 2; }\n  .poster-degree-sub strong { color: " +
                    "rgba(255,255,255,0.9); }\n\n  .poster-why-box { background: rgba(255,255,255,0.08)" +
                    "; border: 1px solid rgba(255,255,255,0.12); border-radius: 12px; padding: 14px 1" +
                    "6px; margin-bottom: 14px; position: relative; z-index: 2; max-width: 175px; }\n  " +
                    ".pwb-title { font-family: \'DM Sans\', sans-serif; font-size: 13px; color: rgba(25" +
                    "5,255,255,0.75); margin-bottom: 10px; line-height: 1.4; }\n  .pwb-title span { fo" +
                    "nt-family: \'Sora\', sans-serif; font-size: 16px; font-weight: 900; color: #00c8ff" +
                    "; }\n  .pwb-item { font-size: 11px; color: rgba(255,255,255,0.65); margin-bottom:" +
                    " 5px; display: flex; align-items: center; gap: 4px; }\n\n  .poster-admission { pos" +
                    "ition: absolute; bottom: 50px; right: 16px; z-index: 3; text-align: right; }\n  ." +
                    "pa-open { font-family: \'Sora\', sans-serif; font-size: 20px; font-weight: 900; co" +
                    "lor: white; line-height: 1.1; letter-spacing: -0.5px; text-shadow: 0 2px 8px rgb" +
                    "a(0,0,0,0.3); }\n\n  .poster-student { position: absolute; bottom: 0; right: -8px;" +
                    " z-index: 2; }\n\n  .poster-footer { border-top: 1px solid rgba(255,255,255,0.1); " +
                    "padding-top: 10px; margin-top: 4px; position: relative; z-index: 2; }\n  .pf-item" +
                    " { font-size: 9.5px; color: rgba(255,255,255,0.5); margin-bottom: 3px; }\n\n  @med" +
                    "ia (max-width: 1100px) {\n    .about-section { grid-template-columns: 1fr; }\n    " +
                    ".about-right { position: static; }\n    .poster-card { max-width: 360px; }\n  }\n\n " +
                    " /* ══ FADE ANIMATIONS ══ */\n  .fade-up { opacity: 0; transform: translateY(22px" +
                    "); animation: fadeUp 0.55s cubic-bezier(0.22,1,0.36,1) forwards; }\n  .d1 { anima" +
                    "tion-delay: 0.05s; } .d2 { animation-delay: 0.15s; } .d3 { animation-delay: 0.25" +
                    "s; }\n  .d4 { animation-delay: 0.35s; } .d5 { animation-delay: 0.45s; } .d6 { ani" +
                    "mation-delay: 0.55s; }\n  @keyframes fadeUp { to { opacity: 1; transform: transla" +
                    "teY(0); } }\n\n  .overlay { display: none; position: fixed; inset: 0; background: " +
                    "rgba(8,21,71,0.4); z-index: 140; backdrop-filter: blur(4px); }\n  .overlay.show {" +
                    " display: block; }\n\n  /* ══ RESPONSIVE ══ */\n  @media (max-width: 1100px) { .why" +
                    "-grid { grid-template-columns: repeat(2, 1fr); } .affil-banner { flex-wrap: wrap" +
                    "; gap: 20px; } .affil-divider { display: none; } }\n  @media (max-width: 900px) {" +
                    "\n    :root { --sidebar-w: 0px; }\n    .sidebar { left: -265px; width: 265px; }\n  " +
                    "  .sidebar.open { left: 0; }\n    .main { margin-left: 0; width: 100%; }\n    .hea" +
                    "der-logo { width: auto; border-right: none; }\n    .hero-banner { grid-template-c" +
                    "olumns: 1fr; }\n    .hero-visual { display: none; }\n    .why-grid { grid-template" +
                    "-columns: 1fr; }\n  }\n  @media (max-width: 600px) { .main-inner { padding: 20px 1" +
                    "6px; } .hero-content { padding: 28px 24px; } .hero-title { font-size: 24px; } .a" +
                    "ffil-banner { padding: 20px 20px; } }\n\n  /* ── Master Page overrides ── */\n  hea" +
                    "der { display: none !important; }\n  .sidebar { display: none !important; }\n  .ov" +
                    "erlay { display: none !important; }\n  body { padding-top: 0 !important; backgrou" +
                    "nd: var(--bg) !important; }\n  .main { margin-left: 0 !important; padding-top: 0 " +
                    "!important; width: 100% !important; }\n  .main-inner { padding: 24px 32px !import" +
                    "ant; }\n</style>\n\n<main class=\"main\">\n  <div class=\"main-inner\">\n\n    <!-- HERO B" +
                    "ANNER -->\n    <div class=\"hero-banner fade-up d1\">\n      <div class=\"hero-shapes" +
                    "\">\n        <div class=\"shape shape-1\"></div>\n        <div class=\"shape shape-2\">" +
                    "</div>\n        <div class=\"shape shape-3\"></div>\n      </div>\n\n      <div class=" +
                    "\"hero-content\">\n\n        <div class=\"hero-title\">\n          Craft Exceptional<br" +
                    ">\n          <span class=\"highlight\">Hospitality Experiences</span>\n        </div" +
                    ">\n\n        <div class=\"hero-mini-stats\">\n          <div class=\"hms-item\">\n      " +
                    "      <div class=\"hms-val\">4<span>yr</span></div>\n            <div class=\"hms-lb" +
                    "l\">Program</div>\n          </div>\n          <div class=\"hms-item\">\n            <" +
                    "div class=\"hms-val\">8</div>\n            <div class=\"hms-lbl\">Semesters</div>\n   " +
                    "       </div>\n          <div class=\"hms-item\">\n            <div class=\"hms-val\">" +
                    "120</div>\n            <div class=\"hms-lbl\">Credit Hours</div>\n          </div>\n " +
                    "         <div class=\"hms-item\">\n            <div class=\"hms-val\">1000<span>+</sp" +
                    "an></div>\n            <div class=\"hms-lbl\">Graduates</div>\n          </div>\n    " +
                    "    </div>\n\n      </div>\n\n      <!-- ILLUSTRATION PANEL -->\n      <div class=\"he" +
                    "ro-visual\">\n        <div class=\"hero-illustration\">\n          <div class=\"ilu-gl" +
                    "ow\"></div>\n\n          <!-- SVG Student Illustration (BHM — hotel/hospitality the" +
                    "me) -->\n          <svg class=\"student-fig\" viewBox=\"0 0 240 280\" fill=\"none\" xml" +
                    "ns=\"http://www.w3.org/2000/svg\">\n            <!-- body / uniform -->\n           " +
                    " <rect x=\"68\" y=\"155\" width=\"104\" height=\"125\" rx=\"14\" fill=\"#1a2e6e\"/>\n        " +
                    "    <rect x=\"108\" y=\"155\" width=\"24\" height=\"80\" rx=\"4\" fill=\"#0B1F66\"/>\n       " +
                    "     <!-- bow tie -->\n            <polygon points=\"120,162 113,168 120,174 127,1" +
                    "68\" fill=\"#FF2D8D\"/>\n            <!-- jacket lapels -->\n            <polygon poi" +
                    "nts=\"108,155 120,175 132,155 118,160\" fill=\"white\" opacity=\"0.9\"/>\n            <" +
                    "polygon points=\"132,155 120,175 108,155 122,160\" fill=\"#e0e4f0\" opacity=\"0.9\"/>\n" +
                    "            <!-- arms -->\n            <rect x=\"38\" y=\"158\" width=\"36\" height=\"92" +
                    "\" rx=\"14\" fill=\"#1a2e6e\"/>\n            <rect x=\"166\" y=\"158\" width=\"36\" height=\"" +
                    "92\" rx=\"14\" fill=\"#1a2e6e\"/>\n            <!-- hands -->\n            <ellipse cx=" +
                    "\"56\" cy=\"256\" rx=\"16\" ry=\"12\" fill=\"#f5c5a3\"/>\n            <ellipse cx=\"184\" cy=" +
                    "\"253\" rx=\"16\" ry=\"12\" fill=\"#f5c5a3\"/>\n            <!-- serving tray held in rig" +
                    "ht hand -->\n            <ellipse cx=\"196\" cy=\"232\" rx=\"28\" ry=\"6\" fill=\"#d4af37\"" +
                    " opacity=\"0.9\"/>\n            <ellipse cx=\"196\" cy=\"230\" rx=\"24\" ry=\"4\" fill=\"#f5" +
                    "c542\"/>\n            <!-- cloche / dome on tray -->\n            <ellipse cx=\"196\"" +
                    " cy=\"228\" rx=\"16\" ry=\"3\" fill=\"#e8e8e8\"/>\n            <path d=\"M180 228 Q180 210" +
                    " 196 208 Q212 210 212 228Z\" fill=\"#f0f0f0\"/>\n            <ellipse cx=\"196\" cy=\"2" +
                    "08\" rx=\"3\" ry=\"2\" fill=\"#d4af37\"/>\n            <!-- neck -->\n            <rect x" +
                    "=\"108\" y=\"132\" width=\"24\" height=\"28\" rx=\"8\" fill=\"#f5c5a3\"/>\n            <!-- h" +
                    "ead -->\n            <ellipse cx=\"120\" cy=\"110\" rx=\"46\" ry=\"50\" fill=\"#f5c5a3\"/>\n" +
                    "            <!-- hair -->\n            <path d=\"M74 96 Q76 52 120 50 Q164 52 166 " +
                    "96 Q155 72 120 70 Q85 72 74 96Z\" fill=\"#2d1a08\"/>\n            <ellipse cx=\"120\" " +
                    "cy=\"55\" rx=\"20\" ry=\"14\" fill=\"#2d1a08\"/>\n            <!-- chef/hotel hat -->\n   " +
                    "         <rect x=\"88\" y=\"56\" width=\"64\" height=\"18\" rx=\"4\" fill=\"white\"/>\n      " +
                    "      <rect x=\"94\" y=\"38\" width=\"52\" height=\"22\" rx=\"8\" fill=\"white\"/>\n         " +
                    "   <rect x=\"88\" y=\"54\" width=\"64\" height=\"6\" rx=\"2\" fill=\"#e8e8e8\"/>\n           " +
                    " <!-- facial features -->\n            <ellipse cx=\"108\" cy=\"114\" rx=\"6\" ry=\"7\" f" +
                    "ill=\"white\"/>\n            <ellipse cx=\"132\" cy=\"114\" rx=\"6\" ry=\"7\" fill=\"white\"/" +
                    ">\n            <ellipse cx=\"109\" cy=\"115\" rx=\"3.5\" ry=\"4\" fill=\"#1a0a0a\"/>\n      " +
                    "      <ellipse cx=\"133\" cy=\"115\" rx=\"3.5\" ry=\"4\" fill=\"#1a0a0a\"/>\n            <e" +
                    "llipse cx=\"110\" cy=\"114\" rx=\"1.5\" ry=\"2\" fill=\"white\"/>\n            <ellipse cx=" +
                    "\"134\" cy=\"114\" rx=\"1.5\" ry=\"2\" fill=\"white\"/>\n            <path d=\"M112 128 Q120" +
                    " 135 128 128\" stroke=\"#c27a5a\" stroke-width=\"2\" fill=\"none\" stroke-linecap=\"roun" +
                    "d\"/>\n            <path d=\"M102 107 Q108 104 114 106\" stroke=\"#2d1a08\" stroke-wid" +
                    "th=\"2.5\" fill=\"none\" stroke-linecap=\"round\"/>\n            <path d=\"M126 106 Q132" +
                    " 104 138 107\" stroke=\"#2d1a08\" stroke-width=\"2.5\" fill=\"none\" stroke-linecap=\"ro" +
                    "und\"/>\n            <!-- notepad in left hand -->\n            <rect x=\"66\" y=\"218" +
                    "\" width=\"26\" height=\"34\" rx=\"3\" fill=\"#fff8e7\" stroke=\"#d4af37\" stroke-width=\"1." +
                    "5\"/>\n            <rect x=\"70\" y=\"224\" width=\"18\" height=\"2\" rx=\"1\" fill=\"#d4af37" +
                    "\" opacity=\"0.6\"/>\n            <rect x=\"70\" y=\"229\" width=\"14\" height=\"2\" rx=\"1\" " +
                    "fill=\"#d4af37\" opacity=\"0.5\"/>\n            <rect x=\"70\" y=\"234\" width=\"16\" heigh" +
                    "t=\"2\" rx=\"1\" fill=\"#d4af37\" opacity=\"0.4\"/>\n            <rect x=\"70\" y=\"239\" wid" +
                    "th=\"12\" height=\"2\" rx=\"1\" fill=\"#d4af37\" opacity=\"0.3\"/>\n          </svg>\n\n     " +
                    "     <!-- Floating badges — BHM specific -->\n          <div class=\"ilu-badge ib-" +
                    "1\">\n            <div class=\"ib-icon blue\">🏨</div>\n            <div class=\"ib-tx" +
                    "t\">\n              <strong>5-Star Hotel Lab</strong>\n              <span>Live kit" +
                    "chen & front desk</span>\n            </div>\n          </div>\n\n          <div cla" +
                    "ss=\"ilu-badge ib-2\">\n            <div class=\"ib-icon pink\">🍽️</div>\n           " +
                    " <div class=\"ib-txt\">\n              <strong>F&B Training Kitchen</strong>\n      " +
                    "        <span>Culinary arts facility</span>\n            </div>\n          </div>\n" +
                    "\n          <div class=\"ilu-badge ib-3\">\n            <div class=\"ib-icon green\">💼" +
                    "</div>\n            <div class=\"ib-txt\">\n              <strong>92% Placement</st" +
                    "rong>\n              <span>2024 cohort</span>\n            </div>\n          </div>" +
                    "\n        </div>\n      </div>\n    </div>\n\n    <!-- ABOUT THE PROGRAM -->\n    <div" +
                    " class=\"about-section fade-up d2\" id=\"coursesSection\">\n      <div class=\"about-l" +
                    "eft\">\n        <div class=\"about-label\">About the Program</div>\n        <h2 class" +
                    "=\"about-heading\">Nepal\'s Premier <span>BHM Degree</span></h2>\n\n        <p class=" +
                    "\"about-para\">\n          The <strong>Bachelor of Hotel Management (BHM)</strong> " +
                    "at Texas College of Management and IT (TCMIT) is a 4-year, 8-semester program af" +
                    "filiated with <strong>Lincoln University College, Malaysia</strong>.\n          D" +
                    "esigned to blend hospitality theory with practical execution, the program covers" +
                    " front office operations, food & beverage management, housekeeping, event manage" +
                    "ment, tourism, and hotel marketing.\n          With modern facilities including a" +
                    " fully equipped Training Kitchen, Mock Hotel Front Desk, and Restaurant & Bar La" +
                    "b, students gain hands-on experience to graduate completely career-ready.\n      " +
                    "  </p>\n        <p class=\"about-para\">\n          To ensure graduates are industry" +
                    "-ready from day one, Texas College integrates structured After-Class Professiona" +
                    "l Classes directly into the academic timeline.\n          With dedicated F&amp;B " +
                    "and Front Office labs, an Incubation Center, and a state-of-the-art e-library, s" +
                    "tudents gain hands-on experience managing real-world hospitality operations.\n   " +
                    "       Industry training, live project work, and globally recognised certificati" +
                    "ons ensure graduates are career-ready for hotel management roles in Nepal and ar" +
                    "ound the world.\n        </p>\n        <p class=\"about-para\">\n          Alongside " +
                    "this core hospitality track, the student journey includes specialized profession" +
                    "al training to make them globally competitive.\n          Students engage in Cert" +
                    "ified Hospitality Supervisor (CHS) preparation, Revenue &amp; Property Managemen" +
                    "t System workshops, event planning simulations, and cross-cultural communication" +
                    " training.\n          Finally, they achieve production-ready expertise in Hotel T" +
                    "echnology Systems and Global Distribution Systems (GDS).\n        </p>\n\n        <" +
                    "div class=\"about-btns\"></div>\n      </div>\n\n      <div class=\"about-right\">\n    " +
                    "    <div class=\"poster-wrap\">\n          <div class=\"poster-card\">\n            <d" +
                    "iv class=\"poster-inner\">\n              <div class=\"poster-logos\">\n              " +
                    "  <div class=\"poster-logo-tx\">\n                  <div class=\"tx-text-wrap\">\n    " +
                    "                <span class=\"tx-name\">Texas</span>\n                    <span cla" +
                    "ss=\"tx-sub\">College of Management &amp; IT</span>\n                  </div>\n     " +
                    "           </div>\n                <div class=\"poster-logo-luc\">\n                " +
                    "  <div class=\"luc-seal\">LUC</div>\n                  <span class=\"luc-name\">LINCO" +
                    "LN<br>UNIVERSITY<br>COLLEGE</span>\n                </div>\n              </div>\n\n" +
                    "              <div class=\"poster-tagline\">CRAFT EXCEPTIONAL EXPERIENCES</div>\n  " +
                    "            <div class=\"poster-main-title\">WITH<br>HOTEL MANAGEMENT</div>\n      " +
                    "        <div class=\"poster-degree-row\">\n                <div class=\"poster-degre" +
                    "e-title\">BHM</div>\n              </div>\n              <div class=\"poster-degree-" +
                    "sub\">Bachelor of (Hons.) in<br><strong>Hotel Management</strong></div>\n\n        " +
                    "      <div class=\"poster-why-box\">\n                <div class=\"pwb-title\">Discov" +
                    "er <span>BHM</span><br>at Texas</div>\n                <div class=\"pwb-item\">▶ 5-" +
                    "Star Training Hotel Lab</div>\n                <div class=\"pwb-item\">▶ F&amp;B Pr" +
                    "oduction Kitchen</div>\n                <div class=\"pwb-item\">▶ Mock Front Desk S" +
                    "tudio</div>\n                <div class=\"pwb-item\">▶ Resourceful Library &amp; eb" +
                    "rary</div>\n                <div class=\"pwb-item\">▶ Hospitality Incubation Center" +
                    "</div>\n              </div>\n\n              <div class=\"poster-admission\">\n      " +
                    "          <div class=\"pa-open\">ADMISSION<br>OPEN 2026</div>\n              </div>" +
                    "\n\n              <!-- Poster student SVG (BHM — hotel uniform with tray) -->\n    " +
                    "          <div class=\"poster-student\">\n                <svg viewBox=\"0 0 160 270" +
                    "\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\" width=\"155\" height=\"270\">\n     " +
                    "             <rect x=\"38\" y=\"125\" width=\"84\" height=\"145\" rx=\"12\" fill=\"#1e3a8a\"" +
                    "/>\n                  <rect x=\"72\" y=\"125\" width=\"16\" height=\"70\" rx=\"3\" fill=\"#1" +
                    "a2e6e\"/>\n                  <!-- bow tie -->\n                  <polygon points=\"8" +
                    "0,131 74,136 80,141 86,136\" fill=\"#FF2D8D\"/>\n                  <polygon points=\"" +
                    "72,125 80,142 88,125 79,129\" fill=\"white\" opacity=\"0.85\"/>\n                  <re" +
                    "ct x=\"16\" y=\"128\" width=\"28\" height=\"84\" rx=\"12\" fill=\"#1e3a8a\"/>\n              " +
                    "    <rect x=\"116\" y=\"128\" width=\"28\" height=\"84\" rx=\"12\" fill=\"#1e3a8a\"/>\n      " +
                    "            <ellipse cx=\"30\" cy=\"218\" rx=\"13\" ry=\"10\" fill=\"#f5c5a3\"/>\n         " +
                    "         <ellipse cx=\"130\" cy=\"216\" rx=\"13\" ry=\"10\" fill=\"#f5c5a3\"/>\n           " +
                    "       <!-- tray in right hand -->\n                  <ellipse cx=\"138\" cy=\"200\" " +
                    "rx=\"22\" ry=\"5\" fill=\"#d4af37\" opacity=\"0.9\"/>\n                  <ellipse cx=\"138" +
                    "\" cy=\"198\" rx=\"18\" ry=\"3.5\" fill=\"#f5c542\"/>\n                  <path d=\"M120 198" +
                    " Q120 183 138 181 Q156 183 156 198Z\" fill=\"#f0f0f0\"/>\n                  <ellipse" +
                    " cx=\"138\" cy=\"181\" rx=\"2.5\" ry=\"1.5\" fill=\"#d4af37\"/>\n                  <!-- not" +
                    "epad left hand -->\n                  <rect x=\"18\" y=\"202\" width=\"22\" height=\"28\"" +
                    " rx=\"3\" fill=\"#fff8e7\" stroke=\"#d4af37\" stroke-width=\"1.5\"/>\n                  <" +
                    "rect x=\"22\" y=\"208\" width=\"14\" height=\"2\" rx=\"1\" fill=\"#d4af37\" opacity=\"0.6\"/>\n" +
                    "                  <rect x=\"22\" y=\"213\" width=\"10\" height=\"2\" rx=\"1\" fill=\"#d4af3" +
                    "7\" opacity=\"0.5\"/>\n                  <rect x=\"22\" y=\"218\" width=\"12\" height=\"2\" " +
                    "rx=\"1\" fill=\"#d4af37\" opacity=\"0.4\"/>\n                  <rect x=\"72\" y=\"103\" wid" +
                    "th=\"16\" height=\"26\" rx=\"7\" fill=\"#f5c5a3\"/>\n                  <ellipse cx=\"80\" c" +
                    "y=\"82\" rx=\"36\" ry=\"40\" fill=\"#f5c5a3\"/>\n                  <path d=\"M44 72 Q46 34" +
                    " 80 32 Q114 34 116 72 Q106 50 80 52 Q54 50 44 72Z\" fill=\"#2d1a08\"/>\n            " +
                    "      <ellipse cx=\"80\" cy=\"36\" rx=\"18\" ry=\"12\" fill=\"#2d1a08\"/>\n                " +
                    "  <!-- hotel hat -->\n                  <rect x=\"54\" y=\"44\" width=\"52\" height=\"14" +
                    "\" rx=\"3\" fill=\"white\"/>\n                  <rect x=\"60\" y=\"30\" width=\"40\" height=" +
                    "\"18\" rx=\"6\" fill=\"white\"/>\n                  <rect x=\"54\" y=\"42\" width=\"52\" heig" +
                    "ht=\"5\" rx=\"2\" fill=\"#e8e8e8\"/>\n                  <ellipse cx=\"68\" cy=\"86\" rx=\"5." +
                    "5\" ry=\"6.5\" fill=\"white\"/>\n                  <ellipse cx=\"92\" cy=\"86\" rx=\"5.5\" r" +
                    "y=\"6.5\" fill=\"white\"/>\n                  <ellipse cx=\"69\" cy=\"87\" rx=\"3.2\" ry=\"3" +
                    ".8\" fill=\"#1a0a0a\"/>\n                  <ellipse cx=\"93\" cy=\"87\" rx=\"3.2\" ry=\"3.8" +
                    "\" fill=\"#1a0a0a\"/>\n                  <ellipse cx=\"70\" cy=\"86\" rx=\"1.3\" ry=\"1.6\" " +
                    "fill=\"white\"/>\n                  <ellipse cx=\"94\" cy=\"86\" rx=\"1.3\" ry=\"1.6\" fill" +
                    "=\"white\"/>\n                  <path d=\"M73 100 Q80 107 87 100\" stroke=\"#c27a5a\" s" +
                    "troke-width=\"1.8\" fill=\"none\" stroke-linecap=\"round\"/>\n                  <path d" +
                    "=\"M62 78 Q68 75 74 77\" stroke=\"#2d1a08\" stroke-width=\"2\" fill=\"none\" stroke-line" +
                    "cap=\"round\"/>\n                  <path d=\"M86 77 Q92 75 98 78\" stroke=\"#2d1a08\" s" +
                    "troke-width=\"2\" fill=\"none\" stroke-linecap=\"round\"/>\n                </svg>\n    " +
                    "          </div>\n\n              <div class=\"poster-footer\">\n                <div" +
                    " class=\"pf-item\">📍 Sifal, Chabahil, Kathmandu</div>\n                <div class=" +
                    "\"pf-item\">📞 01-4589134 | 9801644458</div>\n                <div class=\"pf-item\">" +
                    "🌐 www.texascollege.edu.np</div>\n              </div>\n            </div>\n       " +
                    "   </div>\n          <div class=\"poster-glow\"></div>\n        </div>\n      </div>\n" +
                    "    </div>\n\n    <!-- AFFILIATION BANNER -->\n    <div class=\"affil-banner fade-up" +
                    " d4\">\n      <div class=\"affil-left\">\n        <div class=\"affil-label\">Affiliated" +
                    " with</div>\n        <div class=\"affil-name\">Lincoln University <span>College</sp" +
                    "an></div>\n        <div class=\"affil-sub\">Petaling Jaya, Malaysia · Est. 2002</di" +
                    "v>\n      </div>\n\n      <div class=\"affil-divider\"></div>\n\n      <div class=\"affi" +
                    "l-pills\">\n        <div class=\"apill\"><span class=\"apill-icon\">✅</span> MQA Accre" +
                    "dited</div>\n        <div class=\"apill\"><span class=\"apill-icon\">🎓</span> TU Equ" +
                    "ivalent</div>\n        <div class=\"apill\"><span class=\"apill-icon\">📜</span> MoE " +
                    "Approved</div>\n        <div class=\"apill\"><span class=\"apill-icon\">🌏</span> Glo" +
                    "bally Recognised</div>\n        <div class=\"apill\"><span class=\"apill-icon\">🏆</s" +
                    "pan> Top-ranked College</div>\n      </div>\n\n      <div class=\"affil-right\">\n    " +
                    "    <a href=\"https://www.lincoln.edu.my\" target=\"_blank\" rel=\"noopener noreferre" +
                    "r\" class=\"btn-learn\" style=\"text-decoration: none; display: inline-flex; align-i" +
                    "tems: center; gap: 8px;\">\n          Learn More\n          <svg width=\"13\" height=" +
                    "\"13\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\" viewBox=\"0 0 24 24\">\n " +
                    "           <path d=\"M18 13v6a2 2 0 01-2 2H5a2 2 0 01-2-2V8a2 2 0 012-2h6\"/>\n    " +
                    "        <polyline points=\"15 3 21 3 21 9\"/>\n            <line x1=\"10\" y1=\"14\" x2" +
                    "=\"21\" y2=\"3\"/>\n          </svg>\n        </a>\n      </div>\n    </div>\n\n  </div>\n<" +
                    "/main>\n\n<script>\nconst semesterData = [\n    { label: \"First Sem\", icon: \"1️⃣\", s" +
                    "ubjects: [\"Foundations of Hospitality\", \"Hotel Operations\", \"Food & Beverage I\"," +
                    " \"Communication Skills\", \"Business Maths\"] },\n    { label: \"Second Sem\", icon: \"" +
                    "2️⃣\", subjects: [\"Front Office Management\", \"Housekeeping Management\", \"F&B Serv" +
                    "ice II\", \"Principles of Tourism\", \"Accounting for Hotels\"] },\n    { label: \"Thir" +
                    "d Sem\", icon: \"3️⃣\", subjects: [\"Hotel Marketing\", \"Revenue Management\", \"Culina" +
                    "ry Arts I\", \"Event Management\", \"Human Resource Management\"] },\n    { label: \"Fo" +
                    "urth Sem\", icon: \"4️⃣\", subjects: [\"Hotel Financial Management\", \"Culinary Arts " +
                    "II\", \"Rooms Division Management\", \"Travel & Tourism Management\", \"Strategic Mana" +
                    "gement\"] },\n    { label: \"Fifth Sem\", icon: \"5️⃣\", subjects: [\"Resort & Spa Mana" +
                    "gement\", \"Food Safety & Hygiene\", \"Digital Marketing for Hotels\", \"Convention & " +
                    "MICE\", \"Property Management Systems\"] },\n    { label: \"Sixth Sem\", icon: \"6️⃣\", " +
                    "subjects: [\"Hospitality Law & Ethics\", \"Global Distribution Systems\", \"Sustainab" +
                    "le Tourism\", \"Entrepreneurship\", \"Research Methods\"] },\n    { label: \"Seventh Se" +
                    "m\", icon: \"7️⃣\", subjects: [\"Capstone Project\", \"Internship\", \"Elective I\", \"Ele" +
                    "ctive II\", \"Advanced Hospitality Topics\"] },\n    { label: \"Eighth Sem\", icon: \"8" +
                    "️⃣\", subjects: [\"Final Project\", \"Dissertation\", \"Viva Voce\", \"Elective III\"] }," +
                    "\n];\n\nconst menu = document.getElementById(\'semMenu\');\nsemesterData.forEach((sem," +
                    " i) => {\n    const el = document.createElement(\'div\');\n    el.className = \'sem-i" +
                    "tem\' + (i === 0 ? \' open\' : \'\');\n    el.innerHTML = `\n      <div class=\"sem-head" +
                    "er${i === 0 ? \' active\' : \'\'}\" onclick=\"toggleSem(this)\">\n        <div class=\"se" +
                    "m-icon\">${sem.icon}</div>\n        <span class=\"sem-label\">${sem.label}</span>\n  " +
                    "      <svg class=\"sem-chevron\" width=\"13\" height=\"13\" fill=\"none\" stroke=\"curren" +
                    "tColor\" stroke-width=\"2.5\" viewBox=\"0 0 24 24\"><path d=\"M19 9l-7 7-7-7\"/></svg>\n" +
                    "      </div>\n      <div class=\"sem-subjects\">\n        ${sem.subjects.map((s, j) " +
                    "=> `<div class=\"subject-link${i === 0 && j === 0 ? \' active\' : \'\'}\" onclick=\"pic" +
                    "kSubject(this)\"><div class=\"subject-dot\"></div>${s}</div>`).join(\'\')}\n      </di" +
                    "v>`;\n    menu?.appendChild(el);\n});\n\nfunction toggleSem(el) {\n    el.parentEleme" +
                    "nt.classList.toggle(\'open\');\n}\n\nfunction pickSubject(el) {\n    document.querySel" +
                    "ectorAll(\'.subject-link\').forEach(l => l.classList.remove(\'active\'));\n    el.cla" +
                    "ssList.add(\'active\');\n    if (window.innerWidth < 900) closeSidebar();\n}\n\nfuncti" +
                    "on scrollToCourses() {\n    document.getElementById(\'coursesSection\')?.scrollInto" +
                    "View({ behavior: \'smooth\', block: \'start\' });\n}\n\nfunction closeSidebar() {\n    d" +
                    "ocument.getElementById(\'sidebar\')?.classList.remove(\'open\');\n    document.getEle" +
                    "mentById(\'overlay\')?.classList.remove(\'show\');\n}\n</script>\n\n");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        253,
                        39341,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.WebTools.BrowserLink.Runtime.WebForms.TraceHelpers, Microsoft.WebTools." +
                    "BrowserLink.Tracing, Version=18.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f1" +
                    "1d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.bhm_notes_dash_aspx.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.bhm_notes_dash_aspx.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent1(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 2 "D:\Learningportal\Learning-System\Bhm_Notes\dash.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 2 "D:\Learningportal\Learning-System\Bhm_Notes\dash.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(bhm_notes_dash_aspx @__ctrl) {
            
            #line 1 "D:\Learningportal\Learning-System\Bhm_Notes\dash.aspx"
            @__ctrl.Title = "";
            
            #line default
            #line hidden
            
            #line 1 "D:\Learningportal\Learning-System\Bhm_Notes\dash.aspx"
            @__ctrl.MasterPageFile = "~/Bhm_Notes/note.Master";
            
            #line default
            #line hidden
            
            #line 1 "D:\Learningportal\Learning-System\Bhm_Notes\dash.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 2 "D:\Learningportal\Learning-System\Bhm_Notes\dash.aspx"
            this.AddContentTemplate("ContentPlaceHolder1", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent1)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "D:\Learningportal\Learning-System\Bhm_Notes\dash.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n\r\n"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.bhm_notes_dash_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -1005266328;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
