#pragma checksum "D:\Learningportal\Learning-System\Bba_Notes\dash.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "2BA31CEB4039F88F6EDFBE316783975DC2D5D1D9"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    
    #line 2 "D:\Learningportal\Learning-System\Bba_Notes\dash.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 325 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 331 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 338 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 2 "D:\Learningportal\Learning-System\Bba_Notes\dash.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 326 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 330 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 1 "D:\Learningportal\Learning-System\Bba_Notes\dash.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 336 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 329 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 333 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 2 "D:\Learningportal\Learning-System\Bba_Notes\dash.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 334 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 2 "D:\Learningportal\Learning-System\Bba_Notes\dash.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 328 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 337 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 2 "D:\Learningportal\Learning-System\Bba_Notes\dash.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 332 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 327 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 343 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 342 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class bba_notes_dash_aspx : global::Learning_System.Bba_Notes.dash, System.Web.SessionState.IRequiresSessionState, System.Web.IHttpHandler {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.bba_notes_dash_aspx.@__PageInspector_LoadHelper("SetTraceData");
        
        private static bool @__initialized;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bba_notes_dash_aspx() {
            string[] dependencies;
            ((global::Learning_System.Bba_Notes.dash)(this)).AppRelativeVirtualPath = "~/Bba_Notes/dash.aspx";
            if ((global::ASP.bba_notes_dash_aspx.@__initialized == false)) {
                dependencies = new string[2];
                dependencies[0] = "~/Bba_Notes/dash.aspx";
                dependencies[1] = "~/Bba_Notes/note.Master";
                global::ASP.bba_notes_dash_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.bba_notes_dash_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(this.Context.ApplicationInstance));
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n<style>\r\n  :root {\r\n    --primary: #0B1F66;\r\n    --secondary: #081547;\r\n    -" +
                    "-pink: #FF2D8D;\r\n    --pink-dark: #d4206e;\r\n    --pink-glow: rgba(255,45,141,0.2" +
                    "2);\r\n    --pink-soft: rgba(255,45,141,0.1);\r\n    --bg: #f0f3fc;\r\n    --bg-card: " +
                    "#ffffff;\r\n    --text-primary: #0B1F66;\r\n    --text-secondary: #5a6a99;\r\n    --te" +
                    "xt-light: #a0aec8;\r\n    --border: rgba(11,31,102,0.1);\r\n    --border-pink: rgba(" +
                    "255,45,141,0.18);\r\n    --shadow-sm: 0 2px 12px rgba(8,21,71,0.07);\r\n    --shadow" +
                    "-md: 0 8px 32px rgba(8,21,71,0.13);\r\n    --shadow-lg: 0 20px 60px rgba(8,21,71,0" +
                    ".2);\r\n    --radius: 18px;\r\n    --radius-sm: 10px;\r\n    --sidebar-w: 265px;\r\n    " +
                    "--header-h: 68px;\r\n    --ease: 0.28s cubic-bezier(0.4,0,0.2,1);\r\n  }\r\n\r\n  *, *::" +
                    "before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\r\n\r\n  body {\r" +
                    "\n    font-family: \'DM Sans\', sans-serif;\r\n    background: var(--bg);\r\n    color:" +
                    " var(--text-primary);\r\n    min-height: 100vh;\r\n    overflow-x: hidden;\r\n  }\r\n\r\n " +
                    " ::-webkit-scrollbar { width: 5px; }\r\n  ::-webkit-scrollbar-track { background: " +
                    "transparent; }\r\n  ::-webkit-scrollbar-thumb { background: rgba(11,31,102,0.15); " +
                    "border-radius: 4px; }\r\n\r\n  /* ══ HEADER ══ */\r\n  header {\r\n    position: fixed; " +
                    "top: 0; left: 0; right: 0; z-index: 200;\r\n    height: var(--header-h);\r\n    back" +
                    "ground: rgba(255,255,255,0.92);\r\n    backdrop-filter: blur(20px);\r\n    -webkit-b" +
                    "ackdrop-filter: blur(20px);\r\n    border-bottom: 1px solid var(--border);\r\n    di" +
                    "splay: flex; align-items: center;\r\n    padding: 0 28px 0 0;\r\n    box-shadow: 0 2" +
                    "px 24px rgba(8,21,71,0.07);\r\n  }\r\n\r\n  .header-logo {\r\n    width: var(--sidebar-w" +
                    ");\r\n    display: flex; align-items: center; justify-content: center;\r\n    paddin" +
                    "g: 0 20px;\r\n    border-right: 1px solid var(--border);\r\n    height: 100%;\r\n    f" +
                    "lex-shrink: 0;\r\n    gap: 10px;\r\n  }\r\n\r\n  .logo-mark {\r\n    width: 36px; height: " +
                    "36px;\r\n    background: linear-gradient(135deg, var(--primary), var(--pink));\r\n  " +
                    "  border-radius: 10px;\r\n    display: flex; align-items: center; justify-content:" +
                    " center;\r\n    font-family: \'Sora\', sans-serif;\r\n    font-weight: 800; font-size:" +
                    " 14px; color: white;\r\n    flex-shrink: 0;\r\n  }\r\n\r\n  .logo-text { display: flex; " +
                    "flex-direction: column; }\r\n  .logo-text strong { font-family: \'Sora\', sans-serif" +
                    "; font-size: 14px; font-weight: 800; color: var(--primary); line-height: 1.1; }\r" +
                    "\n  .logo-text span { font-size: 10px; color: var(--text-light); letter-spacing: " +
                    "0.3px; }\r\n\r\n  .header-center { flex: 1; display: flex; align-items: center; padd" +
                    "ing: 0 28px; gap: 16px; }\r\n\r\n  .page-title {\r\n    font-family: \'Sora\', sans-seri" +
                    "f;\r\n    font-size: 15px; font-weight: 700;\r\n    color: var(--primary);\r\n    lett" +
                    "er-spacing: -0.2px;\r\n    white-space: nowrap;\r\n    display: flex; align-items: c" +
                    "enter; gap: 8px;\r\n  }\r\n  .page-title .tag {\r\n    font-size: 10px; font-weight: 7" +
                    "00;\r\n    background: var(--pink); color: white;\r\n    padding: 3px 9px; border-ra" +
                    "dius: 50px;\r\n    letter-spacing: 0.4px; font-family: \'Sora\', sans-serif;\r\n  }\r\n\r" +
                    "\n  .search-bar {\r\n    display: flex; align-items: center; gap: 10px;\r\n    backgr" +
                    "ound: var(--bg); border: 1.5px solid var(--border);\r\n    border-radius: 50px; pa" +
                    "dding: 9px 18px;\r\n    max-width: 340px; width: 100%; transition: var(--ease);\r\n " +
                    " }\r\n  .search-bar:focus-within { border-color: var(--pink); box-shadow: 0 0 0 4p" +
                    "x var(--pink-glow); background: white; }\r\n  .search-bar svg { color: var(--text-" +
                    "light); flex-shrink: 0; }\r\n  .search-bar input { border: none; background: trans" +
                    "parent; font-family: \'DM Sans\', sans-serif; font-size: 13.5px; color: var(--text" +
                    "-primary); outline: none; width: 100%; }\r\n  .search-bar input::placeholder { col" +
                    "or: var(--text-light); }\r\n\r\n  .header-actions { display: flex; align-items: cent" +
                    "er; gap: 8px; }\r\n\r\n  .icon-btn {\r\n    width: 38px; height: 38px; border-radius: " +
                    "10px;\r\n    border: 1.5px solid var(--border); background: white;\r\n    display: f" +
                    "lex; align-items: center; justify-content: center;\r\n    cursor: pointer; transit" +
                    "ion: var(--ease); color: var(--text-secondary); position: relative;\r\n  }\r\n  .ico" +
                    "n-btn:hover { background: var(--bg); border-color: var(--pink); color: var(--pin" +
                    "k); }\r\n\r\n  .notif-dot { position: absolute; top: 8px; right: 8px; width: 7px; he" +
                    "ight: 7px; background: var(--pink); border-radius: 50%; border: 2px solid white;" +
                    " }\r\n\r\n  .avatar {\r\n    width: 38px; height: 38px; border-radius: 50%;\r\n    backg" +
                    "round: linear-gradient(135deg, var(--primary), var(--pink));\r\n    display: flex;" +
                    " align-items: center; justify-content: center;\r\n    font-family: \'Sora\', sans-se" +
                    "rif; font-weight: 700; font-size: 13px; color: white;\r\n    cursor: pointer; box-" +
                    "shadow: 0 2px 10px var(--pink-glow); border: 2px solid white;\r\n  }\r\n\r\n  /* ══ SI" +
                    "DEBAR ══ */\r\n  .sidebar {\r\n    position: fixed; left: 0; top: var(--header-h);\r\n" +
                    "    width: var(--sidebar-w); height: calc(100vh - var(--header-h));\r\n    backgro" +
                    "und: var(--secondary); overflow-y: auto; overflow-x: hidden;\r\n    padding: 18px " +
                    "10px 24px; z-index: 150; transition: var(--ease);\r\n    border-right: 1px solid r" +
                    "gba(255,255,255,0.05);\r\n  }\r\n  .sidebar::-webkit-scrollbar { width: 3px; }\r\n  .s" +
                    "idebar::-webkit-scrollbar-thumb { background: rgba(255,255,255,0.08); border-rad" +
                    "ius: 3px; }\r\n\r\n  .sidebar-label { font-size: 10px; font-weight: 700; text-transf" +
                    "orm: uppercase; letter-spacing: 1.8px; color: rgba(255,255,255,0.28); padding: 4" +
                    "px 12px 10px; margin-top: 4px; }\r\n\r\n  .sem-item { margin-bottom: 1px; }\r\n\r\n  .se" +
                    "m-header {\r\n    display: flex; align-items: center; gap: 10px; padding: 9px 12px" +
                    ";\r\n    border-radius: var(--radius-sm); cursor: pointer; transition: var(--ease)" +
                    ";\r\n    color: rgba(255,255,255,0.58); font-size: 13px; font-weight: 500;\r\n    po" +
                    "sition: relative; user-select: none;\r\n  }\r\n  .sem-header:hover { background: rgb" +
                    "a(255,255,255,0.06); color: rgba(255,255,255,0.9); }\r\n  .sem-header.active { bac" +
                    "kground: rgba(255,45,141,0.16); color: white; }\r\n  .sem-header.active::before { " +
                    "content: \'\'; position: absolute; left: 0; top: 20%; bottom: 20%; width: 3px; bac" +
                    "kground: var(--pink); border-radius: 0 3px 3px 0; }\r\n\r\n  .sem-icon { width: 26px" +
                    "; height: 26px; background: rgba(255,255,255,0.07); border-radius: 7px; display:" +
                    " flex; align-items: center; justify-content: center; font-size: 12px; flex-shrin" +
                    "k: 0; transition: var(--ease); }\r\n  .sem-header.active .sem-icon { background: r" +
                    "gba(255,45,141,0.28); }\r\n\r\n  .sem-label { flex: 1; }\r\n  .sem-chevron { transitio" +
                    "n: var(--ease); opacity: 0.45; flex-shrink: 0; }\r\n  .sem-item.open .sem-chevron " +
                    "{ transform: rotate(180deg); opacity: 1; color: var(--pink); }\r\n\r\n  .sem-subject" +
                    "s { display: none; padding: 3px 0 3px 16px; }\r\n  .sem-item.open .sem-subjects { " +
                    "display: block; }\r\n\r\n  .subject-link {\r\n    display: flex; align-items: center; " +
                    "gap: 8px; padding: 7px 12px; border-radius: 8px;\r\n    font-size: 12.5px; color: " +
                    "rgba(255,255,255,0.4); cursor: pointer; transition: var(--ease);\r\n  }\r\n  .subjec" +
                    "t-link:hover { color: rgba(255,255,255,0.75); background: rgba(255,255,255,0.04)" +
                    "; }\r\n  .subject-link.active { color: var(--pink); background: rgba(255,45,141,0." +
                    "08); font-weight: 500; }\r\n  .subject-dot { width: 4px; height: 4px; border-radiu" +
                    "s: 50%; background: currentColor; flex-shrink: 0; }\r\n\r\n  .course-tabs { display:" +
                    " flex; gap: 6px; padding: 0 8px 14px; margin-bottom: 4px; }\r\n  .ctab {\r\n    flex" +
                    ": 1; padding: 7px 0; border-radius: 8px;\r\n    font-family: \'Sora\', sans-serif; f" +
                    "ont-size: 11px; font-weight: 700;\r\n    text-align: center; cursor: pointer; tran" +
                    "sition: var(--ease);\r\n    color: rgba(255,255,255,0.4); border: 1px solid rgba(2" +
                    "55,255,255,0.07);\r\n    background: rgba(255,255,255,0.04); letter-spacing: 0.3px" +
                    ";\r\n  }\r\n  .ctab.active { background: var(--pink); color: white; border-color: tr" +
                    "ansparent; box-shadow: 0 3px 12px rgba(255,45,141,0.4); }\r\n  .ctab:not(.active):" +
                    "hover { background: rgba(255,255,255,0.08); color: rgba(255,255,255,0.7); }\r\n\r\n " +
                    " /* ══ MAIN ══ */\r\n  .main { margin-left: var(--sidebar-w); padding-top: var(--h" +
                    "eader-h); min-height: 100vh; width: calc(100% - var(--sidebar-w)); }\r\n  .main-in" +
                    "ner { padding: 30px 36px; width: 100%; }\r\n\r\n  /* ══ HERO BANNER ══ */\r\n  .hero-b" +
                    "anner {\r\n    background: linear-gradient(135deg, #0B1F66 0%, #081547 100%);\r\n   " +
                    " border-radius: 24px; padding: 0; position: relative; overflow: hidden;\r\n    box" +
                    "-shadow: var(--shadow-lg); margin-bottom: 28px;\r\n    display: grid; grid-templat" +
                    "e-columns: 1fr 340px; min-height: 28px;\r\n  }\r\n  .hero-banner::before { content: " +
                    "\'\'; position: absolute; top: -100px; right: 280px; width: 420px; height: 420px; " +
                    "background: radial-gradient(circle, rgba(245,197,66,0.10) 0%, transparent 65%); " +
                    "pointer-events: none; }\r\n  .hero-banner::after { content: \'\'; position: absolute" +
                    "; bottom: -80px; left: 20%; width: 300px; height: 300px; background: radial-grad" +
                    "ient(circle, rgba(8,21,71,0.4) 0%, transparent 70%); pointer-events: none; }\r\n\r\n" +
                    "  .hero-shapes { position: absolute; inset: 0; pointer-events: none; overflow: h" +
                    "idden; }\r\n  .shape { position: absolute; border-radius: 50%; border: 1px solid r" +
                    "gba(255,255,255,0.07); }\r\n  .shape-1 { width: 200px; height: 200px; top: -60px; " +
                    "right: 300px; border-color: rgba(245,197,66,0.12); }\r\n  .shape-2 { width: 120px;" +
                    " height: 120px; bottom: -30px; right: 380px; border-color: rgba(255,255,255,0.06" +
                    "); }\r\n  .shape-3 { width: 60px; height: 60px; top: 40px; right: 440px; backgroun" +
                    "d: rgba(245,197,66,0.05); border: none; }\r\n\r\n  .hero-content { padding: 44px 44p" +
                    "x 40px; display: flex; flex-direction: column; justify-content: center; position" +
                    ": relative; z-index: 2; }\r\n\r\n  @keyframes pulse { 0%,100% { opacity: 1; transfor" +
                    "m: scale(1); } 50% { opacity: 0.5; transform: scale(0.8); } }\r\n\r\n  .hero-title {" +
                    " font-family: \'Sora\', sans-serif; font-size: 34px; font-weight: 800; color: whit" +
                    "e; line-height: 1.15; letter-spacing: -0.8px; margin-bottom: 10px; }\r\n  .hero-ti" +
                    "tle .highlight { color: #F5C542; }\r\n  .hero-title .separator { color: rgba(255,2" +
                    "55,255,0.25); font-weight: 300; margin: 0 8px; }\r\n\r\n  .hero-mini-stats { display" +
                    ": flex; gap: 0; margin-bottom: 30px; }\r\n  .hms-item { display: flex; flex-direct" +
                    "ion: column; gap: 2px; padding-right: 22px; }\r\n  .hms-item + .hms-item { padding" +
                    "-left: 22px; border-left: 1px solid rgba(255,255,255,0.1); }\r\n  .hms-val { font-" +
                    "family: \'Sora\', sans-serif; font-size: 24px; font-weight: 800; color: white; }\r\n" +
                    "  .hms-val span { color: #F5C542; font-size: 16px; }\r\n  .hms-lbl { font-size: 10" +
                    "px; font-weight: 600; color: rgba(255,255,255,0.38); text-transform: uppercase; " +
                    "letter-spacing: 0.9px; }\r\n\r\n  .btn-pink {\r\n    display: inline-flex; align-items" +
                    ": center; gap: 9px;\r\n    background: var(--pink); color: white;\r\n    font-family" +
                    ": \'Sora\', sans-serif; font-weight: 700; font-size: 13.5px;\r\n    padding: 12px 24" +
                    "px; border-radius: 12px; border: none; cursor: pointer;\r\n    transition: var(--e" +
                    "ase); box-shadow: 0 4px 20px rgba(255,45,141,0.45); letter-spacing: 0.2px;\r\n  }\r" +
                    "\n  .btn-pink:hover { background: var(--pink-dark); transform: translateY(-2px); " +
                    "box-shadow: 0 8px 28px rgba(255,45,141,0.55); }\r\n\r\n  .hero-visual { position: re" +
                    "lative; z-index: 2; display: flex; align-items: flex-end; justify-content: cente" +
                    "r; padding: 0 20px 0 0; overflow: hidden; }\r\n  .hero-illustration { width: 100%;" +
                    " height: 100%; display: flex; align-items: flex-end; justify-content: center; po" +
                    "sition: relative; }\r\n  .ilu-glow { position: absolute; bottom: 0; left: 50%; tra" +
                    "nsform: translateX(-50%); width: 260px; height: 120px; background: radial-gradie" +
                    "nt(ellipse, rgba(245,197,66,0.15) 0%, transparent 70%); pointer-events: none; }\r" +
                    "\n  .student-fig { width: 240px; height: 260px; position: relative; flex-shrink: " +
                    "0; }\r\n\r\n  .ilu-badge { position: absolute; background: white; border-radius: 14p" +
                    "x; padding: 9px 14px; box-shadow: 0 8px 28px rgba(8,21,71,0.22); display: flex; " +
                    "align-items: center; gap: 8px; white-space: nowrap; animation: float 3s ease-in-" +
                    "out infinite; }\r\n  .ilu-badge:nth-child(2) { animation-delay: 1.2s; }\r\n  .ilu-ba" +
                    "dge:nth-child(3) { animation-delay: 2.1s; }\r\n  @keyframes float { 0%,100% { tran" +
                    "sform: translateY(0); } 50% { transform: translateY(-6px); } }\r\n  .ib-1 { top: 3" +
                    "0px; left: -20px; }\r\n  .ib-2 { top: 110px; right: -24px; }\r\n  .ib-3 { bottom: 68" +
                    "px; left: -30px; }\r\n\r\n  .ib-icon { width: 30px; height: 30px; border-radius: 8px" +
                    "; display: flex; align-items: center; justify-content: center; font-size: 15px; " +
                    "flex-shrink: 0; }\r\n  .ib-icon.blue { background: rgba(11,31,102,0.1); }\r\n  .ib-i" +
                    "con.pink { background: rgba(255,45,141,0.1); }\r\n  .ib-icon.green { background: r" +
                    "gba(16,185,129,0.1); }\r\n  .ib-txt strong { font-family: \'Sora\', sans-serif; font" +
                    "-size: 12px; font-weight: 700; color: var(--primary); display: block; line-heigh" +
                    "t: 1.2; }\r\n  .ib-txt span { font-size: 10px; color: var(--text-secondary); }\r\n\r\n" +
                    "  /* ══ SECTIONS ══ */\r\n  .section-title { font-family: \'Sora\', sans-serif; font" +
                    "-size: 16px; font-weight: 700; color: var(--primary); display: flex; align-items" +
                    ": center; gap: 10px; }\r\n  .section-icon { width: 32px; height: 32px; border-radi" +
                    "us: 9px; background: var(--pink-soft); display: flex; align-items: center; justi" +
                    "fy-content: center; font-size: 15px; }\r\n\r\n  /* ══ AFFILIATION BANNER ══ */\r\n  .a" +
                    "ffil-banner {\r\n    background: linear-gradient(135deg, var(--secondary) 0%, var(" +
                    "--primary) 60%, #162077 100%);\r\n    border-radius: 20px; padding: 28px 36px; dis" +
                    "play: flex; align-items: center; gap: 32px;\r\n    position: relative; overflow: h" +
                    "idden; box-shadow: var(--shadow-md); margin-bottom: 28px;\r\n  }\r\n  .affil-banner:" +
                    ":before { content: \'\'; position: absolute; top: -60px; right: -60px; width: 260p" +
                    "x; height: 260px; background: radial-gradient(circle, rgba(255,45,141,0.15) 0%, " +
                    "transparent 65%); pointer-events: none; }\r\n\r\n  .affil-left { flex-shrink: 0; dis" +
                    "play: flex; flex-direction: column; gap: 4px; }\r\n  .affil-label { font-size: 10p" +
                    "x; font-weight: 700; color: rgba(255,255,255,0.4); text-transform: uppercase; le" +
                    "tter-spacing: 1.5px; font-family: \'Sora\', sans-serif; }\r\n  .affil-name { font-fa" +
                    "mily: \'Sora\', sans-serif; font-size: 20px; font-weight: 800; color: white; lette" +
                    "r-spacing: -0.3px; }\r\n  .affil-name span { color: var(--pink); }\r\n  .affil-sub {" +
                    " font-size: 12px; color: rgba(255,255,255,0.45); margin-top: 2px; }\r\n  .affil-di" +
                    "vider { width: 1px; height: 54px; background: rgba(255,255,255,0.12); flex-shrin" +
                    "k: 0; }\r\n  .affil-pills { display: flex; gap: 10px; flex-wrap: wrap; flex: 1; }\r" +
                    "\n  .apill { display: inline-flex; align-items: center; gap: 7px; background: rgb" +
                    "a(255,255,255,0.08); border: 1px solid rgba(255,255,255,0.12); border-radius: 10" +
                    "px; padding: 9px 14px; font-size: 12px; font-weight: 500; color: rgba(255,255,25" +
                    "5,0.75); transition: var(--ease); }\r\n  .apill:hover { background: rgba(255,255,2" +
                    "55,0.14); color: white; border-color: rgba(255,45,141,0.4); }\r\n  .apill-icon { f" +
                    "ont-size: 15px; }\r\n  .affil-right { flex-shrink: 0; }\r\n\r\n  .btn-learn { display:" +
                    " inline-flex; align-items: center; gap: 9px; background: white; color: var(--pri" +
                    "mary); font-family: \'Sora\', sans-serif; font-weight: 700; font-size: 13px; paddi" +
                    "ng: 12px 22px; border-radius: 12px; border: none; cursor: pointer; transition: v" +
                    "ar(--ease); box-shadow: 0 4px 16px rgba(0,0,0,0.12); white-space: nowrap; }\r\n  ." +
                    "btn-learn:hover { background: var(--pink); color: white; transform: translateY(-" +
                    "2px); box-shadow: 0 8px 24px rgba(255,45,141,0.4); }\r\n\r\n  /* ══ ABOUT SECTION ══" +
                    " */\r\n  .about-section { display: grid; grid-template-columns: 1fr 360px; gap: 32" +
                    "px; margin-bottom: 28px; align-items: start; }\r\n\r\n  .about-left { background: wh" +
                    "ite; border-radius: 22px; border: 1.5px solid var(--border); padding: 36px 38px " +
                    "32px; box-shadow: var(--shadow-sm); }\r\n  .about-label { font-size: 11px; font-we" +
                    "ight: 700; text-transform: uppercase; letter-spacing: 1.8px; color: var(--pink);" +
                    " font-family: \'Sora\', sans-serif; margin-bottom: 10px; }\r\n  .about-heading { fon" +
                    "t-family: \'Sora\', sans-serif; font-size: 26px; font-weight: 800; color: var(--pr" +
                    "imary); letter-spacing: -0.5px; line-height: 1.2; margin-bottom: 20px; }\r\n  .abo" +
                    "ut-heading span { color: #16a34a; }\r\n  .about-para { font-size: 14px; color: #37" +
                    "4151; line-height: 1.75; margin-bottom: 14px; }\r\n  .about-para strong { color: v" +
                    "ar(--primary); font-weight: 700; }\r\n  .about-para:last-of-type { margin-bottom: " +
                    "24px; }\r\n\r\n  .about-btns { display: flex; gap: 12px; flex-wrap: wrap; }\r\n\r\n  /* " +
                    "══ POSTER ══ */\r\n  .about-right { position: sticky; top: calc(var(--header-h) + " +
                    "20px); }\r\n  .poster-wrap { position: relative; }\r\n  .poster-glow { position: abs" +
                    "olute; bottom: -20px; left: 50%; transform: translateX(-50%); width: 280px; heig" +
                    "ht: 60px; background: radial-gradient(ellipse, rgba(255,45,141,0.25) 0%, transpa" +
                    "rent 70%); pointer-events: none; }\r\n  .poster-card { border-radius: 20px; overfl" +
                    "ow: hidden; box-shadow: 0 24px 64px rgba(8,21,71,0.28); position: relative; }\r\n\r" +
                    "\n  .poster-inner {\r\n    background: linear-gradient(160deg, #0047b3 0%, #0B1F66 " +
                    "35%, #081547 70%, #060e33 100%);\r\n    padding: 22px 20px 16px; position: relativ" +
                    "e; overflow: hidden; min-height: 520px;\r\n  }\r\n  .poster-inner::before { content:" +
                    " \'\'; position: absolute; top: -80px; right: -60px; width: 280px; height: 280px; " +
                    "background: radial-gradient(circle, rgba(255,45,141,0.15) 0%, transparent 65%); " +
                    "pointer-events: none; }\r\n  .poster-inner::after { content: \'\'; position: absolut" +
                    "e; top: 0; left: 0; right: 0; bottom: 0; background: url(\"data:image/svg+xml,%3C" +
                    "svg xmlns=\'http://www.w3.org/2000/svg\' width=\'60\' height=\'60\'%3E%3Cpath d=\'M30 0" +
                    " L60 30 L30 60 L0 30Z\' stroke=\'rgba(255,255,255,0.03)\' fill=\'none\'/%3E%3C/svg%3E" +
                    "\") repeat; pointer-events: none; }\r\n\r\n  .poster-logos { display: flex; align-ite" +
                    "ms: center; justify-content: space-between; margin-bottom: 18px; position: relat" +
                    "ive; z-index: 2; }\r\n  .poster-logo-tx { display: flex; align-items: center; gap:" +
                    " 7px; }\r\n  .tx-text-wrap { display: flex; flex-direction: column; }\r\n  .tx-name " +
                    "{ font-family: \'Sora\', sans-serif; font-size: 17px; font-weight: 900; color: whi" +
                    "te; letter-spacing: -0.3px; line-height: 1; }\r\n  .tx-sub { font-size: 8px; color" +
                    ": rgba(255,255,255,0.5); line-height: 1.2; }\r\n\r\n  .poster-logo-luc { display: fl" +
                    "ex; align-items: center; gap: 6px; }\r\n  .luc-seal { width: 28px; height: 28px; b" +
                    "order-radius: 50%; background: #c8102e; display: flex; align-items: center; just" +
                    "ify-content: center; font-family: \'Sora\', sans-serif; font-weight: 800; font-siz" +
                    "e: 8px; color: white; border: 2px solid rgba(255,255,255,0.3); flex-shrink: 0; }" +
                    "\r\n  .luc-name { font-size: 8px; font-weight: 700; color: rgba(255,255,255,0.75);" +
                    " line-height: 1.4; font-family: \'Sora\', sans-serif; letter-spacing: 0.3px; }\r\n\r\n" +
                    "  .poster-tagline { font-family: \'Sora\', sans-serif; font-size: 11px; font-weigh" +
                    "t: 600; color: rgba(255,255,255,0.65); letter-spacing: 1.5px; margin-bottom: 2px" +
                    "; position: relative; z-index: 2; }\r\n  .poster-main-title { font-family: \'Sora\'," +
                    " sans-serif; font-size: 30px; font-weight: 900; color: #00c8ff; line-height: 1.0" +
                    "5; letter-spacing: -0.5px; margin-bottom: 14px; position: relative; z-index: 2; " +
                    "}\r\n  .poster-degree-row { display: flex; align-items: center; gap: 12px; positio" +
                    "n: relative; z-index: 2; }\r\n  .poster-degree-title { font-family: \'Sora\', sans-s" +
                    "erif; font-size: 36px; font-weight: 900; color: white; letter-spacing: -1px; lin" +
                    "e-height: 1; position: relative; z-index: 2; }\r\n  .poster-degree-sub { font-size" +
                    ": 11px; color: rgba(255,255,255,0.6); line-height: 1.4; margin-bottom: 16px; pos" +
                    "ition: relative; z-index: 2; }\r\n  .poster-degree-sub strong { color: rgba(255,25" +
                    "5,255,0.9); }\r\n\r\n  .poster-why-box { background: rgba(255,255,255,0.08); border:" +
                    " 1px solid rgba(255,255,255,0.12); border-radius: 12px; padding: 14px 16px; marg" +
                    "in-bottom: 14px; position: relative; z-index: 2; max-width: 175px; }\r\n  .pwb-tit" +
                    "le { font-family: \'DM Sans\', sans-serif; font-size: 13px; color: rgba(255,255,25" +
                    "5,0.75); margin-bottom: 10px; line-height: 1.4; }\r\n  .pwb-title span { font-fami" +
                    "ly: \'Sora\', sans-serif; font-size: 16px; font-weight: 900; color: #00c8ff; }\r\n  " +
                    ".pwb-item { font-size: 11px; color: rgba(255,255,255,0.65); margin-bottom: 5px; " +
                    "display: flex; align-items: center; gap: 4px; }\r\n\r\n  .poster-admission { positio" +
                    "n: absolute; bottom: 50px; right: 16px; z-index: 3; text-align: right; }\r\n  .pa-" +
                    "open { font-family: \'Sora\', sans-serif; font-size: 20px; font-weight: 900; color" +
                    ": white; line-height: 1.1; letter-spacing: -0.5px; text-shadow: 0 2px 8px rgba(0" +
                    ",0,0,0.3); }\r\n\r\n  .poster-student { position: absolute; bottom: 0; right: -8px; " +
                    "z-index: 2; }\r\n\r\n  .poster-footer { border-top: 1px solid rgba(255,255,255,0.1);" +
                    " padding-top: 10px; margin-top: 4px; position: relative; z-index: 2; }\r\n  .pf-it" +
                    "em { font-size: 9.5px; color: rgba(255,255,255,0.5); margin-bottom: 3px; }\r\n\r\n  " +
                    "@media (max-width: 1100px) {\r\n    .about-section { grid-template-columns: 1fr; }" +
                    "\r\n    .about-right { position: static; }\r\n    .poster-card { max-width: 360px; }" +
                    "\r\n  }\r\n\r\n  /* ══ FADE ANIMATIONS ══ */\r\n  .fade-up { opacity: 0; transform: tran" +
                    "slateY(22px); animation: fadeUp 0.55s cubic-bezier(0.22,1,0.36,1) forwards; }\r\n " +
                    " .d1 { animation-delay: 0.05s; } .d2 { animation-delay: 0.15s; } .d3 { animation" +
                    "-delay: 0.25s; }\r\n  .d4 { animation-delay: 0.35s; } .d5 { animation-delay: 0.45s" +
                    "; } .d6 { animation-delay: 0.55s; }\r\n  @keyframes fadeUp { to { opacity: 1; tran" +
                    "sform: translateY(0); } }\r\n\r\n  .overlay { display: none; position: fixed; inset:" +
                    " 0; background: rgba(8,21,71,0.4); z-index: 140; backdrop-filter: blur(4px); }\r\n" +
                    "  .overlay.show { display: block; }\r\n\r\n  /* ══ RESPONSIVE ══ */\r\n  @media (max-w" +
                    "idth: 1100px) { .why-grid { grid-template-columns: repeat(2, 1fr); } .affil-bann" +
                    "er { flex-wrap: wrap; gap: 20px; } .affil-divider { display: none; } }\r\n  @media" +
                    " (max-width: 900px) {\r\n    :root { --sidebar-w: 0px; }\r\n    .sidebar { left: -26" +
                    "5px; width: 265px; }\r\n    .sidebar.open { left: 0; }\r\n    .main { margin-left: 0" +
                    "; width: 100%; }\r\n    .header-logo { width: auto; border-right: none; }\r\n    .he" +
                    "ro-banner { grid-template-columns: 1fr; }\r\n    .hero-visual { display: none; }\r\n" +
                    "    .why-grid { grid-template-columns: 1fr; }\r\n  }\r\n  @media (max-width: 600px) " +
                    "{ .main-inner { padding: 20px 16px; } .hero-content { padding: 28px 24px; } .her" +
                    "o-title { font-size: 24px; } .affil-banner { padding: 20px 20px; } }\r\n\r\n  /* ── " +
                    "Master Page overrides ── */\r\n  header { display: none !important; }\r\n  .sidebar " +
                    "{ display: none !important; }\r\n  .overlay { display: none !important; }\r\n  body " +
                    "{ padding-top: 0 !important; background: var(--bg) !important; }\r\n  .main { marg" +
                    "in-left: 0 !important; padding-top: 0 !important; width: 100% !important; }\r\n  ." +
                    "main-inner { padding: 24px 32px !important; }\r\n</style>\r\n\r\n<main class=\"main\">\r\n" +
                    "  <div class=\"main-inner\">\r\n\r\n    <!-- HERO BANNER -->\r\n    <div class=\"hero-ban" +
                    "ner fade-up d1\">\r\n      <div class=\"hero-shapes\">\r\n        <div class=\"shape sha" +
                    "pe-1\"></div>\r\n        <div class=\"shape shape-2\"></div>\r\n        <div class=\"sha" +
                    "pe shape-3\"></div>\r\n      </div>\r\n\r\n      <div class=\"hero-content\">\r\n\r\n        " +
                    "<div class=\"hero-title\">\r\n          Lead Business with<br>\r\n          <span clas" +
                    "s=\"highlight\">Vision &amp; Strategy</span>\r\n        </div>\r\n\r\n        <div class" +
                    "=\"hero-mini-stats\">\r\n          <div class=\"hms-item\">\r\n            <div class=\"h" +
                    "ms-val\">4<span>yr</span></div>\r\n            <div class=\"hms-lbl\">Program</div>\r\n" +
                    "          </div>\r\n          <div class=\"hms-item\">\r\n            <div class=\"hms-" +
                    "val\">8</div>\r\n            <div class=\"hms-lbl\">Semesters</div>\r\n          </div>" +
                    "\r\n          <div class=\"hms-item\">\r\n            <div class=\"hms-val\">135</div>\r\n" +
                    "            <div class=\"hms-lbl\">Credit Hours</div>\r\n          </div>\r\n         " +
                    " <div class=\"hms-item\">\r\n            <div class=\"hms-val\">1600<span>+</span></di" +
                    "v>\r\n            <div class=\"hms-lbl\">Graduates</div>\r\n          </div>\r\n        " +
                    "</div>\r\n\r\n      </div>\r\n\r\n      <!-- ILLUSTRATION PANEL -->\r\n      <div class=\"h" +
                    "ero-visual\">\r\n        <div class=\"hero-illustration\">\r\n          <div class=\"ilu" +
                    "-glow\"></div>\r\n\r\n          <!-- SVG Student Illustration (BBA — business / chart" +
                    " theme) -->\r\n          <svg class=\"student-fig\" viewBox=\"0 0 240 280\" fill=\"none" +
                    "\" xmlns=\"http://www.w3.org/2000/svg\">\r\n            <!-- body / blazer -->\r\n     " +
                    "       <rect x=\"68\" y=\"155\" width=\"104\" height=\"125\" rx=\"14\" fill=\"#1a2e6e\"/>\r\n " +
                    "           <rect x=\"108\" y=\"155\" width=\"24\" height=\"80\" rx=\"4\" fill=\"#0B1F66\"/>\r" +
                    "\n            <!-- tie -->\r\n            <polygon points=\"120,162 115,190 120,196 " +
                    "125,190\" fill=\"#FF2D8D\"/>\r\n            <!-- shirt collar -->\r\n            <polyg" +
                    "on points=\"108,155 120,175 132,155 118,160\" fill=\"white\" opacity=\"0.9\"/>\r\n      " +
                    "      <polygon points=\"132,155 120,175 108,155 122,160\" fill=\"#e0e4f0\" opacity=\"" +
                    "0.9\"/>\r\n            <!-- arms -->\r\n            <rect x=\"38\" y=\"158\" width=\"36\" h" +
                    "eight=\"92\" rx=\"14\" fill=\"#1a2e6e\"/>\r\n            <rect x=\"166\" y=\"158\" width=\"36" +
                    "\" height=\"92\" rx=\"14\" fill=\"#1a2e6e\"/>\r\n            <!-- hands -->\r\n            " +
                    "<ellipse cx=\"56\" cy=\"256\" rx=\"16\" ry=\"12\" fill=\"#f5c5a3\"/>\r\n            <ellipse" +
                    " cx=\"184\" cy=\"253\" rx=\"16\" ry=\"12\" fill=\"#f5c5a3\"/>\r\n            <!-- briefcase " +
                    "in right hand -->\r\n            <rect x=\"188\" y=\"208\" width=\"42\" height=\"32\" rx=\"" +
                    "5\" fill=\"#F5C542\"/>\r\n            <rect x=\"198\" y=\"204\" width=\"22\" height=\"6\" rx=" +
                    "\"3\" fill=\"#d4a800\" stroke=\"#d4a800\" stroke-width=\"1\"/>\r\n            <line x1=\"20" +
                    "9\" y1=\"208\" x2=\"209\" y2=\"240\" stroke=\"#d4a800\" stroke-width=\"2\"/>\r\n            <" +
                    "line x1=\"188\" y1=\"220\" x2=\"230\" y2=\"220\" stroke=\"#d4a800\" stroke-width=\"1.5\"/>\r\n" +
                    "            <!-- bar chart on clipboard (left hand) -->\r\n            <rect x=\"28" +
                    "\" y=\"196\" width=\"50\" height=\"62\" rx=\"5\" fill=\"white\" opacity=\"0.95\"/>\r\n         " +
                    "   <rect x=\"32\" y=\"198\" width=\"42\" height=\"4\" rx=\"2\" fill=\"#e5e7eb\"/>\r\n         " +
                    "   <!-- bars -->\r\n            <rect x=\"36\" y=\"238\" width=\"8\" height=\"16\" rx=\"2\" " +
                    "fill=\"#0B1F66\"/>\r\n            <rect x=\"48\" y=\"228\" width=\"8\" height=\"26\" rx=\"2\" " +
                    "fill=\"#FF2D8D\"/>\r\n            <rect x=\"60\" y=\"220\" width=\"8\" height=\"34\" rx=\"2\" " +
                    "fill=\"#F5C542\"/>\r\n            <!-- trend line -->\r\n            <polyline points=" +
                    "\"36,245 52,232 68,218\" stroke=\"#16a34a\" stroke-width=\"2\" fill=\"none\" stroke-line" +
                    "cap=\"round\"/>\r\n            <!-- neck -->\r\n            <rect x=\"108\" y=\"132\" widt" +
                    "h=\"24\" height=\"28\" rx=\"8\" fill=\"#f5c5a3\"/>\r\n            <!-- head -->\r\n         " +
                    "   <ellipse cx=\"120\" cy=\"110\" rx=\"46\" ry=\"50\" fill=\"#f5c5a3\"/>\r\n            <!--" +
                    " hair -->\r\n            <path d=\"M74 96 Q76 52 120 50 Q164 52 166 96 Q155 72 120 " +
                    "70 Q85 72 74 96Z\" fill=\"#2d1a08\"/>\r\n            <ellipse cx=\"120\" cy=\"55\" rx=\"20" +
                    "\" ry=\"14\" fill=\"#2d1a08\"/>\r\n            <!-- facial features -->\r\n            <e" +
                    "llipse cx=\"108\" cy=\"114\" rx=\"6\" ry=\"7\" fill=\"white\"/>\r\n            <ellipse cx=\"" +
                    "132\" cy=\"114\" rx=\"6\" ry=\"7\" fill=\"white\"/>\r\n            <ellipse cx=\"109\" cy=\"11" +
                    "5\" rx=\"3.5\" ry=\"4\" fill=\"#1a0a0a\"/>\r\n            <ellipse cx=\"133\" cy=\"115\" rx=\"" +
                    "3.5\" ry=\"4\" fill=\"#1a0a0a\"/>\r\n            <ellipse cx=\"110\" cy=\"114\" rx=\"1.5\" ry" +
                    "=\"2\" fill=\"white\"/>\r\n            <ellipse cx=\"134\" cy=\"114\" rx=\"1.5\" ry=\"2\" fill" +
                    "=\"white\"/>\r\n            <path d=\"M112 128 Q120 135 128 128\" stroke=\"#c27a5a\" str" +
                    "oke-width=\"2\" fill=\"none\" stroke-linecap=\"round\"/>\r\n            <path d=\"M102 10" +
                    "7 Q108 104 114 106\" stroke=\"#2d1a08\" stroke-width=\"2.5\" fill=\"none\" stroke-linec" +
                    "ap=\"round\"/>\r\n            <path d=\"M126 106 Q132 104 138 107\" stroke=\"#2d1a08\" s" +
                    "troke-width=\"2.5\" fill=\"none\" stroke-linecap=\"round\"/>\r\n          </svg>\r\n\r\n    " +
                    "      <!-- Floating badges — BBA specific -->\r\n          <div class=\"ilu-badge i" +
                    "b-1\">\r\n            <div class=\"ib-icon blue\">📊</div>\r\n            <div class=\"i" +
                    "b-txt\">\r\n              <strong>Business Analytics Lab</strong>\r\n              <s" +
                    "pan>Data-driven decisions</span>\r\n            </div>\r\n          </div>\r\n\r\n      " +
                    "    <div class=\"ilu-badge ib-2\">\r\n            <div class=\"ib-icon pink\">🤝</div>" +
                    "\r\n            <div class=\"ib-txt\">\r\n              <strong>Industry Mentorship</s" +
                    "trong>\r\n              <span>CEOs &amp; entrepreneurs</span>\r\n            </div>\r" +
                    "\n          </div>\r\n\r\n          <div class=\"ilu-badge ib-3\">\r\n            <div cl" +
                    "ass=\"ib-icon green\">💼</div>\r\n            <div class=\"ib-txt\">\r\n              <s" +
                    "trong>92% Placement</strong>\r\n              <span>2024 cohort</span>\r\n          " +
                    "  </div>\r\n          </div>\r\n        </div>\r\n      </div>\r\n    </div>\r\n\r\n    <!--" +
                    " ABOUT THE PROGRAM -->\r\n    <div class=\"about-section fade-up d2\" id=\"coursesSec" +
                    "tion\">\r\n      <div class=\"about-left\">\r\n        <div class=\"about-label\">About t" +
                    "he Program</div>\r\n        <h2 class=\"about-heading\">Nepal\'s Premier <span>BBA De" +
                    "gree</span></h2>\r\n\r\n        <p class=\"about-para\">\r\n          The <strong>Bachel" +
                    "or of Business Administration (BBA)</strong> at Texas College of Management and " +
                    "IT (TCMIT) is a 4-year, 8-semester program affiliated with <strong>Lincoln Unive" +
                    "rsity College, Malaysia</strong>.\r\n          Designed to blend management theory" +
                    " with practical business execution, the program covers marketing, finance, human" +
                    " resource management, entrepreneurship, business analytics, and digital transfor" +
                    "mation.\r\n          With modern facilities including a Business Simulation Lab, I" +
                    "ncubation Center, and e-Library, students gain hands-on experience through live " +
                    "projects and industry internships to graduate completely career-ready.\r\n        " +
                    "</p>\r\n        <p class=\"about-para\">\r\n          To ensure graduates are industry" +
                    "-ready from day one, <strong>Texas College integrates structured After-Class Pro" +
                    "fessional Classes</strong> directly into the academic timeline.\r\n          With " +
                    "dedicated Business Analytics and ERP labs, an active Incubation Center, and a st" +
                    "ate-of-the-art e-library, students gain hands-on experience navigating real-worl" +
                    "d business challenges.\r\n          <strong>Industry training, live project work, " +
                    "and globally recognised management certifications</strong> ensure graduates thri" +
                    "ve in business leadership roles in Nepal and around the world.\r\n        </p>\r\n  " +
                    "      <p class=\"about-para\">\r\n          Alongside the core management track, the" +
                    " student journey includes specialised professional certifications to build globa" +
                    "l competitiveness.\r\n          Students explore<strong> financial modelling works" +
                    "hops, digital marketing and branding strategy, build entrepreneurial</strong> ve" +
                    "ntures through the Incubation Center, and master data analytics using industry t" +
                    "ools.\r\n   \r\n        </p>\r\n\r\n        <div class=\"about-btns\"></div>\r\n      </div>" +
                    "\r\n\r\n      <div class=\"about-right\">\r\n        <div class=\"poster-wrap\">\r\n        " +
                    "  <div class=\"poster-card\">\r\n            <div class=\"poster-inner\">\r\n           " +
                    "   <div class=\"poster-logos\">\r\n                <div class=\"poster-logo-tx\">\r\n   " +
                    "               <div class=\"tx-text-wrap\">\r\n                    <span class=\"tx-n" +
                    "ame\">Texas</span>\r\n                    <span class=\"tx-sub\">College of Managemen" +
                    "t &amp; IT</span>\r\n                  </div>\r\n                </div>\r\n           " +
                    "     <div class=\"poster-logo-luc\">\r\n                  <div class=\"luc-seal\">LUC<" +
                    "/div>\r\n                  <span class=\"luc-name\">LINCOLN<br>UNIVERSITY<br>COLLEGE" +
                    "</span>\r\n                </div>\r\n              </div>\r\n\r\n              <div clas" +
                    "s=\"poster-tagline\">LEAD BUSINESS WITH VISION</div>\r\n              <div class=\"po" +
                    "ster-main-title\">WITH<br>BUSINESS ADMIN</div>\r\n              <div class=\"poster-" +
                    "degree-row\">\r\n                <div class=\"poster-degree-title\">BBA</div>\r\n      " +
                    "        </div>\r\n              <div class=\"poster-degree-sub\">Bachelor of (Hons.)" +
                    " in<br><strong>Business Administration</strong></div>\r\n\r\n              <div clas" +
                    "s=\"poster-why-box\">\r\n                <div class=\"pwb-title\">Discover <span>BBA</" +
                    "span>at Texas</div>\r\n                <div class=\"pwb-item\">▶ Business Simulation" +
                    " Lab</div>\r\n                <div class=\"pwb-item\">▶ ERP &amp; Analytics Studio</" +
                    "div>\r\n                <div class=\"pwb-item\">▶ Incubation Center</div>\r\n         " +
                    "       <div class=\"pwb-item\">▶ Resourceful Library &amp; ebrary</div>\r\n         " +
                    "       <div class=\"pwb-item\">▶ Industry Mentorship Cell</div>\r\n              </d" +
                    "iv>\r\n\r\n              <div class=\"poster-admission\">\r\n                <div class=" +
                    "\"pa-open\">ADMISSION<br>OPEN 2026</div>\r\n              </div>\r\n\r\n              <!" +
                    "-- Poster student SVG (BBA — holding briefcase) -->\r\n              <div class=\"p" +
                    "oster-student\">\r\n                <svg viewBox=\"0 0 160 270\" fill=\"none\" xmlns=\"h" +
                    "ttp://www.w3.org/2000/svg\" width=\"155\" height=\"270\">\r\n                  <rect x=" +
                    "\"38\" y=\"125\" width=\"84\" height=\"145\" rx=\"12\" fill=\"#1e3a8a\"/>\r\n                 " +
                    " <rect x=\"72\" y=\"125\" width=\"16\" height=\"70\" rx=\"3\" fill=\"#1a2e6e\"/>\r\n          " +
                    "        <polygon points=\"80,131 76,155 80,160 84,155\" fill=\"#FF2D8D\"/>\r\n        " +
                    "          <polygon points=\"72,125 80,142 88,125 79,129\" fill=\"white\" opacity=\"0." +
                    "85\"/>\r\n                  <rect x=\"16\" y=\"128\" width=\"28\" height=\"84\" rx=\"12\" fil" +
                    "l=\"#1e3a8a\"/>\r\n                  <rect x=\"116\" y=\"128\" width=\"28\" height=\"84\" rx" +
                    "=\"12\" fill=\"#1e3a8a\"/>\r\n                  <ellipse cx=\"30\" cy=\"218\" rx=\"13\" ry=\"" +
                    "10\" fill=\"#f5c5a3\"/>\r\n                  <ellipse cx=\"130\" cy=\"216\" rx=\"13\" ry=\"1" +
                    "0\" fill=\"#f5c5a3\"/>\r\n                  <!-- briefcase -->\r\n                  <re" +
                    "ct x=\"118\" y=\"180\" width=\"34\" height=\"26\" rx=\"4\" fill=\"#F5C542\"/>\r\n             " +
                    "     <rect x=\"126\" y=\"176\" width=\"18\" height=\"5\" rx=\"2.5\" fill=\"#d4a800\"/>\r\n    " +
                    "              <line x1=\"135\" y1=\"180\" x2=\"135\" y2=\"206\" stroke=\"#d4a800\" stroke-" +
                    "width=\"1.5\"/>\r\n                  <line x1=\"118\" y1=\"190\" x2=\"152\" y2=\"190\" strok" +
                    "e=\"#d4a800\" stroke-width=\"1.2\"/>\r\n                  <rect x=\"72\" y=\"103\" width=\"" +
                    "16\" height=\"26\" rx=\"7\" fill=\"#f5c5a3\"/>\r\n                  <ellipse cx=\"80\" cy=\"" +
                    "82\" rx=\"36\" ry=\"40\" fill=\"#f5c5a3\"/>\r\n                  <path d=\"M44 72 Q46 34 8" +
                    "0 32 Q114 34 116 72 Q106 50 80 52 Q54 50 44 72Z\" fill=\"#2d1a08\"/>\r\n             " +
                    "     <ellipse cx=\"80\" cy=\"36\" rx=\"18\" ry=\"12\" fill=\"#2d1a08\"/>\r\n                " +
                    "  <ellipse cx=\"68\" cy=\"86\" rx=\"5.5\" ry=\"6.5\" fill=\"white\"/>\r\n                  <" +
                    "ellipse cx=\"92\" cy=\"86\" rx=\"5.5\" ry=\"6.5\" fill=\"white\"/>\r\n                  <ell" +
                    "ipse cx=\"69\" cy=\"87\" rx=\"3.2\" ry=\"3.8\" fill=\"#1a0a0a\"/>\r\n                  <elli" +
                    "pse cx=\"93\" cy=\"87\" rx=\"3.2\" ry=\"3.8\" fill=\"#1a0a0a\"/>\r\n                  <ellip" +
                    "se cx=\"70\" cy=\"86\" rx=\"1.3\" ry=\"1.6\" fill=\"white\"/>\r\n                  <ellipse " +
                    "cx=\"94\" cy=\"86\" rx=\"1.3\" ry=\"1.6\" fill=\"white\"/>\r\n                  <path d=\"M73" +
                    " 100 Q80 107 87 100\" stroke=\"#c27a5a\" stroke-width=\"1.8\" fill=\"none\" stroke-line" +
                    "cap=\"round\"/>\r\n                  <path d=\"M62 78 Q68 75 74 77\" stroke=\"#2d1a08\" " +
                    "stroke-width=\"2\" fill=\"none\" stroke-linecap=\"round\"/>\r\n                  <path d" +
                    "=\"M86 77 Q92 75 98 78\" stroke=\"#2d1a08\" stroke-width=\"2\" fill=\"none\" stroke-line" +
                    "cap=\"round\"/>\r\n                </svg>\r\n              </div>\r\n\r\n              <di" +
                    "v class=\"poster-footer\">\r\n                <div class=\"pf-item\">📍 Sifal, Chabahi" +
                    "l, Kathmandu</div>\r\n                <div class=\"pf-item\">📞 01-4589134 | 9801644" +
                    "458</div>\r\n                <div class=\"pf-item\">🌐 www.texascollege.edu.np</div>" +
                    "\r\n              </div>\r\n            </div>\r\n          </div>\r\n          <div cla" +
                    "ss=\"poster-glow\"></div>\r\n        </div>\r\n      </div>\r\n    </div>\r\n\r\n    <!-- AF" +
                    "FILIATION BANNER -->\r\n    <div class=\"affil-banner fade-up d4\">\r\n      <div clas" +
                    "s=\"affil-left\">\r\n        <div class=\"affil-label\">Affiliated with</div>\r\n       " +
                    " <div class=\"affil-name\">Lincoln University <span>College</span></div>\r\n        " +
                    "<div class=\"affil-sub\">Petaling Jaya, Malaysia · Est. 2002</div>\r\n      </div>\r\n" +
                    "\r\n      <div class=\"affil-divider\"></div>\r\n\r\n      <div class=\"affil-pills\">\r\n  " +
                    "      <div class=\"apill\"><span class=\"apill-icon\">✅</span> MQA Accredited</div>\r" +
                    "\n        <div class=\"apill\"><span class=\"apill-icon\">🎓</span> TU Equivalent</di" +
                    "v>\r\n        <div class=\"apill\"><span class=\"apill-icon\">📜</span> MoE Approved</" +
                    "div>\r\n        <div class=\"apill\"><span class=\"apill-icon\">🌏</span> Globally Rec" +
                    "ognised</div>\r\n        <div class=\"apill\"><span class=\"apill-icon\">🏆</span> Top" +
                    "-ranked College</div>\r\n      </div>\r\n\r\n      <div class=\"affil-right\">\r\n        " +
                    "<a href=\"https://www.lincoln.edu.my\" target=\"_blank\" rel=\"noopener noreferrer\" c" +
                    "lass=\"btn-learn\" style=\"text-decoration: none; display: inline-flex; align-items" +
                    ": center; gap: 8px;\">\r\n          Learn More\r\n          <svg width=\"13\" height=\"1" +
                    "3\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\" viewBox=\"0 0 24 24\">\r\n  " +
                    "          <path d=\"M18 13v6a2 2 0 01-2 2H5a2 2 0 01-2-2V8a2 2 0 012-2h6\"/>\r\n    " +
                    "        <polyline points=\"15 3 21 3 21 9\"/>\r\n            <line x1=\"10\" y1=\"14\" x" +
                    "2=\"21\" y2=\"3\"/>\r\n          </svg>\r\n        </a>\r\n      </div>\r\n    </div>\r\n\r\n  <" +
                    "/div>\r\n</main>\r\n\r\n<script>\r\nconst semesterData = [\r\n    { label: \"First Sem\", ic" +
                    "on: \"1️⃣\", subjects: [\"Business English\", \"Principles of Management\", \"Microecon" +
                    "omics\", \"Mathematics for Business\", \"Computer Applications\"] },\r\n    { label: \"S" +
                    "econd Sem\", icon: \"2️⃣\", subjects: [\"Macroeconomics\", \"Business Communication\", " +
                    "\"Financial Accounting\", \"Organizational Behaviour\", \"Statistics for Business\"] }" +
                    ",\r\n    { label: \"Third Sem\", icon: \"3️⃣\", subjects: [\"Marketing Management\", \"Co" +
                    "st Accounting\", \"Business Law\", \"Human Resource Management\", \"Entrepreneurship\"]" +
                    " },\r\n    { label: \"Fourth Sem\", icon: \"4️⃣\", subjects: [\"Financial Management\", " +
                    "\"Operations Management\", \"Consumer Behaviour\", \"Business Research Methods\", \"Man" +
                    "agement Information Systems\"] },\r\n    { label: \"Fifth Sem\", icon: \"5️⃣\", subject" +
                    "s: [\"Strategic Management\", \"Investment & Portfolio Mgmt\", \"Digital Marketing\", " +
                    "\"Supply Chain Management\", \"Business Analytics\"] },\r\n    { label: \"Sixth Sem\", i" +
                    "con: \"6️⃣\", subjects: [\"International Business\", \"Corporate Finance\", \"Brand Man" +
                    "agement\", \"Project Management\", \"E-Commerce\"] },\r\n    { label: \"Seventh Sem\", ic" +
                    "on: \"7️⃣\", subjects: [\"Business Ethics & CSR\", \"Internship\", \"Elective I\", \"Elec" +
                    "tive II\", \"Advanced Management Topics\"] },\r\n    { label: \"Eighth Sem\", icon: \"8️" +
                    "⃣\", subjects: [\"Capstone Project\", \"Dissertation\", \"Viva Voce\", \"Elective III\"] " +
                    "},\r\n];\r\n\r\nconst menu = document.getElementById(\'semMenu\');\r\nsemesterData.forEach" +
                    "((sem, i) => {\r\n    const el = document.createElement(\'div\');\r\n    el.className " +
                    "= \'sem-item\' + (i === 0 ? \' open\' : \'\');\r\n    el.innerHTML = `\r\n      <div class" +
                    "=\"sem-header${i === 0 ? \' active\' : \'\'}\" onclick=\"toggleSem(this)\">\r\n        <di" +
                    "v class=\"sem-icon\">${sem.icon}</div>\r\n        <span class=\"sem-label\">${sem.labe" +
                    "l}</span>\r\n        <svg class=\"sem-chevron\" width=\"13\" height=\"13\" fill=\"none\" s" +
                    "troke=\"currentColor\" stroke-width=\"2.5\" viewBox=\"0 0 24 24\"><path d=\"M19 9l-7 7-" +
                    "7-7\"/></svg>\r\n      </div>\r\n      <div class=\"sem-subjects\">\r\n        ${sem.subj" +
                    "ects.map((s, j) => `<div class=\"subject-link${i === 0 && j === 0 ? \' active\' : \'" +
                    "\'}\" onclick=\"pickSubject(this)\"><div class=\"subject-dot\"></div>${s}</div>`).join" +
                    "(\'\')}\r\n      </div>`;\r\n    menu?.appendChild(el);\r\n});\r\n\r\nfunction toggleSem(el)" +
                    " {\r\n    el.parentElement.classList.toggle(\'open\');\r\n}\r\n\r\nfunction pickSubject(el" +
                    ") {\r\n    document.querySelectorAll(\'.subject-link\').forEach(l => l.classList.rem" +
                    "ove(\'active\'));\r\n    el.classList.add(\'active\');\r\n    if (window.innerWidth < 90" +
                    "0) closeSidebar();\r\n}\r\n\r\nfunction scrollToCourses() {\r\n    document.getElementBy" +
                    "Id(\'coursesSection\')?.scrollIntoView({ behavior: \'smooth\', block: \'start\' });\r\n}" +
                    "\r\n\r\nfunction closeSidebar() {\r\n    document.getElementById(\'sidebar\')?.classList" +
                    ".remove(\'open\');\r\n    document.getElementById(\'overlay\')?.classList.remove(\'show" +
                    "\');\r\n}\r\n</script>\r\n\r\n");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        253,
                        38982,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.WebTools.BrowserLink.Runtime.WebForms.TraceHelpers, Microsoft.WebTools." +
                    "BrowserLink.Tracing, Version=18.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f1" +
                    "1d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.bba_notes_dash_aspx.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.bba_notes_dash_aspx.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent1(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 2 "D:\Learningportal\Learning-System\Bba_Notes\dash.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 2 "D:\Learningportal\Learning-System\Bba_Notes\dash.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(bba_notes_dash_aspx @__ctrl) {
            
            #line 1 "D:\Learningportal\Learning-System\Bba_Notes\dash.aspx"
            @__ctrl.Title = "";
            
            #line default
            #line hidden
            
            #line 1 "D:\Learningportal\Learning-System\Bba_Notes\dash.aspx"
            @__ctrl.MasterPageFile = "~/Bba_Notes/note.Master";
            
            #line default
            #line hidden
            
            #line 1 "D:\Learningportal\Learning-System\Bba_Notes\dash.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 2 "D:\Learningportal\Learning-System\Bba_Notes\dash.aspx"
            this.AddContentTemplate("ContentPlaceHolder1", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent1)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "D:\Learningportal\Learning-System\Bba_Notes\dash.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.bba_notes_dash_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -1005266328;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
