#pragma checksum "D:\Learningportal\Learning-System\Bit_Notes\dash.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "13FB7EA3A08EC964DAC17A85D8929BEAB73F5EE6"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    
    #line 3 "D:\Learningportal\Learning-System\Bit_Notes\dash.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 325 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 331 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 338 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 3 "D:\Learningportal\Learning-System\Bit_Notes\dash.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 326 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 330 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 1 "D:\Learningportal\Learning-System\Bit_Notes\dash.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 336 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 329 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 333 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 3 "D:\Learningportal\Learning-System\Bit_Notes\dash.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 334 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 3 "D:\Learningportal\Learning-System\Bit_Notes\dash.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 328 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 337 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 3 "D:\Learningportal\Learning-System\Bit_Notes\dash.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 332 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 327 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 343 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 342 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class bit_notes_dash_aspx : global::Learning_System.Bit_Notes.dash, System.Web.SessionState.IRequiresSessionState, System.Web.IHttpHandler {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.bit_notes_dash_aspx.@__PageInspector_LoadHelper("SetTraceData");
        
        private static bool @__initialized;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bit_notes_dash_aspx() {
            string[] dependencies;
            ((global::Learning_System.Bit_Notes.dash)(this)).AppRelativeVirtualPath = "~/Bit_Notes/dash.aspx";
            if ((global::ASP.bit_notes_dash_aspx.@__initialized == false)) {
                dependencies = new string[2];
                dependencies[0] = "~/Bit_Notes/dash.aspx";
                dependencies[1] = "~/Bit_Notes/note.Master";
                global::ASP.bit_notes_dash_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.bit_notes_dash_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(this.Context.ApplicationInstance));
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n<style>\r\n\r\n\r\n  :root {\r\n    --primary: #0B1F66;\r\n    --secondary: #081547;\r\n " +
                    "   --pink: #FF2D8D;\r\n    --pink-dark: #d4206e;\r\n    --pink-glow: rgba(255,45,141" +
                    ",0.22);\r\n    --pink-soft: rgba(255,45,141,0.1);\r\n    --bg: #f0f3fc;\r\n    --bg-ca" +
                    "rd: #ffffff;\r\n    --text-primary: #0B1F66;\r\n    --text-secondary: #5a6a99;\r\n    " +
                    "--text-light: #a0aec8;\r\n    --border: rgba(11,31,102,0.1);\r\n    --border-pink: r" +
                    "gba(255,45,141,0.18);\r\n    --shadow-sm: 0 2px 12px rgba(8,21,71,0.07);\r\n    --sh" +
                    "adow-md: 0 8px 32px rgba(8,21,71,0.13);\r\n    --shadow-lg: 0 20px 60px rgba(8,21," +
                    "71,0.2);\r\n    --radius: 18px;\r\n    --radius-sm: 10px;\r\n    --sidebar-w: 265px;\r\n" +
                    "    --header-h: 68px;\r\n    --ease: 0.28s cubic-bezier(0.4,0,0.2,1);\r\n  }\r\n\r\n  *," +
                    " *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\r\n\r\n  bod" +
                    "y {\r\n    font-family: \'DM Sans\', sans-serif;\r\n    background: var(--bg);\r\n    co" +
                    "lor: var(--text-primary);\r\n    min-height: 100vh;\r\n    overflow-x: hidden;\r\n  }\r" +
                    "\n\r\n  ::-webkit-scrollbar { width: 5px; }\r\n  ::-webkit-scrollbar-track { backgrou" +
                    "nd: transparent; }\r\n  ::-webkit-scrollbar-thumb { background: rgba(11,31,102,0.1" +
                    "5); border-radius: 4px; }\r\n\r\n  /* ══ HEADER ══ */\r\n  header {\r\n    position: fix" +
                    "ed; top: 0; left: 0; right: 0; z-index: 200;\r\n    height: var(--header-h);\r\n    " +
                    "background: rgba(255,255,255,0.92);\r\n    backdrop-filter: blur(20px);\r\n    -webk" +
                    "it-backdrop-filter: blur(20px);\r\n    border-bottom: 1px solid var(--border);\r\n  " +
                    "  display: flex; align-items: center;\r\n    padding: 0 28px 0 0;\r\n    box-shadow:" +
                    " 0 2px 24px rgba(8,21,71,0.07);\r\n  }\r\n\r\n  .header-logo {\r\n    width: var(--sideb" +
                    "ar-w);\r\n    display: flex; align-items: center; justify-content: center;\r\n    pa" +
                    "dding: 0 20px;\r\n    border-right: 1px solid var(--border);\r\n    height: 100%;\r\n " +
                    "   flex-shrink: 0;\r\n    gap: 10px;\r\n  }\r\n\r\n  .logo-mark {\r\n    width: 36px; heig" +
                    "ht: 36px;\r\n    background: linear-gradient(135deg, var(--primary), var(--pink));" +
                    "\r\n    border-radius: 10px;\r\n    display: flex; align-items: center; justify-cont" +
                    "ent: center;\r\n    font-family: \'Sora\', sans-serif;\r\n    font-weight: 800; font-s" +
                    "ize: 14px; color: white;\r\n    flex-shrink: 0;\r\n  }\r\n\r\n  .logo-text {\r\n    displa" +
                    "y: flex; flex-direction: column;\r\n  }\r\n  .logo-text strong {\r\n    font-family: \'" +
                    "Sora\', sans-serif;\r\n    font-size: 14px; font-weight: 800;\r\n    color: var(--pri" +
                    "mary); line-height: 1.1;\r\n  }\r\n  .logo-text span {\r\n    font-size: 10px; color: " +
                    "var(--text-light); letter-spacing: 0.3px;\r\n  }\r\n\r\n  .header-center {\r\n    flex: " +
                    "1; display: flex; align-items: center;\r\n    padding: 0 28px; gap: 16px;\r\n  }\r\n\r\n" +
                    "  .page-title {\r\n    font-family: \'Sora\', sans-serif;\r\n    font-size: 15px; font" +
                    "-weight: 700;\r\n    color: var(--primary);\r\n    letter-spacing: -0.2px;\r\n    whit" +
                    "e-space: nowrap;\r\n    display: flex; align-items: center; gap: 8px;\r\n  }\r\n  .pag" +
                    "e-title .tag {\r\n    font-size: 10px; font-weight: 700;\r\n    background: var(--pi" +
                    "nk);\r\n    color: white;\r\n    padding: 3px 9px; border-radius: 50px;\r\n    letter-" +
                    "spacing: 0.4px;\r\n    font-family: \'Sora\', sans-serif;\r\n  }\r\n\r\n  .search-bar {\r\n " +
                    "   display: flex; align-items: center; gap: 10px;\r\n    background: var(--bg);\r\n " +
                    "   border: 1.5px solid var(--border);\r\n    border-radius: 50px;\r\n    padding: 9p" +
                    "x 18px;\r\n    max-width: 340px; width: 100%;\r\n    transition: var(--ease);\r\n  }\r\n" +
                    "  .search-bar:focus-within {\r\n    border-color: var(--pink);\r\n    box-shadow: 0 " +
                    "0 0 4px var(--pink-glow);\r\n    background: white;\r\n  }\r\n  .search-bar svg { colo" +
                    "r: var(--text-light); flex-shrink: 0; }\r\n  .search-bar input {\r\n    border: none" +
                    "; background: transparent;\r\n    font-family: \'DM Sans\', sans-serif;\r\n    font-si" +
                    "ze: 13.5px; color: var(--text-primary);\r\n    outline: none; width: 100%;\r\n  }\r\n " +
                    " .search-bar input::placeholder { color: var(--text-light); }\r\n\r\n  .header-actio" +
                    "ns { display: flex; align-items: center; gap: 8px; }\r\n\r\n  .icon-btn {\r\n    width" +
                    ": 38px; height: 38px;\r\n    border-radius: 10px;\r\n    border: 1.5px solid var(--b" +
                    "order);\r\n    background: white;\r\n    display: flex; align-items: center; justify" +
                    "-content: center;\r\n    cursor: pointer; transition: var(--ease);\r\n    color: var" +
                    "(--text-secondary);\r\n    position: relative;\r\n  }\r\n  .icon-btn:hover { backgroun" +
                    "d: var(--bg); border-color: var(--pink); color: var(--pink); }\r\n\r\n  .notif-dot {" +
                    "\r\n    position: absolute; top: 8px; right: 8px;\r\n    width: 7px; height: 7px;\r\n " +
                    "   background: var(--pink); border-radius: 50%;\r\n    border: 2px solid white;\r\n " +
                    " }\r\n\r\n  .avatar {\r\n    width: 38px; height: 38px; border-radius: 50%;\r\n    backg" +
                    "round: linear-gradient(135deg, var(--primary), var(--pink));\r\n    display: flex;" +
                    " align-items: center; justify-content: center;\r\n    font-family: \'Sora\', sans-se" +
                    "rif;\r\n    font-weight: 700; font-size: 13px; color: white;\r\n    cursor: pointer;" +
                    "\r\n    box-shadow: 0 2px 10px var(--pink-glow);\r\n    border: 2px solid white;\r\n  " +
                    "}\r\n\r\n  /* ══ SIDEBAR ══ */\r\n  .sidebar {\r\n    position: fixed; left: 0; top: var" +
                    "(--header-h);\r\n    width: var(--sidebar-w);\r\n    height: calc(100vh - var(--head" +
                    "er-h));\r\n    background: var(--secondary);\r\n    overflow-y: auto; overflow-x: hi" +
                    "dden;\r\n    padding: 18px 10px 24px;\r\n    z-index: 150;\r\n    transition: var(--ea" +
                    "se);\r\n    border-right: 1px solid rgba(255,255,255,0.05);\r\n  }\r\n  .sidebar::-web" +
                    "kit-scrollbar { width: 3px; }\r\n  .sidebar::-webkit-scrollbar-thumb { background:" +
                    " rgba(255,255,255,0.08); border-radius: 3px; }\r\n\r\n  .sidebar-label {\r\n    font-s" +
                    "ize: 10px; font-weight: 700;\r\n    text-transform: uppercase; letter-spacing: 1.8" +
                    "px;\r\n    color: rgba(255,255,255,0.28);\r\n    padding: 4px 12px 10px;\r\n    margin" +
                    "-top: 4px;\r\n  }\r\n\r\n  .sem-item { margin-bottom: 1px; }\r\n\r\n  .sem-header {\r\n    d" +
                    "isplay: flex; align-items: center; gap: 10px;\r\n    padding: 9px 12px;\r\n    borde" +
                    "r-radius: var(--radius-sm);\r\n    cursor: pointer; transition: var(--ease);\r\n    " +
                    "color: rgba(255,255,255,0.58);\r\n    font-size: 13px; font-weight: 500;\r\n    posi" +
                    "tion: relative; user-select: none;\r\n  }\r\n  .sem-header:hover { background: rgba(" +
                    "255,255,255,0.06); color: rgba(255,255,255,0.9); }\r\n  .sem-header.active { backg" +
                    "round: rgba(255,45,141,0.16); color: white; }\r\n  .sem-header.active::before {\r\n " +
                    "   content: \'\';\r\n    position: absolute; left: 0; top: 20%; bottom: 20%;\r\n    wi" +
                    "dth: 3px; background: var(--pink);\r\n    border-radius: 0 3px 3px 0;\r\n  }\r\n\r\n  .s" +
                    "em-icon {\r\n    width: 26px; height: 26px;\r\n    background: rgba(255,255,255,0.07" +
                    ");\r\n    border-radius: 7px;\r\n    display: flex; align-items: center; justify-con" +
                    "tent: center;\r\n    font-size: 12px; flex-shrink: 0;\r\n    transition: var(--ease)" +
                    ";\r\n  }\r\n  .sem-header.active .sem-icon { background: rgba(255,45,141,0.28); }\r\n\r" +
                    "\n  .sem-label { flex: 1; }\r\n  .sem-chevron { transition: var(--ease); opacity: 0" +
                    ".45; flex-shrink: 0; }\r\n  .sem-item.open .sem-chevron { transform: rotate(180deg" +
                    "); opacity: 1; color: var(--pink); }\r\n\r\n  .sem-subjects { display: none; padding" +
                    ": 3px 0 3px 16px; }\r\n  .sem-item.open .sem-subjects { display: block; }\r\n\r\n  .su" +
                    "bject-link {\r\n    display: flex; align-items: center; gap: 8px;\r\n    padding: 7p" +
                    "x 12px; border-radius: 8px;\r\n    font-size: 12.5px; color: rgba(255,255,255,0.4)" +
                    ";\r\n    cursor: pointer; transition: var(--ease);\r\n  }\r\n  .subject-link:hover { c" +
                    "olor: rgba(255,255,255,0.75); background: rgba(255,255,255,0.04); }\r\n  .subject-" +
                    "link.active { color: var(--pink); background: rgba(255,45,141,0.08); font-weight" +
                    ": 500; }\r\n  .subject-dot { width: 4px; height: 4px; border-radius: 50%; backgrou" +
                    "nd: currentColor; flex-shrink: 0; }\r\n\r\n  /* sidebar course tabs */\r\n  .course-ta" +
                    "bs {\r\n    display: flex; gap: 6px;\r\n    padding: 0 8px 14px;\r\n    margin-bottom:" +
                    " 4px;\r\n  }\r\n  .ctab {\r\n    flex: 1; padding: 7px 0;\r\n    border-radius: 8px;\r\n  " +
                    "  font-family: \'Sora\', sans-serif;\r\n    font-size: 11px; font-weight: 700;\r\n    " +
                    "text-align: center;\r\n    cursor: pointer; transition: var(--ease);\r\n    color: r" +
                    "gba(255,255,255,0.4);\r\n    border: 1px solid rgba(255,255,255,0.07);\r\n    backgr" +
                    "ound: rgba(255,255,255,0.04);\r\n    letter-spacing: 0.3px;\r\n  }\r\n  .ctab.active {" +
                    "\r\n    background: var(--pink);\r\n    color: white;\r\n    border-color: transparent" +
                    ";\r\n    box-shadow: 0 3px 12px rgba(255,45,141,0.4);\r\n  }\r\n  .ctab:not(.active):h" +
                    "over {\r\n    background: rgba(255,255,255,0.08);\r\n    color: rgba(255,255,255,0.7" +
                    ");\r\n  }\r\n\r\n  /* ══ MAIN ══ */\r\n  .main { margin-left: var(--sidebar-w); padding-" +
                    "top: var(--header-h); min-height: 100vh; width: calc(100% - var(--sidebar-w)); }" +
                    "\r\n  .main-inner { padding: 30px 36px; width: 100%; }\r\n\r\n\r\n  /* ══ HERO BANNER ══" +
                    " */\r\n  .hero-banner {\r\n    background: linear-gradient(135deg, #0B1F66 0%, #0815" +
                    "47 100%);\r\n    border-radius: 24px;\r\n    padding: 0;\r\n    position: relative; ov" +
                    "erflow: hidden;\r\n    box-shadow: var(--shadow-lg);\r\n    margin-bottom: 28px;\r\n  " +
                    "  display: grid;\r\n    grid-template-columns: 1fr 340px;\r\n    min-height: 28px;\r\n" +
                    "  }\r\n\r\n  .hero-banner::before {\r\n    content: \'\';\r\n    position: absolute; top: " +
                    "-100px; right: 280px;\r\n    width: 420px; height: 420px;\r\n    background: radial-" +
                    "gradient(circle, rgba(245,197,66,0.10) 0%, transparent 65%);\r\n    pointer-events" +
                    ": none;\r\n  }\r\n  .hero-banner::after {\r\n    content: \'\';\r\n    position: absolute;" +
                    " bottom: -80px; left: 20%;\r\n    width: 300px; height: 300px;\r\n    background: ra" +
                    "dial-gradient(circle, rgba(8,21,71,0.4) 0%, transparent 70%);\r\n    pointer-event" +
                    "s: none;\r\n  }\r\n\r\n  /* floating shapes */\r\n  .hero-shapes {\r\n    position: absolu" +
                    "te; inset: 0; pointer-events: none; overflow: hidden;\r\n  }\r\n  .shape {\r\n    posi" +
                    "tion: absolute; border-radius: 50%;\r\n    border: 1px solid rgba(255,255,255,0.07" +
                    ");\r\n  }\r\n  .shape-1 { width: 200px; height: 200px; top: -60px; right: 300px; bor" +
                    "der-color: rgba(245,197,66,0.12); }\r\n  .shape-2 { width: 120px; height: 120px; b" +
                    "ottom: -30px; right: 380px; border-color: rgba(255,255,255,0.06); }\r\n  .shape-3 " +
                    "{ width: 60px; height: 60px; top: 40px; right: 440px; background: rgba(245,197,6" +
                    "6,0.05); border: none; }\r\n\r\n  .hero-content {\r\n    padding: 44px 44px 40px;\r\n   " +
                    " display: flex; flex-direction: column;\r\n    justify-content: center;\r\n    posit" +
                    "ion: relative; z-index: 2;\r\n  }\r\n\r\n/*  .hero-badge {\r\n    display: inline-flex; " +
                    "align-items: center; gap: 8px;\r\n    background: rgba(255,255,255,0.08);\r\n    bor" +
                    "der: 1px solid rgba(255,255,255,0.13);\r\n    color: rgba(255,255,255,0.75);\r\n    " +
                    "font-size: 11px; font-weight: 700;\r\n    padding: 5px 14px; border-radius: 50px;\r" +
                    "\n    font-family: \'Sora\', sans-serif;\r\n    letter-spacing: 0.5px;\r\n    margin-bo" +
                    "ttom: 18px;\r\n    width: fit-content;\r\n  }*/\r\n\r\n/*  .hero-badge .dot {\r\n    width" +
                    ": 6px; height: 6px; border-radius: 50%;\r\n    background: #F5C542;\r\n    box-shado" +
                    "w: 0 0 6px #F5C542;\r\n    animation: pulse 2s ease-in-out infinite;\r\n  }*/\r\n  @ke" +
                    "yframes pulse {\r\n    0%,100% { opacity: 1; transform: scale(1); }\r\n    50% { opa" +
                    "city: 0.5; transform: scale(0.8); }\r\n  }\r\n\r\n  .hero-title {\r\n    font-family: \'S" +
                    "ora\', sans-serif;\r\n    font-size: 34px; font-weight: 800;\r\n    color: white; lin" +
                    "e-height: 1.15;\r\n    letter-spacing: -0.8px;\r\n    margin-bottom: 10px;\r\n  }\r\n  ." +
                    "hero-title .highlight { color: #F5C542; }\r\n  .hero-title .separator {\r\n    color" +
                    ": rgba(255,255,255,0.25);\r\n    font-weight: 300; margin: 0 8px;\r\n  }\r\n\r\n\r\n\r\n  .h" +
                    "ero-mini-stats {\r\n    display: flex; gap: 0; margin-bottom: 30px;\r\n  }\r\n  .hms-i" +
                    "tem {\r\n    display: flex; flex-direction: column; gap: 2px;\r\n    padding-right: " +
                    "22px;\r\n  }\r\n  .hms-item + .hms-item {\r\n    padding-left: 22px;\r\n    border-left:" +
                    " 1px solid rgba(255,255,255,0.1);\r\n  }\r\n  .hms-val {\r\n    font-family: \'Sora\', s" +
                    "ans-serif;\r\n    font-size: 24px; font-weight: 800; color: white;\r\n  }\r\n  .hms-va" +
                    "l span { color: #F5C542; font-size: 16px; }\r\n  .hms-lbl {\r\n    font-size: 10px; " +
                    "font-weight: 600;\r\n    color: rgba(255,255,255,0.38);\r\n    text-transform: upper" +
                    "case; letter-spacing: 0.9px;\r\n  }\r\n\r\n\r\n  .btn-pink {\r\n    display: inline-flex; " +
                    "align-items: center; gap: 9px;\r\n    background: var(--pink);\r\n    color: white;\r" +
                    "\n    font-family: \'Sora\', sans-serif;\r\n    font-weight: 700; font-size: 13.5px;\r" +
                    "\n    padding: 12px 24px; border-radius: 12px;\r\n    border: none; cursor: pointer" +
                    ";\r\n    transition: var(--ease);\r\n    box-shadow: 0 4px 20px rgba(255,45,141,0.45" +
                    ");\r\n    letter-spacing: 0.2px;\r\n  }\r\n  .btn-pink:hover {\r\n    background: var(--" +
                    "pink-dark);\r\n    transform: translateY(-2px);\r\n    box-shadow: 0 8px 28px rgba(2" +
                    "55,45,141,0.55);\r\n  }\r\n\r\n\r\n\r\n  /* illustration panel */\r\n  .hero-visual {\r\n    p" +
                    "osition: relative; z-index: 2;\r\n    display: flex; align-items: flex-end; justif" +
                    "y-content: center;\r\n    padding: 0 20px 0 0;\r\n    overflow: hidden;\r\n  }\r\n\r\n  /*" +
                    " SVG illustration placeholder */\r\n  .hero-illustration {\r\n    width: 100%; heigh" +
                    "t: 100%;\r\n    display: flex; align-items: flex-end; justify-content: center;\r\n  " +
                    "  position: relative;\r\n  }\r\n\r\n  .ilu-glow {\r\n    position: absolute; bottom: 0; " +
                    "left: 50%;\r\n    transform: translateX(-50%);\r\n    width: 260px; height: 120px;\r\n" +
                    "    background: radial-gradient(ellipse, rgba(245,197,66,0.15) 0%, transparent 7" +
                    "0%);\r\n    pointer-events: none;\r\n  }\r\n\r\n  .student-fig {\r\n    width: 240px; heig" +
                    "ht: 260px;\r\n    position: relative;\r\n    flex-shrink: 0;\r\n  }\r\n\r\n  /* floating b" +
                    "adges on illustration */\r\n  .ilu-badge {\r\n    position: absolute;\r\n    backgroun" +
                    "d: white;\r\n    border-radius: 14px;\r\n    padding: 9px 14px;\r\n    box-shadow: 0 8" +
                    "px 28px rgba(8,21,71,0.22);\r\n    display: flex; align-items: center; gap: 8px;\r\n" +
                    "    white-space: nowrap;\r\n    animation: float 3s ease-in-out infinite;\r\n  }\r\n  " +
                    ".ilu-badge:nth-child(2) { animation-delay: 1.2s; }\r\n  .ilu-badge:nth-child(3) { " +
                    "animation-delay: 2.1s; }\r\n\r\n  @keyframes float {\r\n    0%,100% { transform: trans" +
                    "lateY(0); }\r\n    50% { transform: translateY(-6px); }\r\n  }\r\n\r\n  .ib-1 { top: 30p" +
                    "x; left: -20px; }\r\n  .ib-2 { top: 110px; right: -24px; }\r\n  .ib-3 { bottom: 68px" +
                    "; left: -30px; }\r\n\r\n  .ib-icon {\r\n    width: 30px; height: 30px; border-radius: " +
                    "8px;\r\n    display: flex; align-items: center; justify-content: center;\r\n    font" +
                    "-size: 15px; flex-shrink: 0;\r\n  }\r\n  .ib-icon.blue { background: rgba(11,31,102," +
                    "0.1); }\r\n  .ib-icon.pink { background: rgba(255,45,141,0.1); }\r\n  .ib-icon.green" +
                    " { background: rgba(16,185,129,0.1); }\r\n  .ib-txt strong { font-family: \'Sora\', " +
                    "sans-serif; font-size: 12px; font-weight: 700; color: var(--primary); display: b" +
                    "lock; line-height: 1.2; }\r\n  .ib-txt span { font-size: 10px; color: var(--text-s" +
                    "econdary); }\r\n\r\n\r\n\r\n  /* ══ COURSE CARDS ══ */\r\n  .course-cards {\r\n    display: " +
                    "grid; grid-template-columns: 1fr 1fr;\r\n    gap: 18px; margin-bottom: 28px;\r\n  }\r" +
                    "\n\r\n  .course-card {\r\n    background: white;\r\n    border-radius: 20px;\r\n    borde" +
                    "r: 2px solid var(--border);\r\n    overflow: hidden;\r\n    box-shadow: var(--shadow" +
                    "-sm);\r\n    transition: var(--ease);\r\n    cursor: pointer;\r\n    position: relativ" +
                    "e;\r\n  }\r\n  .course-card:hover {\r\n    border-color: var(--pink);\r\n    box-shadow:" +
                    " 0 12px 40px var(--pink-glow);\r\n    transform: translateY(-3px);\r\n  }\r\n  .course" +
                    "-card.selected {\r\n    border-color: var(--pink);\r\n    box-shadow: 0 10px 36px va" +
                    "r(--pink-glow);\r\n  }\r\n\r\n  .cc-header {\r\n    padding: 22px 24px 18px;\r\n    displa" +
                    "y: flex; align-items: flex-start; gap: 14px;\r\n    position: relative;\r\n  }\r\n\r\n  " +
                    ".cc-icon {\r\n    width: 50px; height: 50px;\r\n    border-radius: 14px;\r\n    displa" +
                    "y: flex; align-items: center; justify-content: center;\r\n    font-size: 24px; fle" +
                    "x-shrink: 0;\r\n  }\r\n  .cc-icon.bit { background: rgba(11,31,102,0.08); }\r\n  .cc-i" +
                    "con.bcs { background: rgba(255,45,141,0.09); }\r\n\r\n  .cc-info { flex: 1; }\r\n  .cc" +
                    "-abbr {\r\n    font-family: \'Sora\', sans-serif;\r\n    font-size: 22px; font-weight:" +
                    " 800;\r\n    color: var(--primary);\r\n    letter-spacing: -0.5px;\r\n    line-height:" +
                    " 1;\r\n  }\r\n  .cc-name {\r\n    font-size: 11.5px; color: var(--text-secondary);\r\n  " +
                    "  margin-top: 4px; line-height: 1.3;\r\n  }\r\n\r\n  .cc-badge {\r\n    position: absolu" +
                    "te; top: 18px; right: 20px;\r\n    font-size: 10px; font-weight: 700;\r\n    font-fa" +
                    "mily: \'Sora\', sans-serif;\r\n    padding: 4px 11px; border-radius: 50px;\r\n    lett" +
                    "er-spacing: 0.4px;\r\n  }\r\n  .cc-badge.popular { background: rgba(255,45,141,0.12)" +
                    "; color: var(--pink); }\r\n  .cc-badge.new { background: rgba(11,31,102,0.08); col" +
                    "or: var(--primary); }\r\n\r\n  .cc-divider { height: 1px; background: var(--border);" +
                    " margin: 0 24px; }\r\n\r\n  .cc-body { padding: 18px 24px 22px; }\r\n\r\n  .cc-desc {\r\n " +
                    "   font-size: 13px; color: var(--text-secondary);\r\n    line-height: 1.6; margin-" +
                    "bottom: 16px;\r\n  }\r\n\r\n  .cc-features {\r\n    display: flex; flex-direction: colum" +
                    "n; gap: 6px;\r\n    margin-bottom: 18px;\r\n  }\r\n  .cc-feat {\r\n    display: flex; al" +
                    "ign-items: center; gap: 9px;\r\n    font-size: 12.5px; color: var(--text-primary);" +
                    "\r\n  }\r\n  .feat-dot {\r\n    width: 18px; height: 18px; border-radius: 5px;\r\n    ba" +
                    "ckground: var(--pink-soft);\r\n    display: flex; align-items: center; justify-con" +
                    "tent: center;\r\n    flex-shrink: 0;\r\n    font-size: 10px;\r\n  }\r\n\r\n  .cc-footer {\r" +
                    "\n    display: flex; align-items: center; justify-content: space-between;\r\n    pa" +
                    "dding: 14px 24px 16px;\r\n    background: rgba(11,31,102,0.025);\r\n    border-top: " +
                    "1px solid var(--border);\r\n  }\r\n  .cc-meta {\r\n    display: flex; gap: 16px;\r\n  }\r" +
                    "\n  .cm-item {\r\n    display: flex; flex-direction: column; gap: 1px;\r\n  }\r\n  .cm-" +
                    "val {\r\n    font-family: \'Sora\', sans-serif;\r\n    font-size: 15px; font-weight: 7" +
                    "00;\r\n    color: var(--primary);\r\n  }\r\n  .cm-lbl {\r\n    font-size: 10px; color: v" +
                    "ar(--text-light);\r\n    text-transform: uppercase; letter-spacing: 0.7px;\r\n    fo" +
                    "nt-weight: 600;\r\n  }\r\n\r\n  .cc-cta {\r\n    display: inline-flex; align-items: cent" +
                    "er; gap: 8px;\r\n    background: var(--primary);\r\n    color: white;\r\n    font-fami" +
                    "ly: \'Sora\', sans-serif;\r\n    font-weight: 700; font-size: 12.5px;\r\n    padding: " +
                    "10px 18px; border-radius: 10px;\r\n    border: none; cursor: pointer;\r\n    transit" +
                    "ion: var(--ease);\r\n    letter-spacing: 0.2px;\r\n  }\r\n  .cc-cta:hover { background" +
                    ": var(--pink); box-shadow: 0 4px 16px rgba(255,45,141,0.4); transform: translate" +
                    "Y(-1px); }\r\n  .course-card.selected .cc-cta { background: var(--pink); box-shado" +
                    "w: 0 4px 16px rgba(255,45,141,0.35); }\r\n\r\n\r\n\r\n  /* ══ AFFILIATION BANNER ══ */\r\n" +
                    "  .affil-banner {\r\n    background: linear-gradient(135deg, var(--secondary) 0%, " +
                    "var(--primary) 60%, #162077 100%);\r\n    border-radius: 20px;\r\n    padding: 28px " +
                    "36px;\r\n    display: flex; align-items: center; gap: 32px;\r\n    position: relativ" +
                    "e; overflow: hidden;\r\n    box-shadow: var(--shadow-md);\r\n    margin-bottom: 28px" +
                    ";\r\n  }\r\n  .affil-banner::before {\r\n    content: \'\';\r\n    position: absolute; top" +
                    ": -60px; right: -60px;\r\n    width: 260px; height: 260px;\r\n    background: radial" +
                    "-gradient(circle, rgba(255,45,141,0.15) 0%, transparent 65%);\r\n    pointer-event" +
                    "s: none;\r\n  }\r\n\r\n  .affil-left {\r\n    flex-shrink: 0;\r\n    display: flex; flex-d" +
                    "irection: column; gap: 4px;\r\n  }\r\n  .affil-label {\r\n    font-size: 10px; font-we" +
                    "ight: 700;\r\n    color: rgba(255,255,255,0.4);\r\n    text-transform: uppercase; le" +
                    "tter-spacing: 1.5px;\r\n    font-family: \'Sora\', sans-serif;\r\n  }\r\n  .affil-name {" +
                    "\r\n    font-family: \'Sora\', sans-serif;\r\n    font-size: 20px; font-weight: 800;\r\n" +
                    "    color: white; letter-spacing: -0.3px;\r\n  }\r\n  .affil-name span { color: var(" +
                    "--pink); }\r\n  .affil-sub {\r\n    font-size: 12px; color: rgba(255,255,255,0.45);\r" +
                    "\n    margin-top: 2px;\r\n  }\r\n\r\n  .affil-divider {\r\n    width: 1px; height: 54px;\r" +
                    "\n    background: rgba(255,255,255,0.12);\r\n    flex-shrink: 0;\r\n  }\r\n\r\n  .affil-p" +
                    "ills {\r\n    display: flex; gap: 10px; flex-wrap: wrap; flex: 1;\r\n  }\r\n  .apill {" +
                    "\r\n    display: inline-flex; align-items: center; gap: 7px;\r\n    background: rgba" +
                    "(255,255,255,0.08);\r\n    border: 1px solid rgba(255,255,255,0.12);\r\n    border-r" +
                    "adius: 10px;\r\n    padding: 9px 14px;\r\n    font-size: 12px; font-weight: 500;\r\n  " +
                    "  color: rgba(255,255,255,0.75);\r\n    transition: var(--ease);\r\n  }\r\n  .apill:ho" +
                    "ver { background: rgba(255,255,255,0.14); color: white; border-color: rgba(255,4" +
                    "5,141,0.4); }\r\n  .apill-icon { font-size: 15px; }\r\n\r\n  .affil-right {\r\n    flex-" +
                    "shrink: 0;\r\n  }\r\n\r\n  .btn-learn {\r\n    display: inline-flex; align-items: center" +
                    "; gap: 9px;\r\n    background: white;\r\n    color: var(--primary);\r\n    font-family" +
                    ": \'Sora\', sans-serif;\r\n    font-weight: 700; font-size: 13px;\r\n    padding: 12px" +
                    " 22px; border-radius: 12px;\r\n    border: none; cursor: pointer;\r\n    transition:" +
                    " var(--ease);\r\n    box-shadow: 0 4px 16px rgba(0,0,0,0.12);\r\n    white-space: no" +
                    "wrap;\r\n  }\r\n  .btn-learn:hover { background: var(--pink); color: white; transfor" +
                    "m: translateY(-2px); box-shadow: 0 8px 24px rgba(255,45,141,0.4); }\r\n\r\n  /* ══ Q" +
                    "UICK STATS ROW ══ */\r\n  .stats-row {\r\n    display: grid; grid-template-columns: " +
                    "repeat(4, 1fr);\r\n    gap: 16px; margin-bottom: 28px;\r\n  }\r\n\r\n  .stat-card {\r\n   " +
                    " background: white; border-radius: 16px;\r\n    border: 1.5px solid var(--border);" +
                    "\r\n    padding: 20px;\r\n    display: flex; align-items: center; gap: 14px;\r\n    bo" +
                    "x-shadow: var(--shadow-sm);\r\n    transition: var(--ease);\r\n  }\r\n  .stat-card:hov" +
                    "er {\r\n    border-color: var(--pink);\r\n    box-shadow: 0 6px 24px var(--pink-glow" +
                    ");\r\n    transform: translateY(-2px);\r\n  }\r\n  .sc-icon {\r\n    width: 44px; height" +
                    ": 44px; border-radius: 12px;\r\n    display: flex; align-items: center; justify-co" +
                    "ntent: center;\r\n    font-size: 20px; flex-shrink: 0;\r\n  }\r\n  .sc-icon.blue { bac" +
                    "kground: rgba(11,31,102,0.08); }\r\n  .sc-icon.green { background: rgba(16,185,129" +
                    ",0.1); }\r\n  .sc-icon.pink { background: rgba(255,45,141,0.1); }\r\n  .sc-icon.ambe" +
                    "r { background: rgba(245,158,11,0.1); }\r\n  .sc-val { font-family: \'Sora\', sans-s" +
                    "erif; font-size: 22px; font-weight: 700; color: var(--primary); }\r\n  .sc-lbl { f" +
                    "ont-size: 11px; color: var(--text-secondary); margin-top: 1px; }\r\n\r\n  /* ══ ABOU" +
                    "T SECTION ══ */\r\n  .about-section {\r\n    display: grid;\r\n    grid-template-colum" +
                    "ns: 1fr 360px;\r\n    gap: 32px;\r\n    margin-bottom: 28px;\r\n    align-items: start" +
                    ";\r\n  }\r\n\r\n  .about-left {\r\n    background: white;\r\n    border-radius: 22px;\r\n   " +
                    " border: 1.5px solid var(--border);\r\n    padding: 36px 38px 32px;\r\n    box-shado" +
                    "w: var(--shadow-sm);\r\n  }\r\n\r\n  .about-label {\r\n    font-size: 11px; font-weight:" +
                    " 700;\r\n    text-transform: uppercase; letter-spacing: 1.8px;\r\n    color: var(--p" +
                    "ink);\r\n    font-family: \'Sora\', sans-serif;\r\n    margin-bottom: 10px;\r\n  }\r\n\r\n  " +
                    ".about-heading {\r\n    font-family: \'Sora\', sans-serif;\r\n    font-size: 26px; fon" +
                    "t-weight: 800;\r\n    color: var(--primary);\r\n    letter-spacing: -0.5px;\r\n    lin" +
                    "e-height: 1.2;\r\n    margin-bottom: 20px;\r\n  }\r\n  .about-heading span { color: #1" +
                    "6a34a; }\r\n\r\n  .about-para {\r\n    font-size: 14px;\r\n    color: #374151;\r\n    line" +
                    "-height: 1.75;\r\n    margin-bottom: 14px;\r\n  }\r\n  .about-para strong { color: var" +
                    "(--primary); font-weight: 700; }\r\n  .about-para:last-of-type { margin-bottom: 24" +
                    "px; }\r\n\r\n  .about-highlights {\r\n    display: flex; flex-direction: column; gap: " +
                    "12px;\r\n    margin-bottom: 28px;\r\n    padding: 20px;\r\n    background: var(--bg);\r" +
                    "\n    border-radius: 14px;\r\n    border: 1.5px solid var(--border);\r\n  }\r\n\r\n  .ah-" +
                    "card {\r\n    display: flex; align-items: flex-start; gap: 12px;\r\n    padding: 14p" +
                    "x 16px;\r\n    background: white;\r\n    border-radius: 12px;\r\n    border: 1px solid" +
                    " var(--border);\r\n    box-shadow: var(--shadow-sm);\r\n    transition: var(--ease);" +
                    "\r\n  }\r\n  .ah-card:hover { border-color: var(--pink); box-shadow: 0 4px 16px var(" +
                    "--pink-glow); }\r\n\r\n  .ah-icon {\r\n    width: 38px; height: 38px; border-radius: 1" +
                    "0px;\r\n    background: var(--pink-soft);\r\n    display: flex; align-items: center;" +
                    " justify-content: center;\r\n    font-size: 18px; flex-shrink: 0;\r\n  }\r\n  .ah-titl" +
                    "e {\r\n    font-family: \'Sora\', sans-serif;\r\n    font-size: 13px; font-weight: 700" +
                    ";\r\n    color: var(--primary); margin-bottom: 3px;\r\n  }\r\n  .ah-text {\r\n    font-s" +
                    "ize: 12px; color: var(--text-secondary); line-height: 1.5;\r\n  }\r\n\r\n  .about-btns" +
                    " { display: flex; gap: 12px; flex-wrap: wrap; }\r\n\r\n\r\n\r\n  /* ══ POSTER ══ */\r\n  ." +
                    "about-right {\r\n    position: sticky; top: calc(var(--header-h) + 20px);\r\n  }\r\n\r\n" +
                    "  .poster-wrap {\r\n    position: relative;\r\n  }\r\n  .poster-glow {\r\n    position: " +
                    "absolute; bottom: -20px; left: 50%;\r\n    transform: translateX(-50%);\r\n    width" +
                    ": 280px; height: 60px;\r\n    background: radial-gradient(ellipse, rgba(255,45,141" +
                    ",0.25) 0%, transparent 70%);\r\n    pointer-events: none;\r\n  }\r\n\r\n  .poster-card {" +
                    "\r\n    border-radius: 20px;\r\n    overflow: hidden;\r\n    box-shadow: 0 24px 64px r" +
                    "gba(8,21,71,0.28);\r\n    position: relative;\r\n  }\r\n\r\n  .poster-inner {\r\n    backg" +
                    "round: linear-gradient(160deg, #0047b3 0%, #0B1F66 35%, #081547 70%, #060e33 100" +
                    "%);\r\n    padding: 22px 20px 16px;\r\n    position: relative;\r\n    overflow: hidden" +
                    ";\r\n    min-height: 520px;\r\n  }\r\n  .poster-inner::before {\r\n    content: \'\';\r\n   " +
                    " position: absolute; top: -80px; right: -60px;\r\n    width: 280px; height: 280px;" +
                    "\r\n    background: radial-gradient(circle, rgba(255,45,141,0.15) 0%, transparent " +
                    "65%);\r\n    pointer-events: none;\r\n  }\r\n  .poster-inner::after {\r\n    content: \'\'" +
                    ";\r\n    position: absolute; top: 0; left: 0; right: 0; bottom: 0;\r\n    background" +
                    ": url(\"data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'60\' h" +
                    "eight=\'60\'%3E%3Cpath d=\'M30 0 L60 30 L30 60 L0 30Z\' stroke=\'rgba(255,255,255,0.0" +
                    "3)\' fill=\'none\'/%3E%3C/svg%3E\") repeat;\r\n    pointer-events: none;\r\n  }\r\n\r\n  .po" +
                    "ster-logos {\r\n    display: flex; align-items: center; justify-content: space-bet" +
                    "ween;\r\n    margin-bottom: 18px; position: relative; z-index: 2;\r\n  }\r\n  .poster-" +
                    "logo-tx {\r\n    display: flex; align-items: center; gap: 7px;\r\n  }\r\n  .tx-text-wr" +
                    "ap { display: flex; flex-direction: column; }\r\n  .tx-name {\r\n    font-family: \'S" +
                    "ora\', sans-serif;\r\n    font-size: 17px; font-weight: 900;\r\n    color: white; let" +
                    "ter-spacing: -0.3px; line-height: 1;\r\n  }\r\n  .tx-sub { font-size: 8px; color: rg" +
                    "ba(255,255,255,0.5); line-height: 1.2; }\r\n\r\n  .poster-logo-luc {\r\n    display: f" +
                    "lex; align-items: center; gap: 6px;\r\n  }\r\n  .luc-seal {\r\n    width: 28px; height" +
                    ": 28px; border-radius: 50%;\r\n    background: #c8102e;\r\n    display: flex; align-" +
                    "items: center; justify-content: center;\r\n    font-family: \'Sora\', sans-serif;\r\n " +
                    "   font-weight: 800; font-size: 8px; color: white;\r\n    border: 2px solid rgba(2" +
                    "55,255,255,0.3);\r\n    flex-shrink: 0;\r\n  }\r\n  .luc-name {\r\n    font-size: 8px; f" +
                    "ont-weight: 700;\r\n    color: rgba(255,255,255,0.75);\r\n    line-height: 1.4;\r\n   " +
                    " font-family: \'Sora\', sans-serif;\r\n    letter-spacing: 0.3px;\r\n  }\r\n\r\n  .poster-" +
                    "tagline {\r\n    font-family: \'Sora\', sans-serif;\r\n    font-size: 11px; font-weigh" +
                    "t: 600;\r\n    color: rgba(255,255,255,0.65);\r\n    letter-spacing: 1.5px;\r\n    mar" +
                    "gin-bottom: 2px;\r\n    position: relative; z-index: 2;\r\n  }\r\n  .poster-main-title" +
                    " {\r\n    font-family: \'Sora\', sans-serif;\r\n    font-size: 30px; font-weight: 900;" +
                    "\r\n    color: #00c8ff;\r\n    line-height: 1.05;\r\n    letter-spacing: -0.5px;\r\n    " +
                    "margin-bottom: 14px;\r\n    position: relative; z-index: 2;\r\n  }\r\n  .poster-degree" +
                    "-row { display: flex; align-items: center; gap: 12px; position: relative; z-inde" +
                    "x: 2; }\r\n  .poster-degree-title {\r\n    font-family: \'Sora\', sans-serif;\r\n    fon" +
                    "t-size: 36px; font-weight: 900;\r\n    color: white;\r\n    letter-spacing: -1px;\r\n " +
                    "   line-height: 1;\r\n    position: relative; z-index: 2;\r\n  }\r\n  .poster-degree-s" +
                    "ub {\r\n    font-size: 11px; color: rgba(255,255,255,0.6);\r\n    line-height: 1.4; " +
                    "margin-bottom: 16px;\r\n    position: relative; z-index: 2;\r\n  }\r\n  .poster-degree" +
                    "-sub strong { color: rgba(255,255,255,0.9); }\r\n\r\n  .poster-why-box {\r\n    backgr" +
                    "ound: rgba(255,255,255,0.08);\r\n    border: 1px solid rgba(255,255,255,0.12);\r\n  " +
                    "  border-radius: 12px;\r\n    padding: 14px 16px;\r\n    margin-bottom: 14px;\r\n    p" +
                    "osition: relative; z-index: 2;\r\n    max-width: 175px;\r\n  }\r\n  .pwb-title {\r\n    " +
                    "font-family: \'DM Sans\', sans-serif;\r\n    font-size: 13px; color: rgba(255,255,25" +
                    "5,0.75);\r\n    margin-bottom: 10px; line-height: 1.4;\r\n  }\r\n  .pwb-title span {\r\n" +
                    "    font-family: \'Sora\', sans-serif;\r\n    font-size: 16px; font-weight: 900;\r\n  " +
                    "  color: #00c8ff;\r\n  }\r\n  .pwb-item {\r\n    font-size: 11px; color: rgba(255,255," +
                    "255,0.65);\r\n    margin-bottom: 5px; display: flex; align-items: center; gap: 4px" +
                    ";\r\n  }\r\n  .pwb-item::before { content: \'\'; }\r\n\r\n  .poster-admission {\r\n    posit" +
                    "ion: absolute; bottom: 50px; right: 16px;\r\n    z-index: 3; text-align: right;\r\n " +
                    " }\r\n  .pa-open {\r\n    font-family: \'Sora\', sans-serif;\r\n    font-size: 20px; fon" +
                    "t-weight: 900;\r\n    color: white; line-height: 1.1;\r\n    letter-spacing: -0.5px;" +
                    "\r\n    text-shadow: 0 2px 8px rgba(0,0,0,0.3);\r\n  }\r\n  .pa-intake {\r\n    font-siz" +
                    "e: 11px; color: rgba(255,255,255,0.6);\r\n    margin-top: 2px;\r\n  }\r\n\r\n  .poster-s" +
                    "tudent {\r\n    position: absolute; bottom: 0; right: -8px;\r\n    z-index: 2;\r\n  }\r" +
                    "\n\r\n  .poster-footer {\r\n    border-top: 1px solid rgba(255,255,255,0.1);\r\n    pad" +
                    "ding-top: 10px;\r\n    margin-top: 4px;\r\n    position: relative; z-index: 2;\r\n  }\r" +
                    "\n  .pf-item {\r\n    font-size: 9.5px; color: rgba(255,255,255,0.5);\r\n    margin-b" +
                    "ottom: 3px;\r\n  }\r\n\r\n  @media (max-width: 1100px) {\r\n    .about-section { grid-te" +
                    "mplate-columns: 1fr; }\r\n    .about-right { position: static; }\r\n    .poster-card" +
                    " { max-width: 360px; }\r\n  }\r\n\r\n  /* ══ FADE ANIMATIONS ══ */\r\n  .fade-up {\r\n    " +
                    "opacity: 0;\r\n    transform: translateY(22px);\r\n    animation: fadeUp 0.55s cubic" +
                    "-bezier(0.22,1,0.36,1) forwards;\r\n  }\r\n  .d1 { animation-delay: 0.05s; }\r\n  .d2 " +
                    "{ animation-delay: 0.15s; }\r\n  .d3 { animation-delay: 0.25s; }\r\n  .d4 { animatio" +
                    "n-delay: 0.35s; }\r\n  .d5 { animation-delay: 0.45s; }\r\n  .d6 { animation-delay: 0" +
                    ".55s; }\r\n\r\n  @keyframes fadeUp {\r\n    to { opacity: 1; transform: translateY(0);" +
                    " }\r\n  }\r\n\r\n  /* overlay */\r\n  .overlay {\r\n    display: none; position: fixed; in" +
                    "set: 0;\r\n    background: rgba(8,21,71,0.4);\r\n    z-index: 140; backdrop-filter: " +
                    "blur(4px);\r\n  }\r\n  .overlay.show { display: block; }\r\n\r\n  /* ══ RESPONSIVE ══ */" +
                    "\r\n  @media (max-width: 1100px) {\r\n    .why-grid { grid-template-columns: repeat(" +
                    "2, 1fr); }\r\n    .affil-banner { flex-wrap: wrap; gap: 20px; }\r\n    .affil-divide" +
                    "r { display: none; }\r\n  }\r\n\r\n  @media (max-width: 900px) {\r\n    :root { --sideba" +
                    "r-w: 0px; }\r\n    .sidebar { left: -265px; width: 265px; }\r\n    .sidebar.open { l" +
                    "eft: 0; }\r\n    .main { margin-left: 0; width: 100%; }\r\n    .header-logo { width:" +
                    " auto; border-right: none; }\r\n    .sidebar-toggle { display: flex; }\r\n    .hero-" +
                    "banner { grid-template-columns: 1fr; }\r\n    .hero-visual { display: none; }\r\n   " +
                    " .course-cards { grid-template-columns: 1fr; }\r\n    .stats-row { grid-template-c" +
                    "olumns: repeat(2, 1fr); }\r\n    .why-grid { grid-template-columns: 1fr; }\r\n  }\r\n\r" +
                    "\n  @media (max-width: 600px) {\r\n    .main-inner { padding: 20px 16px; }\r\n    .he" +
                    "ro-content { padding: 28px 24px; }\r\n    .hero-title { font-size: 24px; }\r\n    .a" +
                    "ffil-banner { padding: 20px 20px; }\r\n    .stats-row { grid-template-columns: 1fr" +
                    " 1fr; }\r\n  }\r\n\r\n\r\n  /* ── Master Page overrides: neutralise standalone layout ──" +
                    " */\r\n  header { display: none !important; }\r\n  .sidebar { display: none !importa" +
                    "nt; }\r\n  .overlay { display: none !important; }\r\n  body { padding-top: 0 !import" +
                    "ant; background: var(--bg) !important; }\r\n  .main { margin-left: 0 !important; p" +
                    "adding-top: 0 !important; width: 100% !important; }\r\n  .main-inner { padding: 24" +
                    "px 32px !important; }\r\n\r\n</style>\r\n\r\n<main class=\"main\">\r\n  <div class=\"main-inn" +
                    "er\">\r\n\r\n\r\n\r\n    <!-- HERO BANNER -->\r\n    <div class=\"hero-banner fade-up d1\">\r\n" +
                    "      <div class=\"hero-shapes\">\r\n        <div class=\"shape shape-1\"></div>\r\n    " +
                    "    <div class=\"shape shape-2\"></div>\r\n        <div class=\"shape shape-3\"></div>" +
                    "\r\n      </div>\r\n\r\n      <div class=\"hero-content\">\r\n        \r\n\r\n        <div cla" +
                    "ss=\"hero-title\">\r\n          Shape the Future<br>\r\n          <span class=\"highlig" +
                    "ht\">with Technology</span>\r\n        </div>\r\n\r\n\r\n        <div class=\"hero-mini-st" +
                    "ats\">\r\n          <div class=\"hms-item\">\r\n            <div class=\"hms-val\">4<span" +
                    ">yr</span></div>\r\n            <div class=\"hms-lbl\">Program</div>\r\n          </di" +
                    "v>\r\n          <div class=\"hms-item\">\r\n            <div class=\"hms-val\">8</div>\r\n" +
                    "            <div class=\"hms-lbl\">Semesters</div>\r\n          </div>\r\n          <d" +
                    "iv class=\"hms-item\">\r\n            <div class=\"hms-val\">120</div>\r\n            <d" +
                    "iv class=\"hms-lbl\">Credit Hours</div>\r\n          </div>\r\n          <div class=\"h" +
                    "ms-item\">\r\n            <div class=\"hms-val\">7000<span>+</span></div>\r\n          " +
                    "  <div class=\"hms-lbl\">Graduates</div>\r\n          </div>\r\n        </div>\r\n\r\n    " +
                    " \r\n      </div>\r\n\r\n      <!-- ILLUSTRATION PANEL -->\r\n      <div class=\"hero-vis" +
                    "ual\">\r\n        <div class=\"hero-illustration\">\r\n          <div class=\"ilu-glow\">" +
                    "</div>\r\n\r\n          <!-- SVG Student Illustration -->\r\n          <svg class=\"stu" +
                    "dent-fig\" viewBox=\"0 0 240 280\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\r" +
                    "\n            <!-- body / suit -->\r\n            <rect x=\"68\" y=\"155\" width=\"104\" " +
                    "height=\"125\" rx=\"14\" fill=\"#1a2e6e\"/>\r\n            <!-- shirt / tie area -->\r\n  " +
                    "          <rect x=\"108\" y=\"155\" width=\"24\" height=\"80\" rx=\"4\" fill=\"#0B1F66\"/>\r\n" +
                    "            <polygon points=\"120,162 115,190 120,196 125,190\" fill=\"#FF2D8D\"/>\r\n" +
                    "            <!-- collar -->\r\n            <polygon points=\"108,155 120,175 132,15" +
                    "5 118,160\" fill=\"white\" opacity=\"0.9\"/>\r\n            <polygon points=\"132,155 12" +
                    "0,175 108,155 122,160\" fill=\"#e0e4f0\" opacity=\"0.9\"/>\r\n            <!-- arms -->" +
                    "\r\n            <rect x=\"38\" y=\"158\" width=\"36\" height=\"92\" rx=\"14\" fill=\"#1a2e6e\"" +
                    "/>\r\n            <rect x=\"166\" y=\"158\" width=\"36\" height=\"92\" rx=\"14\" fill=\"#1a2e" +
                    "6e\"/>\r\n            <!-- hand left -->\r\n            <ellipse cx=\"56\" cy=\"256\" rx=" +
                    "\"16\" ry=\"12\" fill=\"#f5c5a3\"/>\r\n            <!-- hand right holding cube -->\r\n   " +
                    "         <ellipse cx=\"184\" cy=\"253\" rx=\"16\" ry=\"12\" fill=\"#f5c5a3\"/>\r\n          " +
                    "  <!-- rubiks cube -->\r\n            <rect x=\"188\" y=\"228\" width=\"38\" height=\"38\"" +
                    " rx=\"6\" fill=\"#222\"/>\r\n            <rect x=\"190\" y=\"230\" width=\"10\" height=\"10\" " +
                    "rx=\"2\" fill=\"#FF2D8D\"/>\r\n            <rect x=\"203\" y=\"230\" width=\"10\" height=\"10" +
                    "\" rx=\"2\" fill=\"#4ade80\"/>\r\n            <rect x=\"216\" y=\"230\" width=\"8\" height=\"1" +
                    "0\" rx=\"2\" fill=\"#60a5fa\"/>\r\n            <rect x=\"190\" y=\"243\" width=\"10\" height=" +
                    "\"10\" rx=\"2\" fill=\"#fbbf24\"/>\r\n            <rect x=\"203\" y=\"243\" width=\"10\" heigh" +
                    "t=\"10\" rx=\"2\" fill=\"#FF2D8D\"/>\r\n            <rect x=\"216\" y=\"243\" width=\"8\" heig" +
                    "ht=\"10\" rx=\"2\" fill=\"#4ade80\"/>\r\n            <rect x=\"190\" y=\"256\" width=\"10\" he" +
                    "ight=\"8\" rx=\"2\" fill=\"#60a5fa\"/>\r\n            <rect x=\"203\" y=\"256\" width=\"10\" h" +
                    "eight=\"8\" rx=\"2\" fill=\"#fbbf24\"/>\r\n            <rect x=\"216\" y=\"256\" width=\"8\" h" +
                    "eight=\"8\" rx=\"2\" fill=\"#FF2D8D\"/>\r\n            <!-- neck -->\r\n            <rect " +
                    "x=\"108\" y=\"132\" width=\"24\" height=\"28\" rx=\"8\" fill=\"#f5c5a3\"/>\r\n            <!--" +
                    " head -->\r\n            <ellipse cx=\"120\" cy=\"110\" rx=\"46\" ry=\"50\" fill=\"#f5c5a3\"" +
                    "/>\r\n            <!-- hair -->\r\n            <path d=\"M74 96 Q76 52 120 50 Q164 52" +
                    " 166 96 Q155 72 120 70 Q85 72 74 96Z\" fill=\"#2d1a08\"/>\r\n            <!-- bun -->" +
                    "\r\n            <ellipse cx=\"120\" cy=\"55\" rx=\"20\" ry=\"14\" fill=\"#2d1a08\"/>\r\n      " +
                    "      <!-- facial features -->\r\n            <ellipse cx=\"108\" cy=\"114\" rx=\"6\" ry" +
                    "=\"7\" fill=\"white\"/>\r\n            <ellipse cx=\"132\" cy=\"114\" rx=\"6\" ry=\"7\" fill=\"" +
                    "white\"/>\r\n            <ellipse cx=\"109\" cy=\"115\" rx=\"3.5\" ry=\"4\" fill=\"#1a0a0a\"/" +
                    ">\r\n            <ellipse cx=\"133\" cy=\"115\" rx=\"3.5\" ry=\"4\" fill=\"#1a0a0a\"/>\r\n    " +
                    "        <ellipse cx=\"110\" cy=\"114\" rx=\"1.5\" ry=\"2\" fill=\"white\"/>\r\n            <" +
                    "ellipse cx=\"134\" cy=\"114\" rx=\"1.5\" ry=\"2\" fill=\"white\"/>\r\n            <!-- smile" +
                    " -->\r\n            <path d=\"M112 128 Q120 135 128 128\" stroke=\"#c27a5a\" stroke-wi" +
                    "dth=\"2\" fill=\"none\" stroke-linecap=\"round\"/>\r\n            <!-- eyebrows -->\r\n   " +
                    "         <path d=\"M102 107 Q108 104 114 106\" stroke=\"#2d1a08\" stroke-width=\"2.5\"" +
                    " fill=\"none\" stroke-linecap=\"round\"/>\r\n            <path d=\"M126 106 Q132 104 13" +
                    "8 107\" stroke=\"#2d1a08\" stroke-width=\"2.5\" fill=\"none\" stroke-linecap=\"round\"/>\r" +
                    "\n            <!-- laptop on lap -->\r\n            <rect x=\"72\" y=\"236\" width=\"96\"" +
                    " height=\"6\" rx=\"3\" fill=\"#374151\"/>\r\n            <rect x=\"78\" y=\"208\" width=\"84\"" +
                    " height=\"30\" rx=\"4\" fill=\"#1f2937\"/>\r\n            <rect x=\"80\" y=\"210\" width=\"80" +
                    "\" height=\"26\" rx=\"3\" fill=\"#0B1F66\"/>\r\n            <!-- code lines on screen -->" +
                    "\r\n            <rect x=\"84\" y=\"214\" width=\"28\" height=\"2\" rx=\"1\" fill=\"#FF2D8D\" o" +
                    "pacity=\"0.8\"/>\r\n            <rect x=\"84\" y=\"219\" width=\"44\" height=\"2\" rx=\"1\" fi" +
                    "ll=\"#60a5fa\" opacity=\"0.7\"/>\r\n            <rect x=\"84\" y=\"224\" width=\"36\" height" +
                    "=\"2\" rx=\"1\" fill=\"#4ade80\" opacity=\"0.7\"/>\r\n            <rect x=\"84\" y=\"229\" wid" +
                    "th=\"20\" height=\"2\" rx=\"1\" fill=\"#fbbf24\" opacity=\"0.7\"/>\r\n          </svg>\r\n\r\n  " +
                    "        <!-- Floating badges -->\r\n          <div class=\"ilu-badge ib-1\">\r\n      " +
                    "      <div class=\"ib-icon blue\">🎓</div>\r\n            <div class=\"ib-txt\">\r\n    " +
                    "          <strong>MQA Accredited</strong>\r\n              <span>Internationally r" +
                    "ecognised</span>\r\n            </div>\r\n          </div>\r\n\r\n          <div class=\"" +
                    "ilu-badge ib-2\">\r\n            <div class=\"ib-icon pink\">🔐</div>\r\n            <d" +
                    "iv class=\"ib-txt\">\r\n              <strong>CEH & CHFI Lab</strong>\r\n             " +
                    " <span>Hands-on security</span>\r\n            </div>\r\n          </div>\r\n\r\n       " +
                    "   <div class=\"ilu-badge ib-3\">\r\n            <div class=\"ib-icon green\">💼</div>" +
                    "\r\n            <div class=\"ib-txt\">\r\n              <strong>92% Placement</strong>" +
                    "\r\n              <span>2024 cohort</span>\r\n            </div>\r\n          </div>\r\n" +
                    "        </div>\r\n      </div>\r\n    </div>\r\n\r\n    <!-- ABOUT THE PROGRAM: two-colu" +
                    "mn prose + poster -->\r\n    <div class=\"about-section fade-up d2\" id=\"coursesSect" +
                    "ion\">\r\n      <div class=\"about-left\">\r\n        <div class=\"about-label\">About th" +
                    "e Program</div>\r\n        <h2 class=\"about-heading\">Nepal\'s Premier <span>BIT Deg" +
                    "ree</span></h2>\r\n\r\n        <p class=\"about-para\">\r\n        The <strong>Bachelor " +
                    "of Information Technology (BIT)</strong> at Texas College of Management and IT (" +
                    "TCMIT) is a 4-year, 8-semester program affiliated with <strong> Lincoln Universi" +
                    "ty College, Malaysia</strong>. Designed to blend technical theory with practical" +
                    " execution, the program covers software development, networking, databases, clou" +
                    "d computing, AI, and DevOps. With modern facilities like our IoT & Robotics labs" +
                    ", VFX Studio, and Incubation Center, students gain hands-on experience through p" +
                    "roject work and industry training to graduate completely career-ready\r\n        <" +
                    "/p>\r\n        <p class=\"about-para\">\r\n\r\n        To ensure our students are indust" +
                    "ry-ready from day one, Texas College integrates structured, After-Class Professi" +
                    "onal Classes directly into the academic timeline. Students will kickstart their " +
                    "first semester with foundational web design in <strong>HTML/CSS alongside hands-" +
                    "on IoT & Robotics engineering</strong>. Moving into the second semester, they wi" +
                    "ll begin building dynamic applications using React and Node.js, which seamlessly" +
                    " scales into your third and fourth semesters with<strong> Advanced React, Node.j" +
                    "s with Express, and Python Django</strong>. By the fifth semester and leading up" +
                    " to graduation, they will master the full MERN Stack to handle enterprise-level " +
                    "architectures.\r\n        </p>\r\n       <p class=\"about-para\">\r\n           Alongsid" +
                    "e this core development track, students\' journey includes specialized industry c" +
                    "ertifications to make you globally competitive. You will dive into professional<" +
                    "strong> Cisco Training and UI/UX / Multimedia design workshops, build cross-plat" +
                    "form mobile apps with React Native, and master Cybersecurity Essentials</strong>" +
                    ". Finally, students will achieve production-ready expertise in Cloud Foundations" +
                    " and Cloud Architecting running on Linux 9.0. This progressive curriculum aligns" +
                    " beautifully with the semester-by-semester navigation, giving prospective studen" +
                    "ts a clear, exciting view of their technical future.\r\n       </p>\r\n        \r\n\r\n " +
                    "       <div class=\"about-btns\">\r\n\r\n        </div>\r\n      </div>\r\n\r\n      <div cl" +
                    "ass=\"about-right\">\r\n        <div class=\"poster-wrap\">\r\n          <div class=\"pos" +
                    "ter-card\">\r\n            <div class=\"poster-inner\">\r\n              <div class=\"po" +
                    "ster-logos\">\r\n                <div class=\"poster-logo-tx\">\r\n                  \r\n" +
                    "                  <div class=\"tx-text-wrap\">\r\n                    <span class=\"t" +
                    "x-name\">Texas</span>\r\n                    <span class=\"tx-sub\">College of Manage" +
                    "ment &amp; IT</span>\r\n                  </div>\r\n                </div>\r\n        " +
                    "        <div class=\"poster-logo-luc\">\r\n                  <div class=\"luc-seal\">L" +
                    "UC</div>\r\n                  <span class=\"luc-name\">LINCOLN<br>UNIVERSITY<br>COLL" +
                    "EGE</span>\r\n                </div>\r\n              </div>\r\n\r\n              <div c" +
                    "lass=\"poster-tagline\">SHAPE THE FUTURE</div>\r\n              <div class=\"poster-m" +
                    "ain-title\">WITH<br>TECHNOLOGY</div>\r\n              <div class=\"poster-degree-row" +
                    "\">\r\n                <div class=\"poster-degree-title\">BIT</div>\r\n              </" +
                    "div>\r\n              <div class=\"poster-degree-sub\">Bachelor of (Hons.) in<br><st" +
                    "rong>Information Technology</strong></div>\r\n\r\n              <div class=\"poster-w" +
                    "hy-box\">\r\n                <div class=\"pwb-title\">Discover <span>BIT</span>at Tex" +
                    "as</div>\r\n                <div class=\"pwb-item\">▶ Learn by Building Real Project" +
                    "s</div>\r\n                <div class=\"pwb-item\">▶ Professional Skill Development<" +
                    "/div>\r\n                <div class=\"pwb-item\">▶ Career &amp; Internship Opportuni" +
                    "ties</div>\r\n                <div class=\"pwb-item\">▶ Workshops, Seminars &amp; Te" +
                    "ch Events</div>\r\n                <div class=\"pwb-item\">▶ Advanced IT Labs</div>\r" +
                    "\n              </div>\r\n\r\n              <div class=\"poster-admission\">\r\n         " +
                    "       <div class=\"pa-open\">ADMISSION<br>OPEN 2026</div>\r\n\r\n              </div>" +
                    "\r\n\r\n              <div class=\"poster-student\">\r\n                <svg viewBox=\"0 " +
                    "0 160 270\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\" width=\"155\" height=\"27" +
                    "0\">\r\n                  <rect x=\"38\" y=\"125\" width=\"84\" height=\"145\" rx=\"12\" fill" +
                    "=\"#1e3a8a\"/>\r\n                  <rect x=\"72\" y=\"125\" width=\"16\" height=\"70\" rx=\"" +
                    "3\" fill=\"#1a2e6e\"/>\r\n                  <polygon points=\"80,131 76,155 80,160 84," +
                    "155\" fill=\"#FF2D8D\"/>\r\n                  <polygon points=\"72,125 80,142 88,125 7" +
                    "9,129\" fill=\"white\" opacity=\"0.85\"/>\r\n                  <rect x=\"16\" y=\"128\" wid" +
                    "th=\"28\" height=\"84\" rx=\"12\" fill=\"#1e3a8a\"/>\r\n                  <rect x=\"116\" y=" +
                    "\"128\" width=\"28\" height=\"84\" rx=\"12\" fill=\"#1e3a8a\"/>\r\n                  <ellips" +
                    "e cx=\"30\" cy=\"218\" rx=\"13\" ry=\"10\" fill=\"#f5c5a3\"/>\r\n                  <ellipse " +
                    "cx=\"130\" cy=\"216\" rx=\"13\" ry=\"10\" fill=\"#f5c5a3\"/>\r\n                  <rect x=\"1" +
                    "32\" y=\"188\" width=\"32\" height=\"32\" rx=\"5\" fill=\"#111\"/>\r\n                  <rect" +
                    " x=\"134\" y=\"190\" width=\"9\" height=\"9\" rx=\"2\" fill=\"#FF2D8D\"/>\r\n                 " +
                    " <rect x=\"145\" y=\"190\" width=\"9\" height=\"9\" rx=\"2\" fill=\"#4ade80\"/>\r\n           " +
                    "       <rect x=\"134\" y=\"201\" width=\"9\" height=\"9\" rx=\"2\" fill=\"#fbbf24\"/>\r\n     " +
                    "             <rect x=\"145\" y=\"201\" width=\"9\" height=\"9\" rx=\"2\" fill=\"#60a5fa\"/>\r" +
                    "\n                  <rect x=\"134\" y=\"212\" width=\"9\" height=\"6\" rx=\"2\" fill=\"#a78b" +
                    "fa\"/>\r\n                  <rect x=\"145\" y=\"212\" width=\"9\" height=\"6\" rx=\"2\" fill=" +
                    "\"#FF2D8D\"/>\r\n                  <rect x=\"72\" y=\"103\" width=\"16\" height=\"26\" rx=\"7" +
                    "\" fill=\"#f5c5a3\"/>\r\n                  <ellipse cx=\"80\" cy=\"82\" rx=\"36\" ry=\"40\" f" +
                    "ill=\"#f5c5a3\"/>\r\n                  <path d=\"M44 72 Q46 34 80 32 Q114 34 116 72 Q" +
                    "106 50 80 52 Q54 50 44 72Z\" fill=\"#2d1a08\"/>\r\n                  <ellipse cx=\"80\"" +
                    " cy=\"36\" rx=\"18\" ry=\"12\" fill=\"#2d1a08\"/>\r\n                  <ellipse cx=\"68\" cy" +
                    "=\"86\" rx=\"5.5\" ry=\"6.5\" fill=\"white\"/>\r\n                  <ellipse cx=\"92\" cy=\"8" +
                    "6\" rx=\"5.5\" ry=\"6.5\" fill=\"white\"/>\r\n                  <ellipse cx=\"69\" cy=\"87\" " +
                    "rx=\"3.2\" ry=\"3.8\" fill=\"#1a0a0a\"/>\r\n                  <ellipse cx=\"93\" cy=\"87\" r" +
                    "x=\"3.2\" ry=\"3.8\" fill=\"#1a0a0a\"/>\r\n                  <ellipse cx=\"70\" cy=\"86\" rx" +
                    "=\"1.3\" ry=\"1.6\" fill=\"white\"/>\r\n                  <ellipse cx=\"94\" cy=\"86\" rx=\"1" +
                    ".3\" ry=\"1.6\" fill=\"white\"/>\r\n                  <path d=\"M73 100 Q80 107 87 100\" " +
                    "stroke=\"#c27a5a\" stroke-width=\"1.8\" fill=\"none\" stroke-linecap=\"round\"/>\r\n      " +
                    "            <path d=\"M62 78 Q68 75 74 77\" stroke=\"#2d1a08\" stroke-width=\"2\" fill" +
                    "=\"none\" stroke-linecap=\"round\"/>\r\n                  <path d=\"M86 77 Q92 75 98 78" +
                    "\" stroke=\"#2d1a08\" stroke-width=\"2\" fill=\"none\" stroke-linecap=\"round\"/>\r\n      " +
                    "          </svg>\r\n              </div>\r\n\r\n              <div class=\"poster-foote" +
                    "r\">\r\n                <div class=\"pf-item\">📍 Sifal, Chabahil, Kathmandu</div>\r\n " +
                    "               <div class=\"pf-item\">📞 01-4589134 | 9801644458</div>\r\n          " +
                    "      <div class=\"pf-item\">🌐 www.texascollege.edu.np</div>\r\n              </div" +
                    ">\r\n            </div>\r\n          </div>\r\n          <div class=\"poster-glow\"></di" +
                    "v>\r\n        </div>\r\n      </div>\r\n    </div>\r\n\r\n    <!-- AFFILIATION BANNER -->\r" +
                    "\n    <div class=\"affil-banner fade-up d4\">\r\n      <div class=\"affil-left\">\r\n    " +
                    "    <div class=\"affil-label\">Affiliated with</div>\r\n        <div class=\"affil-na" +
                    "me\">Lincoln University <span>College</span></div>\r\n        <div class=\"affil-sub" +
                    "\">Petaling Jaya, Malaysia · Est. 2002</div>\r\n      </div>\r\n\r\n      <div class=\"a" +
                    "ffil-divider\"></div>\r\n\r\n      <div class=\"affil-pills\">\r\n        <div class=\"api" +
                    "ll\"><span class=\"apill-icon\">✅</span> MQA Accredited</div>\r\n        <div class=\"" +
                    "apill\"><span class=\"apill-icon\">🎓</span> TU Equivalent</div>\r\n        <div clas" +
                    "s=\"apill\"><span class=\"apill-icon\">📜</span> MoE Approved</div>\r\n        <div cl" +
                    "ass=\"apill\"><span class=\"apill-icon\">🌏</span> Globally Recognised</div>\r\n      " +
                    "  <div class=\"apill\"><span class=\"apill-icon\">🏆</span> Top-ranked College</div>" +
                    "\r\n      </div>\r\n\r\n     <div class=\"affil-right\">\r\n  <a href=\"https://www.lincoln" +
                    ".edu.my\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"btn-learn\" style=\"text" +
                    "-decoration: none; display: inline-flex; align-items: center; gap: 8px;\">\r\n    L" +
                    "earn More\r\n    <svg width=\"13\" height=\"13\" fill=\"none\" stroke=\"currentColor\" str" +
                    "oke-width=\"2.5\" viewBox=\"0 0 24 24\">\r\n      <path d=\"M18 13v6a2 2 0 01-2 2H5a2 2" +
                    " 0 01-2-2V8a2 2 0 012-2h6\"/>\r\n      <polyline points=\"15 3 21 3 21 9\"/>\r\n      <" +
                    "line x1=\"10\" y1=\"14\" x2=\"21\" y2=\"3\"/>\r\n    </svg>\r\n  </a>\r\n</div>\r\n    </div>\r\n\r" +
                    "\n  \r\n   \r\n\r\n  </div>\r\n</main>\r\n\r\n<script>\r\n    const semesterData = [\r\n        {" +
                    " label: \"First Sem\", icon: \"1️⃣\", subjects: [\"Discrete Maths\", \"C Programming\", " +
                    "\"Digital Logic\", \"Physics\", \"English\"] },\r\n        { label: \"Second Sem\", icon: " +
                    "\"2️⃣\", subjects: [\"Data Structures\", \"OOP (Java)\", \"Calculus\", \"Statistics\", \"Mi" +
                    "croprocessor\"] },\r\n        { label: \"Third Sem\", icon: \"3️⃣\", subjects: [\"DBMS\"," +
                    " \"Computer Networks\", \"OS\", \"Web Tech\", \"Numerical Methods\"] },\r\n        { label" +
                    ": \"Fourth Sem\", icon: \"4️⃣\", subjects: [\"Software Engineering\", \"AI\", \"Computer " +
                    "Graphics\", \"Theory of Computation\", \"Management Info Sys\"] },\r\n        { label: " +
                    "\"Fifth Sem\", icon: \"5️⃣\", subjects: [\"Advanced Java\", \"Cloud Computing\", \"Mobile" +
                    " App Dev\", \"Information Security\", \"Project Mgmt\"] },\r\n        { label: \"Sixth S" +
                    "em\", icon: \"6️⃣\", subjects: [\"Machine Learning\", \"Big Data\", \"DevOps\", \"IoT\", \"R" +
                    "esearch Methods\"] },\r\n        { label: \"Seventh Sem\", icon: \"7️⃣\", subjects: [\"C" +
                    "apstone Project\", \"Internship\", \"Elective I\", \"Elective II\", \"Advanced Topics\"] " +
                    "},\r\n        { label: \"Eighth Sem\", icon: \"8️⃣\", subjects: [\"Final Project\", \"Dis" +
                    "sertation\", \"Viva Voce\", \"Elective III\"] },\r\n    ];\r\n\r\n    const menu = document" +
                    ".getElementById(\'semMenu\');\r\n    semesterData.forEach((sem, i) => {\r\n        con" +
                    "st el = document.createElement(\'div\');\r\n        el.className = \'sem-item\' + (i =" +
                    "== 0 ? \' open\' : \'\');\r\n        el.innerHTML = `\r\n      <div class=\"sem-header${i" +
                    " === 0 ? \' active\' : \'\'}\" onclick=\"toggleSem(this)\">\r\n        <div class=\"sem-ic" +
                    "on\">${sem.icon}</div>\r\n        <span class=\"sem-label\">${sem.label}</span>\r\n    " +
                    "    <svg class=\"sem-chevron\" width=\"13\" height=\"13\" fill=\"none\" stroke=\"currentC" +
                    "olor\" stroke-width=\"2.5\" viewBox=\"0 0 24 24\"><path d=\"M19 9l-7 7-7-7\"/></svg>\r\n " +
                    "     </div>\r\n      <div class=\"sem-subjects\">\r\n        ${sem.subjects.map((s, j)" +
                    " => `<div class=\"subject-link${i === 0 && j === 0 ? \' active\' : \'\'}\" onclick=\"pi" +
                    "ckSubject(this)\"><div class=\"subject-dot\"></div>${s}</div>`).join(\'\')}\r\n      </" +
                    "div>`;\r\n        menu?.appendChild(el);\r\n    });\r\n\r\n    function toggleSem(el: an" +
                    "y) {\r\n        el.parentElement.classList.toggle(\'open\');\r\n    }\r\n\r\n    function " +
                    "pickSubject(el: any) {\r\n        document.querySelectorAll(\'.subject-link\').forEa" +
                    "ch(l => l.classList.remove(\'active\'));\r\n        el.classList.add(\'active\');\r\n   " +
                    "     if (window.innerWidth < 900) closeSidebar();\r\n    }\r\n\r\n    function scrollT" +
                    "oCourses() {\r\n        document.getElementById(\'coursesSection\')?.scrollIntoView(" +
                    "{ behavior: \'smooth\', block: \'start\' });\r\n    }\r\n\r\n    // function toggleSidebar" +
                    "() {\r\n    //     document.getElementById(\'sidebar\').classList.toggle(\'open\');\r\n " +
                    "   //     document.getElementById(\'overlay\').classList.toggle(\'show\');\r\n    // }" +
                    "\r\n\r\n    function closeSidebar() {\r\n        document.getElementById(\'sidebar\')?.c" +
                    "lassList.remove(\'open\');\r\n        document.getElementById(\'overlay\')?.classList." +
                    "remove(\'show\');\r\n    }\r\n</script>\r\n\r\n");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        255,
                        48518,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.WebTools.BrowserLink.Runtime.WebForms.TraceHelpers, Microsoft.WebTools." +
                    "BrowserLink.Tracing, Version=18.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f1" +
                    "1d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.bit_notes_dash_aspx.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.bit_notes_dash_aspx.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent1(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 3 "D:\Learningportal\Learning-System\Bit_Notes\dash.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 3 "D:\Learningportal\Learning-System\Bit_Notes\dash.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(bit_notes_dash_aspx @__ctrl) {
            
            #line 1 "D:\Learningportal\Learning-System\Bit_Notes\dash.aspx"
            @__ctrl.Title = "";
            
            #line default
            #line hidden
            
            #line 1 "D:\Learningportal\Learning-System\Bit_Notes\dash.aspx"
            @__ctrl.MasterPageFile = "~/Bit_Notes/note.Master";
            
            #line default
            #line hidden
            
            #line 1 "D:\Learningportal\Learning-System\Bit_Notes\dash.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 3 "D:\Learningportal\Learning-System\Bit_Notes\dash.aspx"
            this.AddContentTemplate("ContentPlaceHolder1", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent1)));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.bit_notes_dash_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -708851166;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
